#!/usr/bin/env bash
# Select and deploy one approved immutable Sutra ECR release on the retained
# EC2 host. Intended entry point:
#
#   aws ssm send-command --instance-ids i-... \
#     --document-name AWS-RunShellScript \
#     --parameters 'commands=["sudo /usr/local/sbin/sutra-release-update 123456789012.dkr.ecr.ap-south-1.amazonaws.com/sutra/app@sha256:..."]'
#
# The instance role can pull only the account-local sutra/app repository, so a
# caller cannot use this path to introduce a bundle from another registry.
set -Eeuo pipefail

log() { printf '[sutra:release] %s\n' "$*"; }
die() { printf '[sutra:release:error] %s\n' "$*" >&2; exit 1; }

[[ "${EUID}" -eq 0 ]] || die "Run as root (SSM AWS-RunShellScript already does this)."
[[ "$#" -eq 1 ]] || die "Usage: sutra-release-update <account-local-sutra/app@sha256:digest>"

ROOT=/opt/sutra
CONFIG=/etc/sutra-release.conf
ENV_EC2="$ROOT/deploy/ec2/.env.ec2"
DOCKER_ENV="$ROOT/.sutra/docker.env"
NEW_IMAGE="$1"
HELPER_IMAGE="postgres:18.4-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15"

[[ -f "$CONFIG" ]] || die "$CONFIG is missing; repair the CloudFormation-managed host first."
# This file is generated by root-only CloudFormation user data and contains no
# secrets. Reject a writable or non-root file before sourcing it.
[[ "$(stat -c '%u' "$CONFIG")" == 0 ]] || die "$CONFIG must be owned by root."
config_mode="$(stat -c '%a' "$CONFIG")"
[[ "$config_mode" == 644 || "$config_mode" == 600 || "$config_mode" == 400 ]] || die "$CONFIG has unsafe mode $config_mode."
# shellcheck disable=SC1090
source "$CONFIG"

[[ "${SUTRA_ECR_REGISTRY:-}" =~ ^[0-9]{12}\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com$ ]] || die "Invalid release registry boundary."
[[ "${SUTRA_ECR_REPOSITORY:-}" == sutra/app ]] || die "Invalid release repository boundary."
[[ "${SUTRA_AWS_REGION:-}" =~ ^[a-z]{2}-[a-z]+-[0-9]+$ ]] || die "Invalid release region boundary."
EXPECTED_PREFIX="$SUTRA_ECR_REGISTRY/$SUTRA_ECR_REPOSITORY@sha256:"
[[ "$NEW_IMAGE" == "$EXPECTED_PREFIX"* ]] || die "Release must come from $SUTRA_ECR_REGISTRY/$SUTRA_ECR_REPOSITORY."
NEW_DIGEST="${NEW_IMAGE#"$EXPECTED_PREFIX"}"
[[ "$NEW_DIGEST" =~ ^[0-9a-f]{64}$ ]] || die "Release must use an immutable sha256 digest."
[[ -f "$ENV_EC2" && -f "$DOCKER_ENV" ]] || die "Runtime environment is incomplete; run bootstrap first."

PROFILE_ARGS=()
if grep -Eq '^SUTRA_NOTIFICATIONS_ENABLED=true$' "$ENV_EC2"; then
  PROFILE_ARGS=(--profile notifications)
fi
COMPOSE=(docker compose -f "$ROOT/deploy/ec2/compose.prod.yaml" --env-file "$ENV_EC2" --env-file "$DOCKER_ENV" "${PROFILE_ARGS[@]}")
# Release safety must not depend on whether a particular Compose version shows
# already-running, profile-gated containers when that profile is inactive.
# Explicitly activate every declared profile for stop/status control so a
# notification worker cannot write application state during the snapshot or
# database migration even when notifications were subsequently disabled.
ALL_PROFILES_COMPOSE=(docker compose -f "$ROOT/deploy/ec2/compose.prod.yaml" --env-file "$ENV_EC2" --env-file "$DOCKER_ENV" --profile "*")
application_volume() {
  local container volume
  container="$("${COMPOSE[@]}" ps -aq app | head -n1)"
  [[ "$container" =~ ^[0-9a-f]{12,64}$ ]] || die "The Sutra application container is unavailable for a release snapshot."
  volume="$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/app/.sutra"}}{{.Name}}{{end}}{{end}}' "$container")"
  [[ "$volume" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$ ]] || die "The Sutra application-data volume is invalid."
  printf '%s\n' "$volume"
}
archive_application_data() {
  local volume="$1" directory="$2"
  local free_bytes snapshot_bytes
  free_bytes="$(df -P -B1 "$directory" | awk 'NR == 2 {print $4}')"
  [[ "$free_bytes" =~ ^[0-9]+$ ]] || die "Available release-snapshot disk space could not be determined."
  (( free_bytes >= 1073741824 )) || die "At least 1 GiB of free disk is required before capturing release state."
  # The app owns this volume with restrictive permissions. Keep the helper
  # otherwise capability-free, but grant only the read/traverse capability
  # required to capture every tenant-scoped state file.
  docker run --rm --network none --read-only --user 0:0 \
    --cap-drop ALL --cap-add DAC_READ_SEARCH \
    --ulimit fsize=536870912:536870912 \
    --security-opt no-new-privileges:true \
    --volume "$volume:/source:ro" --volume "$directory:/backup" "$HELPER_IMAGE" \
    sh -ec 'tar -C /source -czf /backup/application-data.tar.gz .'
  snapshot_bytes="$(stat -c '%s' "$directory/application-data.tar.gz")"
  (( snapshot_bytes > 0 && snapshot_bytes <= 536870912 )) || die "Application-data release snapshot exceeds the 512-MiB safety limit; run a coordinated backup and prune durable queues before release."
  (cd "$directory" && sha256sum application-data.tar.gz > application-data.tar.gz.sha256)
  chmod 0600 "$directory/application-data.tar.gz" "$directory/application-data.tar.gz.sha256"
}
restore_application_data() {
  local volume="$1" directory="$2"
  (cd "$directory" && sha256sum --check application-data.tar.gz.sha256 >/dev/null)
  # Rollback must be able to replace files owned by the unprivileged app UID.
  # DAC_OVERRIDE and CHOWN are scoped to this offline, networkless one-shot
  # helper so restored files remain readable by the unprivileged app UID.
  docker run --rm --network none --user 0:0 \
    --cap-drop ALL --cap-add DAC_OVERRIDE --cap-add CHOWN \
    --security-opt no-new-privileges:true \
    --volume "$volume:/target" --volume "$directory:/backup:ro" "$HELPER_IMAGE" \
    sh -ec 'tar -tzf /backup/application-data.tar.gz >/dev/null; find /target -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +; tar -C /target -xzf /backup/application-data.tar.gz'
}

exec 8>/run/lock/sutra-data-mutation.lock
flock -n 8 || die "Another release, backup, or restore is already running."
exec 9>/run/lock/sutra-release-update.lock
flock -n 9 || die "Another release update is already running."

CURRENT_IMAGE="$(awk -F= '$1 == "SUTRA_APP_IMAGE" {sub(/^[^=]*=/, ""); print; exit}' "$ENV_EC2")"
[[ "$CURRENT_IMAGE" =~ @sha256:[0-9a-f]{64}$ ]] || die "Current immutable image setting is invalid."
if [[ "$CURRENT_IMAGE" == "$NEW_IMAGE" ]]; then
  log "Requested digest is already selected; reapplying the current release."
  exec "$ROOT/deploy/ec2/redeploy.sh"
fi

log "Authenticating to the account-local release registry."
aws ecr get-login-password --region "$SUTRA_AWS_REGION" | \
  docker login --username AWS --password-stdin "$SUTRA_ECR_REGISTRY" >/dev/null
log "Pulling the approved immutable release."
docker pull "$NEW_IMAGE" >/dev/null
docker image inspect "$NEW_IMAGE" >/dev/null

STAGE_ROOT="$(mktemp -d "$ROOT/.sutra/release-stage.XXXXXX")"
RELEASE_CONTAINER="$(docker create "$NEW_IMAGE")"
SUTRA_DOMAIN="$(awk -F= '$1 == "SUTRA_DOMAIN" {sub(/^[^=]*=/, ""); print; exit}' "$ENV_EC2")"
[[ "$SUTRA_DOMAIN" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]] || \
  die "SUTRA_DOMAIN is invalid in $ENV_EC2."
PUBLIC_ORIGIN="https://www.$SUTRA_DOMAIN"
APPLICATION_VOLUME=""
BACKUP_DIR=""
ROLLBACK_DIR="$ROOT/deploy/ec2.release-rollback"
RELEASE_MUTATION_STARTED=false
BACKUP_READY=false
BUNDLE_SWITCH_STARTED=false
RELEASE_COMMITTED=false

# Use a fresh header/body file on every attempt so a transient maintenance
# response cannot contaminate the final successful verification. These checks
# run while the pre-release snapshot and bundle are still rollback-capable.
PUBLIC_HEADERS=""
PUBLIC_BODY=""
PUBLIC_STATUS="000"
# Identifies this verifier to the CDN edge. These requests originate from the
# release host — an AWS datacenter address with a non-browser client — which is
# exactly the profile Cloudflare Bot Fight Mode and the managed WAF rules block.
# A blocked verification returns 403 and rolls back a release that had already
# deployed and gone healthy, so the edge must be able to recognise and skip these
# requests specifically.
#
# Deliberately NOT a shared secret: a header token that grants a WAF bypass is a
# credential to leak and rotate. The edge rule instead matches this User-Agent
# together with the release host's own egress IP, which is not forgeable by a
# third party and needs nothing kept secret. See docs/ec2-continuous-delivery.md.
RELEASE_VERIFIER_UA="sutra-release-verifier/1 (+deploy/ec2/release-update.sh)"
fetch_public() {
  local path="$1" label="$2" attempts="$3" attempt
  PUBLIC_HEADERS="$STAGE_ROOT/public-$label.headers"
  PUBLIC_BODY="$STAGE_ROOT/public-$label.body"
  PUBLIC_STATUS="000"
  for ((attempt = 1; attempt <= attempts; attempt += 1)); do
    if PUBLIC_STATUS="$(curl --silent --show-error \
      --connect-timeout 10 --max-time 15 \
      --user-agent "$RELEASE_VERIFIER_UA" \
      --header 'X-Sutra-Release-Verifier: 1' \
      --dump-header "$PUBLIC_HEADERS" --output "$PUBLIC_BODY" \
      --write-out '%{http_code}' "$PUBLIC_ORIGIN$path")" \
      && [[ "$PUBLIC_STATUS" == 200 ]]; then
      return 0
    fi
    (( attempt == attempts )) || sleep 5
  done
  # Name the two very different causes of a non-200 here. Without this, an edge
  # block and a broken release produce the same one-line message, and the
  # operator's first instinct is to suspect the release — which is the wrong
  # place to look and costs an hour.
  if [[ "$PUBLIC_STATUS" == 403 || "$PUBLIC_STATUS" == 429 || "$PUBLIC_STATUS" == 503 ]]; then
    die "$PUBLIC_ORIGIN$path returned $PUBLIC_STATUS during the release transaction. \
The application container reported healthy before this check ran, so a $PUBLIC_STATUS \
here is far more likely to be the CDN edge blocking this verifier (Bot Fight Mode, a \
managed WAF rule, or rate limiting) than a bad release: the request comes from an AWS \
address with a non-browser client. Confirm with 'curl -sD - $PUBLIC_ORIGIN$path' from \
this host and look for cf-mitigated / an 'Attention Required' body. The edge must skip \
requests carrying User-Agent '$RELEASE_VERIFIER_UA' from this host's egress IP; see \
docs/ec2-continuous-delivery.md. The release has been rolled back regardless."
  fi
  die "$PUBLIC_ORIGIN$path did not return HTTP 200 during the release transaction (last status: $PUBLIC_STATUS)."
}

require_indexable_response() {
  local label="$1"
  if tr -d '\r' < "$PUBLIC_HEADERS" | grep -Eiq '^x-robots-tag:.*noindex'; then
    die "$PUBLIC_ORIGIN returned a noindex response for $label."
  fi
}

verify_public_release() {
  local apex_headers apex_location apex_status label path security_expected
  local security_well_known_body served_image turnstile_site_key
  command -v curl >/dev/null 2>&1 || die "curl is required for public release verification."

  fetch_public "/api/healthz" "health" 12
  served_image="$(tr -d '\r' < "$PUBLIC_HEADERS" | awk '
    tolower($1) == "x-sutra-release-image:" {
      $1 = ""; sub(/^[[:space:]]+/, ""); print
    }
  ' | tail -n1)"
  [[ "$served_image" == "$NEW_IMAGE" ]] || \
    die "The public origin served '$served_image' instead of the selected immutable release."

  for path in /api/status /login; do
    label="${path//\//-}"
    fetch_public "$path" "$label" 3
  done

  # A 200 login shell is not enough: the page disables submission until this
  # public runtime contract proves that the selected image loaded the real
  # network widget rather than a stale/local bypass or invalid runtime
  # configuration. This endpoint invokes the same fail-closed resolver as each
  # protected mutation while exposing only the intentionally public site key.
  turnstile_site_key="$(awk -F= '$1 == "SUTRA_TURNSTILE_SITE_KEY" {sub(/^[^=]*=/, ""); print; exit}' "$ENV_EC2")"
  fetch_public "/api/turnstile/config" "turnstile-config" 3
  [[ "$(cat "$PUBLIC_BODY")" == "{\"enabled\":true,\"siteKey\":\"$turnstile_site_key\"}" ]] || \
    die "The public Turnstile runtime is disabled, stale, or misconfigured."

  for path in / /about /contact /security /privacy /terms /status /robots.txt /sitemap.xml; do
    label="${path//\//-}"
    [[ "$path" == / ]] && label="home"
    fetch_public "$path" "indexable-$label" 3
    require_indexable_response "$path"
    if [[ "$path" == "/robots.txt" ]]; then
      grep -Fqx "Sitemap: $PUBLIC_ORIGIN/sitemap.xml" "$PUBLIC_BODY" || \
        die "The public robots.txt does not advertise the canonical sitemap."
    elif [[ "$path" == "/sitemap.xml" ]]; then
      grep -Fq "<loc>$PUBLIC_ORIGIN/</loc>" "$PUBLIC_BODY" || \
        die "The public sitemap does not contain the canonical site origin."
    fi
  done

  # These files are served by the version-controlled Caddy maintenance mount
  # and may also be cached at Cloudflare. Compare the public bodies byte for
  # byte with the selected bundle and with each other before committing the
  # host mutation. This catches a healthy app deployed behind a stale edge
  # process or stale alternate-path response.
  security_expected="$ROOT/deploy/ec2/maintenance/security.txt"
  [[ -s "$security_expected" ]] || die "The selected release has no canonical security.txt document."
  fetch_public "/.well-known/security.txt" "security-well-known" 3
  tr -d '\r' < "$PUBLIC_HEADERS" | \
    grep -Eiq '^content-type:[[:space:]]*text/plain([[:space:]]*;[[:space:]]*charset=utf-8)?[[:space:]]*$' || \
    die "The public /.well-known/security.txt response is not text/plain."
  cmp -s "$PUBLIC_BODY" "$security_expected" || \
    die "The public /.well-known/security.txt bytes differ from the selected release."
  security_well_known_body="$PUBLIC_BODY"

  fetch_public "/security.txt" "security-root" 3
  tr -d '\r' < "$PUBLIC_HEADERS" | \
    grep -Eiq '^content-type:[[:space:]]*text/plain([[:space:]]*;[[:space:]]*charset=utf-8)?[[:space:]]*$' || \
    die "The public /security.txt response is not text/plain."
  cmp -s "$PUBLIC_BODY" "$security_expected" || \
    die "The public /security.txt bytes differ from the selected release."
  cmp -s "$PUBLIC_BODY" "$security_well_known_body" || \
    die "The two public security.txt paths do not return identical bytes."

  apex_headers="$STAGE_ROOT/public-apex.headers"
  apex_status="$(curl --silent --show-error \
    --connect-timeout 10 --max-time 15 \
    --dump-header "$apex_headers" --output /dev/null \
    --write-out '%{http_code}' "https://$SUTRA_DOMAIN/")"
  apex_location="$(tr -d '\r' < "$apex_headers" | awk '
    tolower($1) == "location:" {
      $1 = ""; sub(/^[[:space:]]+/, ""); print
    }
  ' | tail -n1)"
  [[ "$apex_status" == 308 && "$apex_location" == "$PUBLIC_ORIGIN/" ]] || \
    die "The apex domain did not redirect exactly to the canonical public origin."
}

cleanup() {
  local rc=$?
  trap - EXIT INT TERM
  if (( rc != 0 )) && [[ "$RELEASE_MUTATION_STARTED" == true && "$RELEASE_COMMITTED" != true ]]; then
    set +e
    log "Release transaction failed; recovering the prior application state and host bundle."
    "${ALL_PROFILES_COMPOSE[@]}" stop -t 30 notification-worker >/dev/null 2>&1 || true
    "${COMPOSE[@]}" stop -t 30 app >/dev/null 2>&1 || true
    if [[ "$BACKUP_READY" == true ]]; then
      if ! restore_application_data "$APPLICATION_VOLUME" "$BACKUP_DIR"; then
        log "Automatic application-data recovery failed; preserve $BACKUP_DIR for emergency recovery."
      fi
    fi
    if [[ "$BUNDLE_SWITCH_STARTED" == true ]]; then
      if [[ -d "$ROLLBACK_DIR" ]]; then
        rm -rf "$ROOT/deploy/ec2"
        mv "$ROLLBACK_DIR" "$ROOT/deploy/ec2"
        install -m 0755 "$BACKUP_DIR/docker/postgres-init.sh" "$ROOT/docker/postgres-init.sh"
        if [[ -f "$BACKUP_DIR/cloudflared-config.yml" ]]; then
          rollback_cloudflared_config="$ROOT/.sutra/cloudflared/config.yml.rollback.$$"
          install -o 65532 -g 65532 -m 0400 \
            "$BACKUP_DIR/cloudflared-config.yml" "$rollback_cloudflared_config"
          mv -f "$rollback_cloudflared_config" "$ROOT/.sutra/cloudflared/config.yml"
        else
          log "Prior named-tunnel routing is missing from $BACKUP_DIR; manual recovery may be required."
        fi
        install -m 0644 "$ROOT/deploy/ec2/sutra.service" /etc/systemd/system/sutra.service
        install -m 0755 "$ROOT/deploy/ec2/release-update.sh" /usr/local/sbin/sutra-release-update
        systemctl daemon-reload
      else
        log "Prior host bundle is missing from $ROLLBACK_DIR; manual recovery is required."
      fi
    fi
    if [[ -x "$ROOT/deploy/ec2/redeploy.sh" ]]; then
      if "$ROOT/deploy/ec2/redeploy.sh" >/dev/null 2>&1; then
        # The immediately prior bundle may predate explicit edge-process
        # recreation. Force both services onto the restored Caddyfile,
        # maintenance assets and ignored tunnel-config inode.
        "${COMPOSE[@]}" up -d --wait --no-build --no-deps --force-recreate caddy >/dev/null 2>&1 || \
          log "Prior Caddy edge did not reload automatically; use $BACKUP_DIR for emergency recovery."
        "${COMPOSE[@]}" up -d --wait --no-build --no-deps --force-recreate cloudflared >/dev/null 2>&1 || \
          log "Prior named tunnel did not reload automatically; use $BACKUP_DIR for emergency recovery."
      else
        log "Prior release did not restart automatically; use $BACKUP_DIR for emergency recovery."
      fi
    fi
    set -e
  fi
  docker rm -f "$RELEASE_CONTAINER" >/dev/null 2>&1 || true
  rm -rf "$STAGE_ROOT" || true
  exit "$rc"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

install -d -m 0755 "$STAGE_ROOT/deploy/ec2" "$STAGE_ROOT/docker"
docker cp "$RELEASE_CONTAINER:/app/deploy/ec2/." "$STAGE_ROOT/deploy/ec2/"
docker cp "$RELEASE_CONTAINER:/app/docker/postgres-init.sh" "$STAGE_ROOT/docker/postgres-init.sh"
docker rm -f "$RELEASE_CONTAINER" >/dev/null
RELEASE_CONTAINER=""

for required in \
  compose.prod.yaml .env.ec2.example Caddyfile cloudflared-config.yml.example \
  maintenance/security.txt bootstrap.sh redeploy.sh release-update.sh sutra.service; do
  [[ -f "$STAGE_ROOT/deploy/ec2/$required" ]] || die "Release bundle is missing deploy/ec2/$required."
done
[[ -f "$STAGE_ROOT/docker/postgres-init.sh" ]] || die "Release bundle is missing docker/postgres-init.sh."
bash -n \
  "$STAGE_ROOT/deploy/ec2/bootstrap.sh" \
  "$STAGE_ROOT/deploy/ec2/redeploy.sh" \
  "$STAGE_ROOT/deploy/ec2/release-update.sh" \
  "$STAGE_ROOT/docker/postgres-init.sh"

# Preserve all operator settings while replacing only the immutable digest.
awk -v image="$NEW_IMAGE" '
  BEGIN { found = 0 }
  /^SUTRA_APP_IMAGE=/ { print "SUTRA_APP_IMAGE=" image; found = 1; next }
  { print }
  END { if (!found) print "SUTRA_APP_IMAGE=" image }
' "$ENV_EC2" > "$STAGE_ROOT/deploy/ec2/.env.ec2"
chmod 0600 "$STAGE_ROOT/deploy/ec2/.env.ec2"

# Render before touching the active host bundle. This catches malformed Compose
# changes, missing environment keys and relative-volume regressions.
docker compose \
  -f "$STAGE_ROOT/deploy/ec2/compose.prod.yaml" \
  --env-file "$STAGE_ROOT/deploy/ec2/.env.ec2" \
  --env-file "$DOCKER_ENV" config --quiet

BACKUP_ROOT="$ROOT/.sutra/host-releases"
install -d -m 0700 "$BACKUP_ROOT"
BACKUP_DIR="$BACKUP_ROOT/$(date -u +%Y%m%dT%H%M%SZ)-$$-${CURRENT_IMAGE##*@sha256:}"
[[ ! -e "$BACKUP_DIR" ]] || die "The release backup directory already exists."
install -d -m 0700 "$BACKUP_DIR/deploy" "$BACKUP_DIR/docker"
cp -a "$ROOT/deploy/ec2" "$BACKUP_DIR/deploy/ec2"
cp -a "$ROOT/docker/postgres-init.sh" "$BACKUP_DIR/docker/postgres-init.sh"
cp -a "$ROOT/.sutra/cloudflared/config.yml" "$BACKUP_DIR/cloudflared-config.yml"
APPLICATION_VOLUME="$(application_volume)"
RELEASE_MUTATION_STARTED=true
"${ALL_PROFILES_COMPOSE[@]}" stop -t 30 notification-worker >/dev/null
"${COMPOSE[@]}" stop -t 30 app >/dev/null
if "${COMPOSE[@]}" ps --services --filter status=running | grep -Fxq app; then
  die "The Sutra application did not quiesce for its release snapshot."
fi
if "${ALL_PROFILES_COMPOSE[@]}" ps --services --filter status=running | grep -Fxq notification-worker; then
  die "The notification worker did not quiesce before release migration."
fi
archive_application_data "$APPLICATION_VOLUME" "$BACKUP_DIR"
BACKUP_READY=true

# Never replace current customer state with a historical snapshot merely
# because an older image digest was selected. That would silently discard
# accounts/jobs created since that digest last ran while leaving PostgreSQL at
# its current schema and data. The selected image must read the current state;
# otherwise its health failure atomically restores this pre-release snapshot
# and the prior image. Historical snapshots remain emergency evidence only.

rm -rf "$ROLLBACK_DIR"
BUNDLE_SWITCH_STARTED=true
mv "$ROOT/deploy/ec2" "$ROLLBACK_DIR"
mv "$STAGE_ROOT/deploy/ec2" "$ROOT/deploy/ec2"
install -m 0755 "$STAGE_ROOT/docker/postgres-init.sh" "$ROOT/docker/postgres-init.sh"
install -m 0644 "$ROOT/deploy/ec2/sutra.service" /etc/systemd/system/sutra.service
install -m 0755 "$ROOT/deploy/ec2/release-update.sh" /usr/local/sbin/sutra-release-update
systemctl daemon-reload

log "Applying the new bundle and database migration."
set +e
"$ROOT/deploy/ec2/redeploy.sh"
update_status=$?
set -e
if [[ "$update_status" -ne 0 ]]; then
  die "New release did not become healthy; automatic prior-release recovery was started."
fi

# Do not commit the host mutation until the Cloudflare-facing canonical origin
# proves that it is serving this exact digest and crawl-control assets. Any
# failure here exits through cleanup(), which restores the prior image, bundle
# and application-data snapshot.
verify_public_release

RELEASE_COMMITTED=true
rm -rf "$ROLLBACK_DIR"

# Keep three encrypted-at-rest host bundle copies. ECR lifecycle independently
# keeps the three deployable image releases; older local app images are removed
# only after the new release has passed its health checks.
mapfile -t old_bundles < <(find "$BACKUP_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' | sort -rn | tail -n +4 | cut -d' ' -f2-)
if ((${#old_bundles[@]})); then rm -rf -- "${old_bundles[@]}"; fi
docker image rm "$CURRENT_IMAGE" >/dev/null 2>&1 || true
docker image prune -f >/dev/null

log "Release update completed and the site is healthy."
