#!/usr/bin/env bash
# Select and deploy one approved immutable Sutra ECR release on the retained
# EC2 host. Intended entry point:
#
#   aws ssm send-command --instance-ids i-... \
#     --document-name AWS-RunShellScript \
#     --parameters 'commands=["sudo /usr/local/sbin/sutra-release-update 123456789012.dkr.ecr.ap-south-1.amazonaws.com/sutra/app@sha256:..."]'
#
# The instance role can pull only the account-local sutra/app repository, so a
# caller cannot use this path to introduce a bundle from another registry.
set -Eeuo pipefail

log() { printf '[sutra:release] %s\n' "$*"; }
die() { printf '[sutra:release:error] %s\n' "$*" >&2; exit 1; }

[[ "${EUID}" -eq 0 ]] || die "Run as root (SSM AWS-RunShellScript already does this)."
[[ "$#" -eq 1 ]] || die "Usage: sutra-release-update <account-local-sutra/app@sha256:digest>"

ROOT=/opt/sutra
CONFIG=/etc/sutra-release.conf
ENV_EC2="$ROOT/deploy/ec2/.env.ec2"
DOCKER_ENV="$ROOT/.sutra/docker.env"
NEW_IMAGE="$1"

[[ -f "$CONFIG" ]] || die "$CONFIG is missing; repair the CloudFormation-managed host first."
# This file is generated by root-only CloudFormation user data and contains no
# secrets. Reject a writable or non-root file before sourcing it.
[[ "$(stat -c '%u' "$CONFIG")" == 0 ]] || die "$CONFIG must be owned by root."
config_mode="$(stat -c '%a' "$CONFIG")"
[[ "$config_mode" == 644 || "$config_mode" == 600 || "$config_mode" == 400 ]] || die "$CONFIG has unsafe mode $config_mode."
# shellcheck disable=SC1090
source "$CONFIG"

[[ "${SUTRA_ECR_REGISTRY:-}" =~ ^[0-9]{12}\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com$ ]] || die "Invalid release registry boundary."
[[ "${SUTRA_ECR_REPOSITORY:-}" == sutra/app ]] || die "Invalid release repository boundary."
[[ "${SUTRA_AWS_REGION:-}" =~ ^[a-z]{2}-[a-z]+-[0-9]+$ ]] || die "Invalid release region boundary."
EXPECTED_PREFIX="$SUTRA_ECR_REGISTRY/$SUTRA_ECR_REPOSITORY@sha256:"
[[ "$NEW_IMAGE" == "$EXPECTED_PREFIX"* ]] || die "Release must come from $SUTRA_ECR_REGISTRY/$SUTRA_ECR_REPOSITORY."
NEW_DIGEST="${NEW_IMAGE#"$EXPECTED_PREFIX"}"
[[ "$NEW_DIGEST" =~ ^[0-9a-f]{64}$ ]] || die "Release must use an immutable sha256 digest."
[[ -f "$ENV_EC2" && -f "$DOCKER_ENV" ]] || die "Runtime environment is incomplete; run bootstrap first."

exec 9>/run/lock/sutra-release-update.lock
flock -n 9 || die "Another release update is already running."

CURRENT_IMAGE="$(awk -F= '$1 == "SUTRA_APP_IMAGE" {sub(/^[^=]*=/, ""); print; exit}' "$ENV_EC2")"
[[ "$CURRENT_IMAGE" =~ @sha256:[0-9a-f]{64}$ ]] || die "Current immutable image setting is invalid."
if [[ "$CURRENT_IMAGE" == "$NEW_IMAGE" ]]; then
  log "Requested digest is already selected; reapplying the current release."
  exec "$ROOT/deploy/ec2/redeploy.sh"
fi

log "Authenticating to the account-local release registry."
aws ecr get-login-password --region "$SUTRA_AWS_REGION" | \
  docker login --username AWS --password-stdin "$SUTRA_ECR_REGISTRY" >/dev/null
log "Pulling the approved immutable release."
docker pull "$NEW_IMAGE" >/dev/null
docker image inspect "$NEW_IMAGE" >/dev/null

STAGE_ROOT="$(mktemp -d "$ROOT/.sutra/release-stage.XXXXXX")"
RELEASE_CONTAINER="$(docker create "$NEW_IMAGE")"
cleanup() {
  docker rm -f "$RELEASE_CONTAINER" >/dev/null 2>&1 || true
  rm -rf "$STAGE_ROOT"
}
trap cleanup EXIT

install -d -m 0755 "$STAGE_ROOT/deploy/ec2" "$STAGE_ROOT/docker"
docker cp "$RELEASE_CONTAINER:/app/deploy/ec2/." "$STAGE_ROOT/deploy/ec2/"
docker cp "$RELEASE_CONTAINER:/app/docker/postgres-init.sh" "$STAGE_ROOT/docker/postgres-init.sh"
docker rm -f "$RELEASE_CONTAINER" >/dev/null
RELEASE_CONTAINER=""

for required in \
  compose.prod.yaml .env.ec2.example Caddyfile cloudflared-config.yml.example \
  bootstrap.sh redeploy.sh release-update.sh sutra.service; do
  [[ -f "$STAGE_ROOT/deploy/ec2/$required" ]] || die "Release bundle is missing deploy/ec2/$required."
done
[[ -f "$STAGE_ROOT/docker/postgres-init.sh" ]] || die "Release bundle is missing docker/postgres-init.sh."
bash -n \
  "$STAGE_ROOT/deploy/ec2/bootstrap.sh" \
  "$STAGE_ROOT/deploy/ec2/redeploy.sh" \
  "$STAGE_ROOT/deploy/ec2/release-update.sh" \
  "$STAGE_ROOT/docker/postgres-init.sh"

# Preserve all operator settings while replacing only the immutable digest.
awk -v image="$NEW_IMAGE" '
  BEGIN { found = 0 }
  /^SUTRA_APP_IMAGE=/ { print "SUTRA_APP_IMAGE=" image; found = 1; next }
  { print }
  END { if (!found) print "SUTRA_APP_IMAGE=" image }
' "$ENV_EC2" > "$STAGE_ROOT/deploy/ec2/.env.ec2"
chmod 0600 "$STAGE_ROOT/deploy/ec2/.env.ec2"

# Render before touching the active host bundle. This catches malformed Compose
# changes, missing environment keys and relative-volume regressions.
docker compose \
  -f "$STAGE_ROOT/deploy/ec2/compose.prod.yaml" \
  --env-file "$STAGE_ROOT/deploy/ec2/.env.ec2" \
  --env-file "$DOCKER_ENV" config --quiet

BACKUP_ROOT="$ROOT/.sutra/host-releases"
install -d -m 0700 "$BACKUP_ROOT"
BACKUP_DIR="$BACKUP_ROOT/$(date -u +%Y%m%dT%H%M%SZ)-${CURRENT_IMAGE##*@sha256:}"
install -d -m 0700 "$BACKUP_DIR/deploy" "$BACKUP_DIR/docker"
cp -a "$ROOT/deploy/ec2" "$BACKUP_DIR/deploy/ec2"
cp -a "$ROOT/docker/postgres-init.sh" "$BACKUP_DIR/docker/postgres-init.sh"

ROLLBACK_DIR="$ROOT/deploy/ec2.release-rollback"
rm -rf "$ROLLBACK_DIR"
mv "$ROOT/deploy/ec2" "$ROLLBACK_DIR"
mv "$STAGE_ROOT/deploy/ec2" "$ROOT/deploy/ec2"
install -m 0755 "$STAGE_ROOT/docker/postgres-init.sh" "$ROOT/docker/postgres-init.sh"
install -m 0644 "$ROOT/deploy/ec2/sutra.service" /etc/systemd/system/sutra.service
install -m 0755 "$ROOT/deploy/ec2/release-update.sh" /usr/local/sbin/sutra-release-update
systemctl daemon-reload

log "Applying the new bundle and database migration."
set +e
"$ROOT/deploy/ec2/redeploy.sh"
update_status=$?
set -e
if [[ "$update_status" -ne 0 ]]; then
  log "Release failed; restoring the prior host bundle and image selection."
  rm -rf "$ROOT/deploy/ec2"
  mv "$ROLLBACK_DIR" "$ROOT/deploy/ec2"
  install -m 0755 "$BACKUP_DIR/docker/postgres-init.sh" "$ROOT/docker/postgres-init.sh"
  install -m 0644 "$ROOT/deploy/ec2/sutra.service" /etc/systemd/system/sutra.service
  install -m 0755 "$ROOT/deploy/ec2/release-update.sh" /usr/local/sbin/sutra-release-update
  systemctl daemon-reload
  "$ROOT/deploy/ec2/redeploy.sh" || true
  die "New release did not become healthy; prior release was restored."
fi

rm -rf "$ROLLBACK_DIR"

# Keep three encrypted-at-rest host bundle copies. ECR lifecycle independently
# keeps the three deployable image releases; older local app images are removed
# only after the new release has passed its health checks.
mapfile -t old_bundles < <(find "$BACKUP_ROOT" -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\n' | sort -rn | tail -n +4 | cut -d' ' -f2-)
if ((${#old_bundles[@]})); then rm -rf -- "${old_bundles[@]}"; fi
docker image rm "$CURRENT_IMAGE" >/dev/null 2>&1 || true
docker image prune -f >/dev/null

log "Release update completed and the site is healthy."
