CREATE TABLE `finops_compute_optimizer_export_snapshots` (`generation_id` text PRIMARY KEY NOT NULL,`org_id` text NOT NULL,`customer_id` text NOT NULL,`connection_id` text NOT NULL,`materialization_id` text NOT NULL,`management_account_id` text NOT NULL,`source_state` text NOT NULL CHECK (`source_state`='COMPLETE'),`complete` integer NOT NULL CHECK (`complete`=1),`content_sha256` text NOT NULL,`snapshot_json` text NOT NULL,`generated_at` text NOT NULL,`recommendation_count` integer NOT NULL CHECK (`recommendation_count` BETWEEN 0 AND 100000),`export_object_count` integer NOT NULL CHECK (`export_object_count` BETWEEN 1 AND 2000),`created_at` integer NOT NULL CHECK (`created_at` BETWEEN 0 AND 9007199254740991),FOREIGN KEY (`org_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE,FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON DELETE CASCADE,FOREIGN KEY (`connection_id`) REFERENCES `aws_connections`(`id`) ON DELETE CASCADE,UNIQUE (`org_id`,`customer_id`,`connection_id`,`materialization_id`),CHECK (length(`generation_id`)=68 AND substr(`generation_id`,1,4)='coh_' AND substr(`generation_id`,5) NOT GLOB '*[^a-f0-9]*'),CHECK (length(`materialization_id`)=68 AND substr(`materialization_id`,1,4)='com_'),CHECK (length(`management_account_id`)=12 AND `management_account_id` NOT GLOB '*[^0-9]*'),CHECK (length(`content_sha256`)=64 AND `content_sha256` NOT GLOB '*[^a-f0-9]*'),CHECK (length(`snapshot_json`) BETWEEN 2 AND 268435456),CHECK (length(`generated_at`)=24));
--> statement-breakpoint
CREATE INDEX `finops_compute_optimizer_export_history_idx` ON `finops_compute_optimizer_export_snapshots` (`org_id`,`customer_id`,`connection_id`,`generated_at` DESC,`generation_id` DESC);
--> statement-breakpoint
CREATE TABLE `finops_compute_optimizer_export_heads` (`org_id` text NOT NULL,`customer_id` text NOT NULL,`connection_id` text NOT NULL,`active_generation_id` text NOT NULL UNIQUE,`advanced_at` integer NOT NULL CHECK (`advanced_at` BETWEEN 0 AND 9007199254740991),PRIMARY KEY (`org_id`,`customer_id`,`connection_id`),FOREIGN KEY (`active_generation_id`) REFERENCES `finops_compute_optimizer_export_snapshots`(`generation_id`));
--> statement-breakpoint
CREATE TRIGGER `finops_compute_optimizer_export_snapshots_update_guard` BEFORE UPDATE ON `finops_compute_optimizer_export_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_COMPUTE_OPTIMIZER_EXPORT_SNAPSHOT_IMMUTABLE'); END;
--> statement-breakpoint
CREATE TRIGGER `finops_compute_optimizer_export_snapshots_delete_guard` BEFORE DELETE ON `finops_compute_optimizer_export_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_COMPUTE_OPTIMIZER_EXPORT_SNAPSHOT_IMMUTABLE'); END;
--> statement-breakpoint
CREATE TRIGGER `finops_compute_optimizer_export_heads_insert_guard` BEFORE INSERT ON `finops_compute_optimizer_export_heads` WHEN NOT EXISTS (SELECT 1 FROM `finops_compute_optimizer_export_snapshots` candidate WHERE candidate.`generation_id`=NEW.`active_generation_id` AND candidate.`org_id`=NEW.`org_id` AND candidate.`customer_id`=NEW.`customer_id` AND candidate.`connection_id`=NEW.`connection_id` AND candidate.`complete`=1) BEGIN SELECT RAISE(ABORT,'FINOPS_COMPUTE_OPTIMIZER_EXPORT_HEAD_REJECTED'); END;
--> statement-breakpoint
CREATE TRIGGER `finops_compute_optimizer_export_heads_update_guard` BEFORE UPDATE ON `finops_compute_optimizer_export_heads` WHEN NEW.`org_id`<>OLD.`org_id` OR NEW.`customer_id`<>OLD.`customer_id` OR NEW.`connection_id`<>OLD.`connection_id` OR NOT EXISTS (SELECT 1 FROM `finops_compute_optimizer_export_snapshots` candidate JOIN `finops_compute_optimizer_export_snapshots` active ON active.`generation_id`=OLD.`active_generation_id` WHERE candidate.`generation_id`=NEW.`active_generation_id` AND candidate.`org_id`=OLD.`org_id` AND candidate.`customer_id`=OLD.`customer_id` AND candidate.`connection_id`=OLD.`connection_id` AND candidate.`complete`=1 AND (candidate.`generated_at`>active.`generated_at` OR (candidate.`generated_at`=active.`generated_at` AND candidate.`generation_id`>active.`generation_id`))) BEGIN SELECT RAISE(ABORT,'FINOPS_COMPUTE_OPTIMIZER_EXPORT_HEAD_REJECTED'); END;
--> statement-breakpoint
CREATE TRIGGER `finops_compute_optimizer_export_heads_delete_guard` BEFORE DELETE ON `finops_compute_optimizer_export_heads` BEGIN SELECT RAISE(ABORT,'FINOPS_COMPUTE_OPTIMIZER_EXPORT_HEAD_IMMUTABLE'); END;
