CREATE TABLE `finops_extended_support_snapshots`(`generation_id` text PRIMARY KEY NOT NULL,`org_id` text NOT NULL,`customer_id` text NOT NULL,`connection_id` text NOT NULL,`management_account_id` text NOT NULL,`partition` text NOT NULL CHECK(`partition` IN('aws','aws-cn','aws-us-gov')),`collection_id` text NOT NULL,`source_state` text NOT NULL CHECK(`source_state` IN('READY','PARTIAL','CONFIGURATION_REQUIRED')),`content_sha256` text NOT NULL,`snapshot_json` text NOT NULL,`collected_at` text NOT NULL,`resource_count` integer NOT NULL CHECK(`resource_count` BETWEEN 0 AND 5000),`ready_service_count` integer NOT NULL CHECK(`ready_service_count` BETWEEN 0 AND 5),`partial_service_count` integer NOT NULL CHECK(`partial_service_count` BETWEEN 0 AND 5),`configuration_required_service_count` integer NOT NULL CHECK(`configuration_required_service_count` BETWEEN 0 AND 5),`created_at` integer NOT NULL CHECK(`created_at` BETWEEN 0 AND 9007199254740991),FOREIGN KEY(`org_id`)REFERENCES`organizations`(`id`)ON DELETE CASCADE,FOREIGN KEY(`customer_id`)REFERENCES`customers`(`id`)ON DELETE CASCADE,FOREIGN KEY(`connection_id`)REFERENCES`aws_connections`(`id`)ON DELETE CASCADE,UNIQUE(`org_id`,`customer_id`,`connection_id`,`generation_id`),UNIQUE(`org_id`,`customer_id`,`connection_id`,`collection_id`),CHECK(length(`generation_id`)=69 AND substr(`generation_id`,1,5)='espg_' AND substr(`generation_id`,6)NOT GLOB'*[^a-f0-9]*'),CHECK(length(`collection_id`)=68 AND substr(`collection_id`,1,4)='esp_' AND substr(`collection_id`,5)NOT GLOB'*[^a-f0-9]*'),CHECK(length(`content_sha256`)=64 AND `content_sha256` NOT GLOB'*[^a-f0-9]*'),CHECK(length(`management_account_id`)=12 AND `management_account_id` NOT GLOB'*[^0-9]*'),CHECK(length(`snapshot_json`)BETWEEN 2 AND 8388608),CHECK(length(`collected_at`)=24),CHECK(`ready_service_count`+`partial_service_count`+`configuration_required_service_count`=5));
--> statement-breakpoint
CREATE INDEX `finops_extended_support_history_idx` ON `finops_extended_support_snapshots`(`org_id`,`customer_id`,`connection_id`,`collected_at` DESC,`generation_id` DESC);
--> statement-breakpoint
CREATE TABLE `finops_extended_support_heads`(`org_id` text NOT NULL,`customer_id` text NOT NULL,`connection_id` text NOT NULL,`active_generation_id` text NOT NULL UNIQUE,`advanced_at` integer NOT NULL CHECK(`advanced_at` BETWEEN 0 AND 9007199254740991),PRIMARY KEY(`org_id`,`customer_id`,`connection_id`),FOREIGN KEY(`active_generation_id`)REFERENCES`finops_extended_support_snapshots`(`generation_id`));
--> statement-breakpoint
CREATE TRIGGER `finops_extended_support_snapshot_update_guard` BEFORE UPDATE ON `finops_extended_support_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_EXTENDED_SUPPORT_SNAPSHOT_IMMUTABLE');END;
--> statement-breakpoint
CREATE TRIGGER `finops_extended_support_snapshot_delete_guard` BEFORE DELETE ON `finops_extended_support_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_EXTENDED_SUPPORT_SNAPSHOT_IMMUTABLE');END;
--> statement-breakpoint
CREATE TRIGGER `finops_extended_support_head_insert_guard` BEFORE INSERT ON `finops_extended_support_heads` WHEN NOT EXISTS(SELECT 1 FROM `finops_extended_support_snapshots` c WHERE c.`generation_id`=NEW.`active_generation_id` AND c.`org_id`=NEW.`org_id` AND c.`customer_id`=NEW.`customer_id` AND c.`connection_id`=NEW.`connection_id` AND c.`source_state`='READY')BEGIN SELECT RAISE(ABORT,'FINOPS_EXTENDED_SUPPORT_HEAD_REJECTED');END;
--> statement-breakpoint
CREATE TRIGGER `finops_extended_support_head_update_guard` BEFORE UPDATE ON `finops_extended_support_heads` WHEN NEW.`org_id`<>OLD.`org_id` OR NEW.`customer_id`<>OLD.`customer_id` OR NEW.`connection_id`<>OLD.`connection_id` OR NOT EXISTS(SELECT 1 FROM `finops_extended_support_snapshots` candidate JOIN `finops_extended_support_snapshots` active ON active.`generation_id`=OLD.`active_generation_id` WHERE candidate.`generation_id`=NEW.`active_generation_id` AND candidate.`org_id`=OLD.`org_id` AND candidate.`customer_id`=OLD.`customer_id` AND candidate.`connection_id`=OLD.`connection_id` AND candidate.`source_state`='READY' AND candidate.`collected_at`>active.`collected_at`)BEGIN SELECT RAISE(ABORT,'FINOPS_EXTENDED_SUPPORT_HEAD_REJECTED');END;
--> statement-breakpoint
CREATE TRIGGER `finops_extended_support_head_delete_guard` BEFORE DELETE ON `finops_extended_support_heads` BEGIN SELECT RAISE(ABORT,'FINOPS_EXTENDED_SUPPORT_HEAD_IMMUTABLE');END;
