CREATE TABLE `finops_aws_health_snapshots` (`generation_id` text PRIMARY KEY NOT NULL,`org_id` text NOT NULL,`customer_id` text NOT NULL,`connection_id` text NOT NULL,`account_id` text NOT NULL,`partition` text NOT NULL,`endpoint_region` text NOT NULL,`capture_id` text NOT NULL,`configuration_state` text NOT NULL CHECK (`configuration_state` IN ('ready','pending','unavailable','unverified')),`collection_state` text NOT NULL CHECK (`collection_state` IN ('complete','partial','unavailable')),`complete` integer NOT NULL CHECK (`complete` IN (0,1)),`support_plan` text NOT NULL,`organization_view_status` text NOT NULL,`content_sha256` text NOT NULL,`snapshot_json` text NOT NULL,`observed_at` text NOT NULL,`event_count` integer NOT NULL CHECK (`event_count` BETWEEN 0 AND 10000),`affected_account_count` integer NOT NULL CHECK (`affected_account_count` BETWEEN 0 AND 100000),`affected_entity_count` integer NOT NULL CHECK (`affected_entity_count` BETWEEN 0 AND 200000),`created_at` integer NOT NULL CHECK (`created_at` BETWEEN 0 AND 9007199254740991),FOREIGN KEY (`org_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE,FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON DELETE CASCADE,FOREIGN KEY (`connection_id`) REFERENCES `aws_connections`(`id`) ON DELETE CASCADE,UNIQUE(`org_id`,`customer_id`,`connection_id`,`capture_id`),CHECK(length(`generation_id`)=68 AND substr(`generation_id`,1,4)='hhg_' AND substr(`generation_id`,5) NOT GLOB '*[^a-f0-9]*'),CHECK(length(`capture_id`)=71 AND substr(`capture_id`,1,7)='health_'),CHECK(length(`account_id`)=12 AND `account_id` NOT GLOB '*[^0-9]*'),CHECK(length(`content_sha256`)=64 AND `content_sha256` NOT GLOB '*[^a-f0-9]*'),CHECK(length(`snapshot_json`) BETWEEN 2 AND 67108864),CHECK(length(`observed_at`)=24),CHECK(`complete`=0 OR (`configuration_state`='ready' AND `collection_state`='complete')));
--> statement-breakpoint
CREATE INDEX `finops_aws_health_history_idx` ON `finops_aws_health_snapshots`(`org_id`,`customer_id`,`connection_id`,`observed_at` DESC,`generation_id` DESC);
--> statement-breakpoint
CREATE TABLE `finops_aws_health_heads`(`org_id` text NOT NULL,`customer_id` text NOT NULL,`connection_id` text NOT NULL,`active_generation_id` text NOT NULL UNIQUE,`advanced_at` integer NOT NULL CHECK (`advanced_at` BETWEEN 0 AND 9007199254740991),PRIMARY KEY(`org_id`,`customer_id`,`connection_id`),FOREIGN KEY(`active_generation_id`) REFERENCES `finops_aws_health_snapshots`(`generation_id`));
--> statement-breakpoint
CREATE TRIGGER `finops_aws_health_snapshots_update_guard` BEFORE UPDATE ON `finops_aws_health_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_AWS_HEALTH_SNAPSHOT_IMMUTABLE'); END;
--> statement-breakpoint
CREATE TRIGGER `finops_aws_health_snapshots_delete_guard` BEFORE DELETE ON `finops_aws_health_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_AWS_HEALTH_SNAPSHOT_IMMUTABLE'); END;
--> statement-breakpoint
CREATE TRIGGER `finops_aws_health_heads_insert_guard` BEFORE INSERT ON `finops_aws_health_heads` WHEN NOT EXISTS(SELECT 1 FROM `finops_aws_health_snapshots` candidate WHERE candidate.`generation_id`=NEW.`active_generation_id` AND candidate.`org_id`=NEW.`org_id` AND candidate.`customer_id`=NEW.`customer_id` AND candidate.`connection_id`=NEW.`connection_id` AND candidate.`complete`=1)BEGIN SELECT RAISE(ABORT,'FINOPS_AWS_HEALTH_HEAD_REJECTED');END;
--> statement-breakpoint
CREATE TRIGGER `finops_aws_health_heads_update_guard` BEFORE UPDATE ON `finops_aws_health_heads` WHEN NEW.`org_id`<>OLD.`org_id` OR NEW.`customer_id`<>OLD.`customer_id` OR NEW.`connection_id`<>OLD.`connection_id` OR NOT EXISTS(SELECT 1 FROM `finops_aws_health_snapshots` candidate JOIN `finops_aws_health_snapshots` active ON active.`generation_id`=OLD.`active_generation_id` WHERE candidate.`generation_id`=NEW.`active_generation_id` AND candidate.`org_id`=OLD.`org_id` AND candidate.`customer_id`=OLD.`customer_id` AND candidate.`connection_id`=OLD.`connection_id` AND candidate.`complete`=1 AND(candidate.`observed_at`>active.`observed_at` OR(candidate.`observed_at`=active.`observed_at` AND candidate.`generation_id`>active.`generation_id`)))BEGIN SELECT RAISE(ABORT,'FINOPS_AWS_HEALTH_HEAD_REJECTED');END;
--> statement-breakpoint
CREATE TRIGGER `finops_aws_health_heads_delete_guard` BEFORE DELETE ON `finops_aws_health_heads` BEGIN SELECT RAISE(ABORT,'FINOPS_AWS_HEALTH_HEAD_IMMUTABLE'); END;
