CREATE TABLE `finops_azure_cid_sources`(`source_id` text PRIMARY KEY NOT NULL,`org_id` text NOT NULL,`customer_id` text NOT NULL,`azure_tenant_id` text NOT NULL,`billing_scope_kind` text NOT NULL CHECK(`billing_scope_kind` IN('BILLING_ACCOUNT','BILLING_PROFILE','MANAGEMENT_GROUP','SUBSCRIPTION')),`billing_scope_hash` text NOT NULL,`status` text NOT NULL CHECK(`status` IN('active','configuration_required')),`activation_reason` text NOT NULL CHECK(`activation_reason` IN('READY','AZURE_CREDENTIAL_NOT_CONFIGURED','AZURE_EXPORT_NOT_CONFIGURED','AZURE_STORAGE_ACCESS_NOT_CONFIGURED','AZURE_EXPORT_DELIVERY_NOT_OBSERVED','AZURE_DATASET_SCHEMA_UNSUPPORTED')),`created_at` integer NOT NULL CHECK(`created_at` BETWEEN 0 AND 9007199254740991),FOREIGN KEY(`org_id`)REFERENCES`organizations`(`id`)ON DELETE CASCADE,FOREIGN KEY(`customer_id`)REFERENCES`customers`(`id`)ON DELETE CASCADE,UNIQUE(`org_id`,`customer_id`,`source_id`),CHECK(length(`source_id`)=38 AND substr(`source_id`,1,6)='azsrc_' AND substr(`source_id`,7)NOT GLOB'*[^a-f0-9]*'),CHECK(length(`azure_tenant_id`)=36),CHECK(length(`billing_scope_hash`)=64 AND `billing_scope_hash` NOT GLOB'*[^a-f0-9]*'),CHECK((`status`='active')=(`activation_reason`='READY')));
--> statement-breakpoint
CREATE TABLE `finops_azure_cid_snapshots`(`generation_id` text PRIMARY KEY NOT NULL,`source_generation_id` text NOT NULL,`source_id` text NOT NULL,`org_id` text NOT NULL,`customer_id` text NOT NULL,`source_state` text NOT NULL CHECK(`source_state` IN('READY','EMPTY','PARTIAL','STALE')),`dataset_kind` text NOT NULL CHECK(`dataset_kind` IN('AZURE_STANDARD_ACTUAL_COST','FOCUS_1_0')),`content_sha256` text NOT NULL,`snapshot_json` text NOT NULL,`completed_at` text NOT NULL,`data_through_at` text NOT NULL,`row_count` integer NOT NULL CHECK(`row_count` BETWEEN 0 AND 500000),`currency_count` integer NOT NULL CHECK(`currency_count` BETWEEN 0 AND 128),`created_at` integer NOT NULL CHECK(`created_at` BETWEEN 0 AND 9007199254740991),FOREIGN KEY(`source_id`)REFERENCES`finops_azure_cid_sources`(`source_id`)ON DELETE CASCADE,FOREIGN KEY(`org_id`)REFERENCES`organizations`(`id`)ON DELETE CASCADE,FOREIGN KEY(`customer_id`)REFERENCES`customers`(`id`)ON DELETE CASCADE,UNIQUE(`org_id`,`customer_id`,`source_id`,`generation_id`),UNIQUE(`org_id`,`customer_id`,`source_id`,`source_generation_id`),CHECK(length(`generation_id`)=69 AND substr(`generation_id`,1,5)='azcg_' AND substr(`generation_id`,6)NOT GLOB'*[^a-f0-9]*'),CHECK(length(`source_generation_id`)=70 AND substr(`source_generation_id`,1,6)='azcid_' AND substr(`source_generation_id`,7)NOT GLOB'*[^a-f0-9]*'),CHECK(length(`content_sha256`)=64 AND `content_sha256` NOT GLOB'*[^a-f0-9]*'),CHECK(length(`snapshot_json`)BETWEEN 2 AND 83886080),CHECK(length(`completed_at`)=24 AND length(`data_through_at`)=24 AND `data_through_at`<=`completed_at`));
--> statement-breakpoint
CREATE INDEX `finops_azure_cid_history_idx` ON `finops_azure_cid_snapshots`(`org_id`,`customer_id`,`source_id`,`completed_at` DESC,`generation_id` DESC);
--> statement-breakpoint
CREATE TABLE `finops_azure_cid_heads`(`org_id` text NOT NULL,`customer_id` text NOT NULL,`source_id` text NOT NULL,`active_generation_id` text NOT NULL UNIQUE,`advanced_at` integer NOT NULL CHECK(`advanced_at` BETWEEN 0 AND 9007199254740991),PRIMARY KEY(`org_id`,`customer_id`,`source_id`),FOREIGN KEY(`active_generation_id`)REFERENCES`finops_azure_cid_snapshots`(`generation_id`));
--> statement-breakpoint
CREATE TRIGGER `finops_azure_cid_snapshot_update_guard` BEFORE UPDATE ON `finops_azure_cid_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_AZURE_CID_SNAPSHOT_IMMUTABLE');END;
--> statement-breakpoint
CREATE TRIGGER `finops_azure_cid_snapshot_delete_guard` BEFORE DELETE ON `finops_azure_cid_snapshots` BEGIN SELECT RAISE(ABORT,'FINOPS_AZURE_CID_SNAPSHOT_IMMUTABLE');END;
--> statement-breakpoint
CREATE TRIGGER `finops_azure_cid_head_insert_guard` BEFORE INSERT ON `finops_azure_cid_heads` WHEN NOT EXISTS(SELECT 1 FROM `finops_azure_cid_snapshots` c WHERE c.`generation_id`=NEW.`active_generation_id` AND c.`org_id`=NEW.`org_id` AND c.`customer_id`=NEW.`customer_id` AND c.`source_id`=NEW.`source_id` AND c.`source_state` IN('READY','EMPTY'))BEGIN SELECT RAISE(ABORT,'FINOPS_AZURE_CID_HEAD_REJECTED');END;
--> statement-breakpoint
CREATE TRIGGER `finops_azure_cid_head_update_guard` BEFORE UPDATE ON `finops_azure_cid_heads` WHEN NEW.`org_id`<>OLD.`org_id` OR NEW.`customer_id`<>OLD.`customer_id` OR NEW.`source_id`<>OLD.`source_id` OR NOT EXISTS(SELECT 1 FROM `finops_azure_cid_snapshots` candidate JOIN `finops_azure_cid_snapshots` active ON active.`generation_id`=OLD.`active_generation_id` WHERE candidate.`generation_id`=NEW.`active_generation_id` AND candidate.`org_id`=OLD.`org_id` AND candidate.`customer_id`=OLD.`customer_id` AND candidate.`source_id`=OLD.`source_id` AND candidate.`source_state` IN('READY','EMPTY') AND candidate.`completed_at`>active.`completed_at`)BEGIN SELECT RAISE(ABORT,'FINOPS_AZURE_CID_HEAD_REJECTED');END;
--> statement-breakpoint
CREATE TRIGGER `finops_azure_cid_head_delete_guard` BEFORE DELETE ON `finops_azure_cid_heads` BEGIN SELECT RAISE(ABORT,'FINOPS_AZURE_CID_HEAD_IMMUTABLE');END;
