import assert from "node:assert/strict";
import test from "node:test";
import { AWS_NEWS_FEED_SOURCES } from "../lib/finops-aws-news-feeds.ts";
import { AwsNewsFeedsXmlGateway } from "../lib/finops-aws-news-feeds-xml-gateway.ts";
import { AWS_NEWS_FEEDS_DURABLE_HANDLER_SCHEMA, AwsNewsFeedsDurableHandlerError, handleAwsNewsFeedsDurableJob } from "../lib/finops-aws-news-feeds-durable-handler.ts";
import { AWS_NEWS_FEEDS_JOB_KIND, awsNewsFeedsJobIdempotencyKey } from "../lib/finops-aws-news-feeds-job.ts";

const rss=AWS_NEWS_FEED_SOURCES[0],atom=AWS_NEWS_FEED_SOURCES[4];
function response(body,headers={"content-type":"application/rss+xml"},status=200){return new Response(body,{status,headers})}
function rssXml(items=1){return `<?xml version="1.0"?><rss version="2.0"><channel><title>AWS</title>${Array.from({length:items},(_,index)=>`<item><guid>item-${index}</guid><link>https://aws.amazon.com/about-aws/whats-new/2026/07/item-${index}/</link><title>Launch &amp; update ${index}</title><description><![CDATA[<p>Plain <b>summary</b></p>]]></description><pubDate>Thu, 31 Jul 2026 10:00:00 GMT</pubDate><category>Compute</category></item>`).join("")}</channel></rss>`}

test("XML gateway parses pinned RSS/Atom feeds, sanitizes text, and bounds items",async()=>{let clocks=[1000,1050];const gateway=new AwsNewsFeedsXmlGateway({fetcher:async()=>response(rssXml(501)),now:()=>clocks.shift()});const capture=await gateway.collect(rss,new AbortController().signal);assert.equal(capture.status,"SUCCEEDED");assert.equal(capture.items.length,500);assert.equal(capture.truncated,true);assert.equal(capture.items[0].title,"Launch & update 0");assert.equal(capture.items[0].summary,"Plain summary");assert.equal(capture.responseBytes,new TextEncoder().encode(rssXml(501)).byteLength);
  clocks=[2000,2040];const atomXml=`<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom" xmlns:yt="http://www.youtube.com/xml/schemas/2015"><entry><id>yt:video:AbCdEf123_-</id><yt:videoId>AbCdEf123_-</yt:videoId><title>AWS video</title><published>2026-07-31T10:00:00Z</published><updated>2026-07-31T11:00:00Z</updated><link rel="alternate" href="https://www.youtube.com/watch?v=AbCdEf123_-"/><category term="Cloud"/></entry></feed>`;const atomGateway=new AwsNewsFeedsXmlGateway({fetcher:async()=>response(atomXml,{"content-type":"application/atom+xml"}),now:()=>clocks.shift()});const atomCapture=await atomGateway.collect(atom,new AbortController().signal);assert.equal(atomCapture.status,"SUCCEEDED");assert.equal(atomCapture.items[0].canonicalUrl,"https://www.youtube.com/watch?v=AbCdEf123_-");assert.deepEqual(atomCapture.items[0].categories,["Cloud"])});

test("XML gateway blocks DTD, entities, XInclude, unsafe redirects, MIME confusion, and byte overflow",async()=>{for(const xml of [`<!DOCTYPE rss [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><rss><channel><item><title>&xxe;</title></item></channel></rss>`,`<rss xmlns:xi="http://www.w3.org/2001/XInclude"><xi:include href="https://evil.example"/></rss>`,`<rss><channel><item><title>&unknown;</title></item></channel></rss>`,`<rss><channel><item><title>Unescaped & value</title></item></channel></rss>`]){let clocks=[1000,1010];const gateway=new AwsNewsFeedsXmlGateway({fetcher:async()=>response(xml),now:()=>clocks.shift()});const captured=await gateway.collect(rss,new AbortController().signal);assert.equal(captured.status,"FAILED");assert.equal(captured.failureCode,"INVALID_DOCUMENT");assert.equal(JSON.stringify(captured).includes("passwd"),false)}
  let clocks=[1000,1010];const redirect=new AwsNewsFeedsXmlGateway({fetcher:async()=>response("",{location:"https://169.254.169.254/latest/meta-data"},302),now:()=>clocks.shift()});const redirected=await redirect.collect(rss,new AbortController().signal);assert.equal(redirected.failureCode,"REDIRECT_REJECTED");assert.deepEqual(redirected.redirectChain,[rss.feedUrl]);
  clocks=[1000,1010];const mime=new AwsNewsFeedsXmlGateway({fetcher:async()=>response(rssXml(),{"content-type":"text/html"}),now:()=>clocks.shift()});assert.equal((await mime.collect(rss,new AbortController().signal)).failureCode,"INVALID_CONTENT_TYPE");
  clocks=[1000,1010];const large=new AwsNewsFeedsXmlGateway({fetcher:async()=>response("x",{"content-type":"application/xml","content-length":String(2*1024*1024+1)}),now:()=>clocks.shift()});assert.equal((await large.collect(rss,new AbortController().signal)).failureCode,"BYTE_LIMIT_REACHED")});

test("XML gateway rejects modified sources, propagates cancellation, and sanitizes transport failures",async()=>{let called=false;const gateway=new AwsNewsFeedsXmlGateway({fetcher:async()=>{called=true;throw new Error("secret upstream details")},now:()=>1000});await assert.rejects(gateway.collect({...rss,feedUrl:"https://evil.example/feed"},new AbortController().signal));assert.equal(called,false);const capture=await gateway.collect(rss,new AbortController().signal);assert.equal(capture.status,"FAILED");assert.equal(capture.failureCode,"UNKNOWN");assert.equal(JSON.stringify(capture).includes("secret"),false);const controller=new AbortController();controller.abort();const cancelled=new AwsNewsFeedsXmlGateway({fetcher:async(_url,init)=>{assert.equal(init.signal.aborted,true);throw new DOMException("provider details","AbortError")},now:()=>1000});assert.equal((await cancelled.collect(rss,controller.signal)).failureCode,"NETWORK_TIMEOUT")});

const scope={organizationId:"org_alpha",customerId:"customer_alpha",connectionId:`conn_${"a".repeat(32)}`},window="2026-07-31T12:00:00.000Z";
function envelope(){return{schemaVersion:AWS_NEWS_FEEDS_DURABLE_HANDLER_SCHEMA,kind:AWS_NEWS_FEEDS_JOB_KIND,idempotencyKey:awsNewsFeedsJobIdempotencyKey(scope,window),job:{id:"job_1",orgId:scope.organizationId,customerId:scope.customerId,connectionId:scope.connectionId,payload:{scheduledWindow:window}}}}
function collectionDependencies(overrides={}){const times=[Date.parse(window),Date.parse(window)+1000];return{gateway:{collect:async source=>({sourceId:source.id,status:"FAILED",requestUrl:source.feedUrl,finalUrl:source.feedUrl,redirectChain:[source.feedUrl],durationMs:10,fetchedAt:window,contentType:null,responseBytes:0,parser:null,truncated:false,failureCode:"PROVIDER_UNAVAILABLE",items:[]})},loadTenantBoundary:async()=>({scope:{orgId:scope.organizationId,customerId:scope.customerId,connectionId:scope.connectionId},binding:"SERVER_RESOLVED_CONNECTION",catalogId:`catalog_${"b".repeat(64)}`,catalogCapturedAt:window,services:[]}),recordCapture:async()=>({snapshot:{generationId:`newsg_${"c".repeat(64)}`,snapshot:{generationId:"unused",state:"FAILED"}},becameActive:false}),now:()=>times.shift(),...overrides}}

test("durable handler executes once, stores a hashed receipt, and replays completed results",async()=>{const completed=[],failed=[],dependencies=collectionDependencies({replayStore:{claim:async()=>({state:"ACQUIRED",leaseToken:"lease_1"}),complete:async value=>completed.push(value),fail:async value=>failed.push(value)}}),executed=await handleAwsNewsFeedsDurableJob(envelope(),dependencies);assert.equal(executed.disposition,"EXECUTED");assert.match(completed[0].resultSha256,/^[a-f0-9]{64}$/u);assert.equal(failed.length,0);let collected=false;const replay=await handleAwsNewsFeedsDurableJob(envelope(),collectionDependencies({gateway:{collect:async()=>{collected=true;throw new Error("must not run")}},replayStore:{claim:async()=>({state:"COMPLETED",result:executed.result,resultSha256:completed[0].resultSha256}),complete:async()=>{},fail:async()=>{}}}));assert.equal(replay.disposition,"REPLAYED");assert.equal(collected,false)});

test("durable handler rejects key/payload substitution, exposes in-progress leases, and sanitizes failures",async()=>{let claimed=false;await assert.rejects(handleAwsNewsFeedsDurableJob({...envelope(),idempotencyKey:"attacker"},collectionDependencies({replayStore:{claim:async()=>{claimed=true;return{state:"IN_PROGRESS"}},complete:async()=>{},fail:async()=>{}}})),error=>error instanceof AwsNewsFeedsDurableHandlerError&&error.code==="INVALID_ENVELOPE");assert.equal(claimed,false);const progress=await handleAwsNewsFeedsDurableJob(envelope(),collectionDependencies({replayStore:{claim:async()=>({state:"IN_PROGRESS"}),complete:async()=>{},fail:async()=>{}}}));assert.deepEqual(progress,{disposition:"IN_PROGRESS",result:null});const failures=[];await assert.rejects(handleAwsNewsFeedsDurableJob(envelope(),collectionDependencies({gateway:{collect:async()=>{throw new Error("credential=secret")}},replayStore:{claim:async()=>({state:"ACQUIRED",leaseToken:"lease"}),complete:async()=>{},fail:async value=>failures.push(value)}})),error=>error instanceof AwsNewsFeedsDurableHandlerError&&error.code==="COLLECTION_FAILED"&&!error.message.includes("secret"));assert.equal(failures[0].failureCode,"AWS_NEWS_FEEDS_COLLECTION_FAILED")});

test("durable handler rejects corrupt receipts and masks replay-store failures",async()=>{await assert.rejects(handleAwsNewsFeedsDurableJob(envelope(),collectionDependencies({replayStore:{claim:async()=>({state:"COMPLETED",result:{generationId:"bad",captureId:"bad",state:"READY",becameActive:true},resultSha256:"0".repeat(64)}),complete:async()=>{},fail:async()=>{}}})),error=>error instanceof AwsNewsFeedsDurableHandlerError&&error.code==="COLLECTION_FAILED");const validResult={generationId:`newsg_${"c".repeat(64)}`,captureId:`news_${"d".repeat(64)}`,state:"READY",becameActive:true};await assert.rejects(handleAwsNewsFeedsDurableJob(envelope(),collectionDependencies({replayStore:{claim:async()=>({state:"COMPLETED",result:validResult,resultSha256:"0".repeat(64)}),complete:async()=>{},fail:async()=>{}}})),error=>error instanceof AwsNewsFeedsDurableHandlerError&&error.code==="COLLECTION_FAILED");await assert.rejects(handleAwsNewsFeedsDurableJob(envelope(),collectionDependencies({replayStore:{claim:async()=>{throw new Error("database password leaked")},complete:async()=>{},fail:async()=>{}}})),error=>error instanceof AwsNewsFeedsDurableHandlerError&&error.code==="COLLECTION_FAILED"&&!error.message.includes("password"));await assert.rejects(handleAwsNewsFeedsDurableJob(envelope(),collectionDependencies({replayStore:{claim:async()=>({state:"ACQUIRED",leaseToken:"lease"}),complete:async()=>{throw new Error("receipt store secret")},fail:async()=>{throw new Error("secondary secret")}}})),error=>error instanceof AwsNewsFeedsDurableHandlerError&&error.code==="COLLECTION_FAILED"&&!error.message.includes("secret"))});
