import assert from "node:assert/strict";
import test from "node:test";
import { buildProviderNeutralFocusReport, FinopsFocusNeutralError } from "../lib/finops-focus-neutral.ts";

const scope={orgId:"org_focus",customerId:"customer_focus"};
function source(sourceId,provider,focusVersion,hex){return{...scope,sourceId,provider,focusVersion,datasetName:`${provider}_FOCUS_${focusVersion}`,generationId:`generation_${hex}`,contentSha256:hex.repeat(64),collectedAt:"2026-08-01T00:00:00.000Z",dataThroughAt:"2026-07-31T23:59:59.000Z",normalizedSchema:"sutra.focus-neutral-line.v1"}}
function row(sourceId,lineId,currency="USD",overrides={}){return{sourceId,lineId,billingPeriod:"2026-07",billingCurrency:currency,billedCostMicros:"7000000",effectiveCostMicros:"6000000",listCostMicros:"10000000",contractedCostMicros:"8000000",providerName:"Provider",serviceName:"Compute",chargeCategory:"Usage",chargeClass:null,chargeClassEvidence:"PRESENT",tags:[{key:"team",value:"platform"},{key:sourceId.startsWith("azure")?"microsoft:meter":"aws:createdBy",value:"provider"}],...overrides}}
const taxonomy={policyId:"tenant-taxonomy-v1",governedKeys:[{key:"team",label:"Team"}],providerTagPrefixes:{AWS:["aws:"],AZURE:["microsoft:"],GCP:["goog-"]}};

test("provider-neutral FOCUS consolidates explicit versions/providers without combining currencies",()=>{const sources=[source("aws-source","AWS","1.2","a"),source("azure-source","AZURE","1.0","b")],report=buildProviderNeutralFocusReport({scope,sources,rows:[row("aws-source","aws-line"),row("azure-source","azure-line"),row("azure-source","azure-eur","EUR")],taxonomy});assert.deepEqual(report.providers,["AWS","AZURE"]);assert.deepEqual(report.versions,["1.0","1.2"]);assert.deepEqual(report.currencies.map(item=>item.currency),["EUR","USD"]);assert.equal(report.currencies[1].billedCostMicros,"14000000");assert.equal(report.sources[0].contentSha256,"a".repeat(64));assert.equal(report.invariants.includes("currencies_are_never_combined"),true)});

test("governed taxonomy preserves governed, provider-defined, and ungoverned classifications",()=>{const report=buildProviderNeutralFocusReport({scope,sources:[source("aws-source","AWS","1.2","a")],rows:[row("aws-source","line", "USD",{tags:[{key:"team",value:"platform"},{key:"aws:createdBy",value:"service"},{key:"experiment",value:"one"}]})],taxonomy}),tags=report.currencies[0].tags;assert.deepEqual(tags.map(tag=>tag.classification).sort(),["GOVERNED","PROVIDER_DEFINED","UNGOVERNED"]);assert.equal(tags.find(tag=>tag.key==="team").label,"Team")});

test("effective discount rate is exact only with valid FOCUS denominator semantics",()=>{const available=buildProviderNeutralFocusReport({scope,sources:[source("aws-source","AWS","1.2","a")],rows:[row("aws-source","line")],taxonomy});assert.deepEqual(available.currencies[0].effectiveDiscountRate,{state:"AVAILABLE",basisPoints:"4000",numeratorMicros:"4000000",denominatorMicros:"10000000",formula:"(LIST_COST-EFFECTIVE_COST)/LIST_COST",reason:"VALID_FOCUS_COST_COMPARISON"});for(const [overrides,reason] of [[{chargeClassEvidence:"NOT_PROVIDED"},"CHARGE_CLASS_SEMANTICS_NOT_PROVIDED"],[{effectiveCostMicros:null},"MISSING_EFFECTIVE_COST"],[{listCostMicros:null},"MISSING_LIST_COST"],[{listCostMicros:"0"},"NON_POSITIVE_LIST_COST"]]){const report=buildProviderNeutralFocusReport({scope,sources:[source("aws-source","AWS","1.2","a")],rows:[row("aws-source","line","USD",overrides)],taxonomy});assert.equal(report.currencies[0].effectiveDiscountRate.state,"UNAVAILABLE");assert.equal(report.currencies[0].effectiveDiscountRate.reason,reason)}});

test("neutral contract rejects cross-tenant sources, duplicate lines, and unbound sources",()=>{const valid=source("aws-source","AWS","1.2","a");for(const [sources,rows,code] of [[[ {...valid,customerId:"customer_attacker"} ],[row("aws-source","line")],"SCOPE_MISMATCH"],[[valid],[row("aws-source","same"),row("aws-source","same")],"DUPLICATE_LINE"],[[valid],[row("unknown-source","line")],"SCOPE_MISMATCH"]])assert.throws(()=>buildProviderNeutralFocusReport({scope,sources,rows,taxonomy}),(error)=>error instanceof FinopsFocusNeutralError&&error.code===code)});
