import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { register } from "node:module";
import test from "node:test";
import { Miniflare } from "miniflare";
register(new URL("./cloudflare-loader.mjs", import.meta.url));
const runtime=await import("../db/runtime-migrations.ts");
const {AwsConfigComplianceRuntimeRepository}=await import("../db/finops-aws-config-compliance-runtime-repository.ts");
const {AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS}=await import("../lib/finops-aws-config-compliance-production-composition.ts");
const sdkReader=await readFile(new URL("../services/aws-collector/src/aws-config-compliance-provider-client.ts",import.meta.url),"utf8");
const ORG="org_config_runtime",CUSTOMER="customer_config_runtime",CONNECTION=`conn_${"a".repeat(32)}`;
const SCOPE={organizationId:ORG,customerId:CUSTOMER,connectionId:CONNECTION};
const WINDOW="2026-08-02T00:00:00.000Z",JOB=`job_${"b".repeat(32)}`,NOW=Date.parse("2026-08-02T12:00:00.000Z");
async function fixture(){const mf=new Miniflare({modules:true,script:"export default{fetch(){return new Response('ok')}}",compatibilityDate:"2026-05-22",d1Databases:{DB:`config-${crypto.randomUUID()}`},d1Persist:false});const db=await mf.getD1Database("DB");runtime.resetRuntimeSchemaCacheForTests();await runtime.ensureRuntimeSchema(db);const migration=await readFile(new URL("../drizzle/0129_finops_aws_config_compliance_runtime.sql",import.meta.url),"utf8");for(const statement of migration.split("--> statement-breakpoint").map((value)=>value.trim()).filter(Boolean))await db.prepare(statement).run();await db.batch([
  db.prepare("INSERT INTO organizations(id,slug,name,status)VALUES(?,'config-org','Config Org','active')").bind(ORG),
  db.prepare("INSERT INTO customers(id,org_id,slug,name,status)VALUES(?,?,'config-customer','Config Customer','active')").bind(CUSTOMER,ORG),
  db.prepare("INSERT INTO aws_connections(id,org_id,customer_id,source_kind,partition,aws_account_id,role_arn,external_id_ciphertext,external_id_key_version,permission_pack_version,status,enabled_regions_json)VALUES(?,?,?,'aws_trust_role','aws','111122223333','arn:aws:iam::111122223333:role/sutra/SutraCollectorRole','ct','v1','standard-2026-08.18','active','[\"us-east-1\"]')").bind(CONNECTION,ORG,CUSTOMER),
  db.prepare("INSERT INTO finops_config_compliance_runtime_configuration(org_id,customer_id,connection_id,aggregator_name,aggregator_arn,aws_organization_id,accounts_evidence_id,accounts_observed_at,active_account_ids_json,expected_regions_json,enabled,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?,1,?)").bind(ORG,CUSTOMER,CONNECTION,"organization-aggregator","arn:aws:config:us-east-1:111122223333:config-aggregator/config-aggregator-abc123","o-1234567890","organizations-ledger","2026-08-02T11:00:00.000Z",'["111122223333"]','["us-east-1"]',NOW),
]);return{mf,db}}

test("production contract pins the complete official surface and forbids evidence substitution",()=>{assert.deepEqual({sheets:AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS.pinnedSheets,visuals:AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS.pinnedVisuals,controls:AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS.pinnedControls,datasets:AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS.pinnedDatasets,views:AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS.pinnedAthenaViews},{sheets:7,visuals:124,controls:64,datasets:13,views:14});assert.equal(AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS.requiredPermissionPack,"standard-2026-08.18");assert.equal(AWS_CONFIG_COMPLIANCE_PRODUCTION_STATUS.securityHubOrCloudTrailSubstitution,false);for(const command of["DescribeConfigurationAggregatorsCommand","DescribeConfigurationAggregatorSourcesStatusCommand","DescribeAggregateComplianceByConfigRulesCommand","GetAggregateComplianceDetailsByConfigRuleCommand","DescribeAggregateComplianceByConformancePacksCommand","GetAggregateDiscoveredResourceCountsCommand","SelectAggregateResourceConfigCommand","DescribeConfigRulesCommand","DescribeConfigRuleEvaluationStatusCommand","DescribeConfigurationRecordersCommand","DescribeConfigurationRecorderStatusCommand","DescribeOrganizationCommand","ListAccountsCommand"])assert.match(sdkReader,new RegExp(command,"u"));assert.match(sdkReader,/do\{.*while\(next!==null\)/su);assert.match(sdkReader,/received===next\|\|seen\.has\(received\)/u)});

test("trusted runtime configuration expands exact account/Region targets and is pack gated",async()=>{const{mf,db}=await fixture();try{const repo=new AwsConfigComplianceRuntimeRepository(db,{now:()=>NOW,skipRuntimeSchema:true});assert.equal((await repo.listEligibleScopes()).length,1);assert.deepEqual(await repo.loadScope(SCOPE),{orgId:ORG,customerId:CUSTOMER,connectionId:CONNECTION,partition:"aws",aggregatorAccountId:"111122223333",aggregatorRegion:"us-east-1",aggregatorName:"organization-aggregator",aggregatorArn:"arn:aws:config:us-east-1:111122223333:config-aggregator/config-aggregator-abc123"});const context=await repo.loadProviderContext(SCOPE);assert.deepEqual(context.targets,[{accountId:"111122223333",region:"us-east-1",connectionId:CONNECTION}]);await db.prepare("UPDATE aws_connections SET permission_pack_version='standard-2026-08.17' WHERE id=?").bind(CONNECTION).run();await assert.rejects(repo.loadScope(SCOPE),(error)=>error.code==="SCOPE_NOT_FOUND")}finally{await mf.dispose()}});

test("durable replay excludes a second worker, records failure, and replays a sealed result",async()=>{const{mf,db}=await fixture();try{const repo=new AwsConfigComplianceRuntimeRepository(db,{now:()=>NOW,skipRuntimeSchema:true});const key=`aws-config-compliance:${ORG}:${CUSTOMER}:${CONNECTION}:${encodeURIComponent(WINDOW)}`;const first=await repo.claim({key,jobId:JOB,leaseDurationMs:1_260_000});assert.equal(first.state,"ACQUIRED");assert.equal((await repo.claim({key,jobId:`job_${"c".repeat(32)}`,leaseDurationMs:1_260_000})).state,"IN_PROGRESS");const result={snapshotId:`acc_${"d".repeat(64)}`,state:"READY",captureId:`config_${"e".repeat(64)}`};const resultSha256=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(result))).then((bytes)=>[...new Uint8Array(bytes)].map((part)=>part.toString(16).padStart(2,"0")).join(""));await repo.complete({key,jobId:JOB,leaseToken:first.leaseToken,result,resultSha256});const replay=await repo.claim({key,jobId:`job_${"f".repeat(32)}`,leaseDurationMs:1_260_000});assert.equal(replay.state,"COMPLETED");assert.deepEqual(replay.result,result);assert.equal((await repo.getRuntimeStatus(SCOPE)).state,"ready")}finally{await mf.dispose()}});
