import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { register } from "node:module";
import test from "node:test";
import { Miniflare } from "miniflare";
register(new URL("./cloudflare-loader.mjs", import.meta.url));
const runtime = await import("../db/runtime-migrations.ts");
const { CoraRuntimeAttemptRepository, CORA_RUNTIME_LEASE_MS } = await import("../db/finops-cora-runtime-attempt-repository.ts");
const SCOPE = { organizationId: "org_cora_runtime", customerId: "customer_cora_runtime", connectionId: `conn_${"a".repeat(32)}` }; const NOW = Date.parse("2026-08-02T12:00:00.000Z");
const identity = (hex = "b", window = "2026-08-02T00:00:00.000Z", attempt = 1, maxAttempts = 5) => ({ ...SCOPE, requestKey: `corarq_${hex.repeat(64)}`, jobId: `job_${hex.repeat(32)}`, scheduledWindow: window, jobAttempt: attempt, maxAttempts });
async function fixture() { const mf = new Miniflare({ modules: true, script: "export default{fetch(){return new Response('ok')}}", compatibilityDate: "2026-05-22", d1Databases: { DB: `cora-runtime-${crypto.randomUUID()}` }, d1Persist: false }); const db = await mf.getD1Database("DB"); runtime.resetRuntimeSchemaCacheForTests(); await runtime.ensureRuntimeSchema(db); const sql = await readFile(new URL("../drizzle/0124_finops_cora_runtime_attempts.sql", import.meta.url), "utf8"); for (const statement of sql.split("--> statement-breakpoint").map((item) => item.trim()).filter(Boolean)) await db.prepare(statement).run(); await db.batch([db.prepare("INSERT INTO organizations(id,slug,name,status)VALUES(?,'cora-runtime','CORA Runtime','active')").bind(SCOPE.organizationId), db.prepare("INSERT INTO customers(id,org_id,slug,name,status)VALUES(?,?,'cora-customer','CORA Customer','active')").bind(SCOPE.customerId, SCOPE.organizationId), db.prepare("INSERT INTO aws_connections(id,org_id,customer_id,source_kind,partition,aws_account_id,role_arn,external_id_ciphertext,external_id_key_version,permission_pack_version,status,enabled_regions_json)VALUES(?,?,?,'aws_trust_role','aws','111122223333','arn:aws:iam::111122223333:role/sutra/SutraCollectorRole','ct','v1','standard-2026-08.14','active','[]')").bind(SCOPE.connectionId, SCOPE.organizationId, SCOPE.customerId)]); return { mf, db }; }
async function insertGeneration(db, item, hex = "c") { const generationId = `core_${hex.repeat(64)}`; await db.prepare(`INSERT INTO finops_cora_export_object_generations(generation_id,org_id,customer_id,connection_id,management_account_id,request_key,materialization_id,capture_id,export_arn,execution_id,source_state,complete,content_sha256,materialization_json,scheduled_window,generated_at,data_through_at,manifest_sha256,object_count,row_count,accepted_row_count,rejected_row_count,created_at)VALUES(?,?,?,?,?,?,?,?,?,?,'EMPTY',1,?,'{}',?,?,?, ?,0,0,0,0,?)`).bind(generationId, SCOPE.organizationId, SCOPE.customerId, SCOPE.connectionId, "111122223333", item.requestKey, `coram_${hex.repeat(64)}`, `cora_${hex.repeat(64)}`, "arn:aws:bcm-data-exports:us-east-1:111122223333:export/sutra-cora-12345678-abcd-abcd-abcd-1234567890ab", `execution-${hex}`, hex.repeat(64), item.scheduledWindow, "2026-08-02T06:00:00.000Z", "2026-08-02T06:00:00.000Z", hex.repeat(64), NOW).run(); return generationId; }

test("ADD-01 17-minute CAS lease excludes concurrent workers and reclaims an expired orphan", async () => { const { mf, db } = await fixture(); let clock = NOW; try { const first = new CoraRuntimeAttemptRepository(db, () => clock); const second = new CoraRuntimeAttemptRepository(db, () => clock); assert.equal((await first.prepare(identity())).state, "leased"); await assert.rejects(second.prepare(identity()), (error) => error.code === "ATTEMPT_IN_PROGRESS"); clock += CORA_RUNTIME_LEASE_MS + 1; assert.equal((await second.prepare(identity("b", "2026-08-02T00:00:00.000Z", 2))).state, "leased"); } finally { await mf.dispose(); } });

test("ADD-01 seals only a same-request immutable generation and replays without provider work", async () => { const { mf, db } = await fixture(); try { const repo = new CoraRuntimeAttemptRepository(db, () => NOW); const item = identity(); await repo.prepare(item); const generationId = await insertGeneration(db, item); await repo.commitSuccess({ ...item, generationId, completedAtMs: NOW }); assert.deepEqual(await new CoraRuntimeAttemptRepository(db, () => NOW).prepare(item), { state: "replayed", generationId }); await assert.rejects(db.prepare("UPDATE finops_cora_runtime_attempts SET generation_id=NULL WHERE request_key=?").bind(item.requestKey).run(), /FINOPS_CORA_RUNTIME_TERMINAL_IMMUTABLE/u); } finally { await mf.dispose(); } });

test("ADD-01 recovers a crash after export persistence and keeps failure codes sanitized", async () => { const { mf, db } = await fixture(); try { const orphan = identity("d", "2026-08-03T00:00:00.000Z"); const repo = new CoraRuntimeAttemptRepository(db, () => NOW); await repo.prepare(orphan); const generationId = await insertGeneration(db, orphan, "d"); assert.equal(await repo.recoverPersistedGeneration(orphan), generationId); const retry = identity("e", "2026-08-04T00:00:00.000Z"); await repo.prepare(retry); await repo.recordFailure({ ...retry, code: "ADAPTER_UNAVAILABLE", terminal: false, completedAtMs: NOW }); assert.equal((await new CoraRuntimeAttemptRepository(db, () => NOW).prepare({ ...retry, jobAttempt: 2 })).state, "leased"); const terminal = identity("f", "2026-08-05T00:00:00.000Z", 5, 5); const final = new CoraRuntimeAttemptRepository(db, () => NOW); await final.prepare(terminal); await final.recordFailure({ ...terminal, code: "CAPTURE_REJECTED", terminal: true, completedAtMs: NOW }); await assert.rejects(new CoraRuntimeAttemptRepository(db, () => NOW).prepare(terminal), (error) => error.code === "TERMINAL_FAILURE" && !error.message.includes("CAPTURE_REJECTED")); } finally { await mf.dispose(); } });

test("ADD-01 runtime migrations retain SQLite/PostgreSQL parity, FK, CAS lease and PUBLIC revoke", async () => { const [sqlite, postgres] = await Promise.all([readFile(new URL("../drizzle/0124_finops_cora_runtime_attempts.sql", import.meta.url), "utf8"), readFile(new URL("../postgres/migrations/0120_finops_cora_runtime_attempts.sql", import.meta.url), "utf8")]); for (const sql of [sqlite, postgres]) { assert.match(sql, /finops_cora_runtime_attempts/u); assert.match(sql, /generation_id.*finops_cora_export_object_generations/su); assert.match(sql, /lease_expires_at.*started_at.*1020000/su); assert.match(sql, /RETRYABLE_FAILED/u); assert.match(sql, /FINOPS_CORA_RUNTIME_TERMINAL_IMMUTABLE/u); } assert.match(postgres, /REVOKE ALL ON finops_cora_runtime_attempts FROM PUBLIC/u); });
