import { createConnectionDraft } from "../../../../db/pilot-repository";
import {
  assertSameOrigin,
  decryptExternalId,
  deriveScopedAwsConnectionIdentity,
  encryptExternalId,
  generateExternalId,
  parseAwsConnectionDraftRequest,
  readBoundedJson,
} from "../../../../lib/aws-pilot-security";
import {
  AWS_CUSTOMER_ROLE_TEMPLATE_URL_ENV,
  withVerifiedPublicCustomerRoleTemplate,
} from "../../../../lib/aws-cloudformation-quick-launch";
import { withLocalOnboardingAccountLock } from "../../../../lib/local-onboarding-lock";
import {
  errorResponse,
  getCollectorHealth,
  getPilotSecrets,
  jsonResponse,
  requirePilotActor,
} from "../../../../lib/pilot-server";

export const dynamic = "force-dynamic";

function slug(value: string, customerId: string): string {
  const base = value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "").slice(0, 44) || "customer";
  return `${base}-${customerId.slice(-8)}`;
}

export async function POST(request: Request): Promise<Response> {
  try {
    const actor = await requirePilotActor(request, "customer:create");
    assertSameOrigin(request);
    const body = parseAwsConnectionDraftRequest(await readBoundedJson(request));
    const createHandoff = (publicTemplateUrl: string | null) => withLocalOnboardingAccountLock(
        body.partition,
        body.awsAccountId,
        async () => {
          const health = await getCollectorHealth(body.partition);
          if (!health.ok || !health.principalArn || health.mode !== "live") {
            throw Object.assign(new Error("The local AWS collector is not ready"), { code: "INVALID_STATE" });
          }
          const { customerId, connectionId } = await deriveScopedAwsConnectionIdentity(
            actor.orgId,
            body.awsAccountId,
            body.partition,
          );
          const generatedExternalId = generateExternalId();
          const secrets = getPilotSecrets();
          const encrypted = await encryptExternalId(
            generatedExternalId,
            secrets.connectionEncryptionKey,
            secrets.connectionKeyVersion,
            { orgId: actor.orgId, customerId, connectionId },
          );
          const handoff = await createConnectionDraft({
            orgId: actor.orgId,
            sourceKind: body.connectionMethod === "static_credentials"
              ? "aws_static_credentials"
              : "aws_trust_role",
            actorId: actor.id,
            operationId: body.operationId,
            customerId,
            connectionId,
            customerName: body.customerName,
            customerSlug: slug(body.customerName, customerId),
            accountId: body.awsAccountId,
            partition: body.partition,
            enabledRegions: body.enabledRegions,
            externalIdCiphertext: encrypted.ciphertext,
            externalIdKeyVersion: encrypted.keyVersion,
            roleProvisioningMode: body.roleProvisioningMode,
            expectedRolePath: body.rolePath,
            expectedRoleName: body.roleName,
          });
          // Always open the committed envelope: a concurrent retry may have won
          // with different generated bytes, and returning those would strand the
          // customer role handoff.
          const externalId = await decryptExternalId(
            {
              ciphertext: handoff.externalIdCiphertext,
              keyVersion: handoff.externalIdKeyVersion,
            },
            secrets.connectionEncryptionKey,
            { orgId: actor.orgId, customerId, connectionId },
          );
          return jsonResponse({
            connection: handoff.connection,
            handoff: { recovered: handoff.recovered },
            trust: {
              externalId,
              collectorPrincipal: health.principalArn,
              vendorCollectorRoleArn: health.principalArn,
              roleSessionName: "sutra-",
              sessionNamePrefix: "sutra-",
              customerTenantId: customerId,
              roleProvisioningMode: handoff.connection.roleProvisioningMode,
              rolePath: handoff.connection.expectedRolePath,
              roleName: handoff.connection.expectedRoleName,
              permissionPackVersion: handoff.connection.permissionPackVersion,
            },
            deployment: { publicTemplateUrl },
            collector: health,
          }, { status: handoff.recovered ? 200 : 201 });
        },
      );
    // Static-credential connections have no CloudFormation deployment at all:
    // the customer submits keys directly, so no public template URL is fetched
    // or returned. The server-held ExternalId is still generated and stored by
    // the shared draft path; it is simply unused for this kind.
    if (body.connectionMethod === "static_credentials") {
      return await createHandoff(null);
    }
    // The canonical Sutra template is fetched and authenticated before its
    // quick-launch URL is returned. Customer-managed artifacts are generated
    // from the one-time browser handoff and do not depend on that public object.
    if (body.roleProvisioningMode === "customer_managed") {
      return await createHandoff(null);
    }
    return await withVerifiedPublicCustomerRoleTemplate(
      process.env[AWS_CUSTOMER_ROLE_TEMPLATE_URL_ENV],
      createHandoff,
    );
  } catch (error) {
    return errorResponse(error);
  }
}
