import { createConnectionDraft, LOCAL_ORG_ID } from "../../../../db/pilot-repository";
import {
  assertSameOrigin,
  decryptExternalId,
  deriveLocalAwsConnectionIdentity,
  encryptExternalId,
  generateExternalId,
  parseAwsConnectionDraftRequest,
  readBoundedJson,
} from "../../../../lib/aws-pilot-security";
import {
  AWS_CUSTOMER_ROLE_TEMPLATE_URL_ENV,
  withVerifiedPublicCustomerRoleTemplate,
} from "../../../../lib/aws-cloudformation-quick-launch";
import { withLocalOnboardingAccountLock } from "../../../../lib/local-onboarding-lock";
import {
  errorResponse,
  getCollectorHealth,
  getPilotSecrets,
  jsonResponse,
  requirePilotActor,
} from "../../../../lib/pilot-server";

export const dynamic = "force-dynamic";

function slug(value: string, customerId: string): string {
  const base = value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "").slice(0, 44) || "customer";
  return `${base}-${customerId.slice(-8)}`;
}

export async function POST(request: Request): Promise<Response> {
  try {
    const actor = await requirePilotActor(request, "customer:create");
    if (actor.orgId !== LOCAL_ORG_ID) {
      throw Object.assign(
        new Error("Hosted AWS onboarding remains disabled until the tenant-scoped durable job adapter is active"),
        { code: "AUTHORIZATION_DENIED" },
      );
    }
    assertSameOrigin(request);
    const body = parseAwsConnectionDraftRequest(await readBoundedJson(request));
    // Fetch and authenticate the immutable deployment artifact before
    // generating or committing a connection handoff. The one-time ExternalId
    // is never placed in server configuration or logs.
    return await withVerifiedPublicCustomerRoleTemplate(
      process.env[AWS_CUSTOMER_ROLE_TEMPLATE_URL_ENV],
      async (publicTemplateUrl) => withLocalOnboardingAccountLock(
        body.partition,
        body.awsAccountId,
        async () => {
          const health = await getCollectorHealth(body.partition);
          if (!health.ok || !health.principalArn || health.mode !== "live") {
            throw Object.assign(new Error("The local AWS collector is not ready"), { code: "INVALID_STATE" });
          }
          const { customerId, connectionId } = await deriveLocalAwsConnectionIdentity(
            body.awsAccountId,
            body.partition,
          );
          const generatedExternalId = generateExternalId();
          const secrets = getPilotSecrets();
          const encrypted = await encryptExternalId(
            generatedExternalId,
            secrets.connectionEncryptionKey,
            secrets.connectionKeyVersion,
            { orgId: LOCAL_ORG_ID, customerId, connectionId },
          );
          const handoff = await createConnectionDraft({
            actorId: actor.id,
            operationId: body.operationId,
            customerId,
            connectionId,
            customerName: body.customerName,
            customerSlug: slug(body.customerName, customerId),
            accountId: body.awsAccountId,
            partition: body.partition,
            enabledRegions: body.enabledRegions,
            externalIdCiphertext: encrypted.ciphertext,
            externalIdKeyVersion: encrypted.keyVersion,
          });
          // Always open the committed envelope: a concurrent retry may have won
          // with different generated bytes, and returning those would strand the
          // customer role handoff.
          const externalId = await decryptExternalId(
            {
              ciphertext: handoff.externalIdCiphertext,
              keyVersion: handoff.externalIdKeyVersion,
            },
            secrets.connectionEncryptionKey,
            { orgId: LOCAL_ORG_ID, customerId, connectionId },
          );
          return jsonResponse({
            connection: handoff.connection,
            handoff: { recovered: handoff.recovered },
            trust: {
              externalId,
              vendorCollectorRoleArn: health.principalArn,
              sessionNamePrefix: "sutra-",
              customerTenantId: customerId,
              roleName: "SutraReadOnlyRole",
            },
            deployment: { publicTemplateUrl },
            collector: health,
          }, { status: handoff.recovered ? 200 : 201 });
        },
      ),
    );
  } catch (error) {
    return errorResponse(error);
  }
}
