import { AmazonConnectCostInsightRepository } from "../../../../../db/finops-amazon-connect-cost-insight-repository";
import { getConnectionForOrg } from "../../../../../db/pilot-repository";
import { assertSessionCapability, requireApiSession } from "../../../../../lib/api-auth";
import { buildAmazonConnectCostInsightDashboard, type AmazonConnectCostInsightSnapshot } from "../../../../../lib/finops-amazon-connect-cost-insight";
import { AMAZON_CONNECT_COST_RUNTIME_ACTIVATION_REASONS } from "../../../../../lib/finops-amazon-connect-cost-insight-runtime-binding";
import { AMAZON_CONNECT_OFFICIAL_DEFINITION } from "../../../../../lib/finops-amazon-connect-official-definition";
import { errorResponse, jsonResponse } from "../../../../../lib/pilot-server";
export const dynamic="force-dynamic";
const CONNECTION=/^conn_[a-f0-9]{32}$/u,SAFE=/^[A-Za-z0-9][A-Za-z0-9 ._:@+\/-]{0,127}$/u,COUNTRY=/^[A-Z]{2}$/u;
const ALLOWED=new Set(["connectionId","instanceAlias","service","chargeFamily","channel","direction","countryCode","phoneNumberType","usageUnit"]);
interface Filters{instanceAlias:string|null;service:string|null;chargeFamily:string|null;channel:string|null;direction:string|null;countryCode:string|null;phoneNumberType:string|null;usageUnit:string|null}
function invalid():never{throw Object.assign(new Error("The Amazon Connect cost request is invalid"),{code:"INVALID_INPUT",status:400});}
function parse(request:Request):{connectionId:string;filters:Filters}{const p=new URL(request.url).searchParams;for(const k of p.keys())if(!ALLOWED.has(k))invalid();for(const k of ALLOWED)if(p.getAll(k).length>1)invalid();const connectionId=p.get("connectionId")??"",instanceAlias=p.get("instanceAlias"),service=p.get("service"),chargeFamily=p.get("chargeFamily"),channel=p.get("channel"),direction=p.get("direction"),countryCode=p.get("countryCode"),phoneNumberType=p.get("phoneNumberType"),usageUnit=p.get("usageUnit");if(!CONNECTION.test(connectionId)||(instanceAlias!==null&&!SAFE.test(instanceAlias))||(service!==null&&!['AMAZON_CONNECT','CONTACT_CENTER_TELECOM'].includes(service))||(chargeFamily!==null&&!['CONNECT_SERVICE','TELEPHONY_INBOUND','TELEPHONY_OUTBOUND','PHONE_NUMBER','CHAT','TASK','EMAIL','OTHER'].includes(chargeFamily))||(channel!==null&&!['VOICE','CHAT','TASK','EMAIL','OTHER'].includes(channel))||(direction!==null&&!['INBOUND','OUTBOUND','TRANSFER','UNKNOWN'].includes(direction))||(countryCode!==null&&!COUNTRY.test(countryCode))||(phoneNumberType!==null&&!['DID','TOLL_FREE','UIFN','SHARED_COST','THIRD_PARTY','UNKNOWN'].includes(phoneNumberType))||(usageUnit!==null&&!SAFE.test(usageUnit)))invalid();return{connectionId,filters:{instanceAlias,service,chargeFamily,channel,direction,countryCode,phoneNumberType,usageUnit}};}
function project(snapshot:AmazonConnectCostInsightSnapshot,filters:Filters){const aliasByArn=new Map(snapshot.collections.flatMap(c=>c.instance===null?[]:[[c.instanceArn,c.instance.alias] as const]));const allowedArns=filters.instanceAlias===null?null:new Set(snapshot.collections.filter(c=>c.instance?.alias===filters.instanceAlias).map(c=>c.instanceArn));const end=new Date(snapshot.costEvidence.dataThroughAtIso);const endDay=Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),end.getUTCDate());const startDay=endDay-29*86400000;
  const rows=snapshot.costEvidence.rows.filter(r=>{const day=Date.parse(`${r.chargePeriodStartIso.slice(0,10)}T00:00:00.000Z`);return day>=startDay&&day<=endDay&&(allowedArns===null||(r.instanceArn!==null&&allowedArns.has(r.instanceArn)))&&(filters.service===null||r.service===filters.service)&&(filters.chargeFamily===null||r.chargeFamily===filters.chargeFamily)&&(filters.channel===null||r.channel===filters.channel)&&(filters.direction===null||r.direction===filters.direction)&&(filters.countryCode===null||r.countryCode===filters.countryCode)&&(filters.phoneNumberType===null||r.phoneNumberType===filters.phoneNumberType)&&(filters.usageUnit===null||r.usageUnit===filters.usageUnit);});
  const collections=snapshot.collections.filter(c=>allowedArns===null||allowedArns.has(c.instanceArn)).map(c=>({...c,phoneInventory:c.phoneInventory.filter(p=>(filters.countryCode===null||p.countryCode===filters.countryCode)&&(filters.phoneNumberType===null||p.phoneNumberType===filters.phoneNumberType))}));const dashboard=buildAmazonConnectCostInsightDashboard({...snapshot,collections,costEvidence:{...snapshot.costEvidence,rows}},Date.parse(snapshot.completedAtIso));
  return{filters,window:{days:30,startDay:new Date(startDay).toISOString().slice(0,10),endDay:new Date(endDay).toISOString().slice(0,10)},filterOptions:{instanceAliases:[...new Set(snapshot.collections.flatMap(c=>c.instance?[c.instance.alias]:[]))].sort(),services:[...new Set(snapshot.costEvidence.rows.map(r=>r.service))].sort(),chargeFamilies:[...new Set(snapshot.costEvidence.rows.map(r=>r.chargeFamily))].sort(),channels:[...new Set(snapshot.costEvidence.rows.map(r=>r.channel))].sort(),directions:[...new Set(snapshot.costEvidence.rows.map(r=>r.direction))].sort(),countries:[...new Set(snapshot.costEvidence.rows.flatMap(r=>r.countryCode?[r.countryCode]:[]))].sort(),phoneNumberTypes:[...new Set(snapshot.costEvidence.rows.flatMap(r=>r.phoneNumberType?[r.phoneNumberType]:[]))].sort(),usageUnits:[...new Set(snapshot.costEvidence.rows.flatMap(r=>r.usageUnit?[r.usageUnit]:[]))].sort()},overview:dashboard.overview,
    instances:dashboard.instances.map(x=>({instanceLabel:x.observation.alias,status:x.observation.status,inboundCallsEnabled:x.observation.inboundCallsEnabled,outboundCallsEnabled:x.observation.outboundCallsEnabled,observedAtIso:x.observation.observedAtIso,phoneNumberCount:x.phoneNumberCount,costMicros:x.costMicros})),telecom:dashboard.telecom,dailyUsage:dashboard.dailyUsage,
    callPatterns:dashboard.callPatterns.map(x=>({instanceLabel:x.instanceArn===null?"Unattributed":aliasByArn.get(x.instanceArn)??"Governed instance",channel:x.channel,direction:x.direction,countryCode:x.countryCode,phoneNumberType:x.phoneNumberType,contactCount:x.contactCount,costMicros:x.costMicros,quantityMicros:x.quantityMicros,unit:x.unit})),
    phoneInventory:collections.flatMap(c=>c.phoneInventory.map(p=>({instanceLabel:c.instance?.alias??"Governed instance",countryCode:p.countryCode,phoneNumberType:p.phoneNumberType,status:p.status,count:p.count}))),
    privacySafeContactDetails:dashboard.callPatterns.filter(x=>x.contactCount>0).map(x=>({instanceLabel:x.instanceArn===null?"Unattributed":aliasByArn.get(x.instanceArn)??"Governed instance",channel:x.channel,direction:x.direction,countryCode:x.countryCode,phoneNumberType:x.phoneNumberType,distinctTokenizedContactCount:x.contactCount,totalCostMicros:x.costMicros,totalUsageMicros:x.quantityMicros,unit:x.unit,detailLevel:"AGGREGATED_TOKEN_COUNTS_ONLY"})),limitations:dashboard.limitations};}
export async function GET(request:Request):Promise<Response>{try{const q=parse(request),auth=await requireApiSession(request),connection=await getConnectionForOrg(auth.subject.orgId,q.connectionId);if(connection===null||connection.sourceKind!=="aws_trust_role"||connection.status!=="active")throw Object.assign(new Error("Cloud connection not found"),{code:"NOT_FOUND",status:404});assertSessionCapability(auth,"connection:read",connection.customerId);const s={organizationId:auth.subject.orgId,customerId:connection.customerId,connectionId:connection.id},repo=new AmazonConnectCostInsightRepository(),[active,latest,history]=await Promise.all([repo.getActiveSnapshot(s),repo.getLatestSnapshot(s),repo.listHistory(s,30)]),selected=active??latest;if(selected===null)return jsonResponse({schema:"sutra.finops-amazon-connect-cost-insights-dashboard.v1",connectionId:connection.id,sourceState:"configuration_required",officialDefinition:AMAZON_CONNECT_OFFICIAL_DEFINITION,dashboard:null,collection:{jobContractAvailable:true,providerAdapterAvailable:false,reason:AMAZON_CONNECT_COST_RUNTIME_ACTIVATION_REASONS.adapter}});const dashboard=project(selected.snapshot,q.filters),age=Math.round(Math.max(0,(Date.now()-Date.parse(selected.snapshot.costEvidence.dataThroughAtIso))/3600000)*100)/100,newerIncomplete=active!==null&&latest!==null&&active.generationId!==latest.generationId;const sourceState=newerIncomplete?"partial":active===null?selected.snapshot.state:age>48?"stale":dashboard.overview.usageRowCount===0&&dashboard.overview.instanceCount===0?"empty":"complete";return jsonResponse({schema:"sutra.finops-amazon-connect-cost-insights-dashboard.v1",connectionId:connection.id,sourceState,officialDefinition:AMAZON_CONNECT_OFFICIAL_DEFINITION,dashboard,history,freshness:{dataThroughAt:selected.snapshot.costEvidence.dataThroughAtIso,ageHours:age,staleAfterHours:48},provenance:{generationId:selected.generationId,activeGenerationId:active?.generationId??null,latestGenerationId:latest?.generationId??null,newerIncomplete,captureId:selected.snapshot.captureId,billingGenerationId:selected.snapshot.costEvidence.generationId,billingManifestSha256:selected.snapshot.costEvidence.manifestSha256,costBasis:selected.snapshot.costEvidence.costBasis,currency:selected.snapshot.costEvidence.currency},privacy:{rawPhoneNumbersReturned:false,rawContactIdsReturned:false,contactTokensReturned:false,callerPiiReturned:false,standardUiDetailLevel:"AGGREGATED_TOKEN_COUNTS_ONLY",privilegedTokenLookupRouteAvailable:false},collection:{jobContractAvailable:true,providerAdapterAvailable:false,reason:AMAZON_CONNECT_COST_RUNTIME_ACTIVATION_REASONS.adapter}});}catch(error){return errorResponse(error);}}
