"use client";
import { useEffect, useState } from "react";
import type { KubecostAllocationGroup, KubecostExactDecimal } from "../../lib/finops-kubecost-allocation";
import { KUBECOST_OFFICIAL_DEFINITION, type KubecostOfficialDefinition } from "../../lib/finops-kubecost-official-definition";
import styles from "./finops-kubecost-allocation-dashboard.module.css";

interface Aggregate { readonly identity:string; readonly currency:string; readonly totalCost:KubecostExactDecimal; readonly groupCount:number }
interface Efficiency { readonly metric:string; readonly requestedOrProvisioned:KubecostExactDecimal; readonly used:KubecostExactDecimal; readonly ratio:KubecostExactDecimal|null; readonly contributingGroupCount:number; readonly state:string }
interface ComponentCost { readonly component:string; readonly currency:string; readonly totalCost:KubecostExactDecimal; readonly contributingGroupCount:number }
interface HourlyCost { readonly windowStartIso:string; readonly windowEndIso:string; readonly currency:string; readonly totalCost:KubecostExactDecimal; readonly rowCount:number }
interface Filters { readonly accountId?:string; readonly clusterId?:string; readonly namespace?:string; readonly allocationKind?:string; readonly currency?:string }
export interface KubecostDashboardEnvelope {
  readonly schema:string; readonly connectionId:string; readonly sourceState:"complete"|"partial"|"stale"|"empty"|"failed"|"configuration_required";
  readonly officialDefinition:KubecostOfficialDefinition;
  readonly filters:Filters; readonly resultCount:number; readonly rows:readonly KubecostAllocationGroup[]; readonly nextCursor:string|null;
  readonly executiveSummary:{readonly totals:readonly {readonly currency:string;readonly totalCost:KubecostExactDecimal}[];readonly componentCosts:readonly ComponentCost[];readonly efficiencies:readonly Efficiency[]};
  readonly hourlyCosts:readonly HourlyCost[];
  readonly byAccount:readonly (Aggregate&{readonly accountId:string})[]; readonly topClusters:readonly (Aggregate&{readonly clusterId:string})[];
  readonly pivots:{readonly namespaces:readonly Aggregate[];readonly controllers:readonly Aggregate[];readonly workloads:readonly Aggregate[]};
  readonly reconciliation:Readonly<Record<string,unknown>>; readonly coverage:Readonly<Record<string,unknown>>; readonly source:Readonly<Record<string,unknown>>;
  readonly unsupported:{readonly eksCapacityInstanceType:string};
  readonly history:readonly Readonly<Record<string,unknown>>[]; readonly freshness:Readonly<Record<string,unknown>>; readonly evidence:Readonly<Record<string,unknown>>;
  readonly collection:{readonly jobContractAvailable:boolean;readonly providerAdapterAvailable:boolean;readonly reason:string}; readonly disclosures:readonly string[];
}

function decimal(value:KubecostExactDecimal|null):string { if(value===null)return "Unavailable"; const n=BigInt(value.numerator),d=BigInt(value.denominator); const negative=n<BigInt(0); const abs=negative?-n:n; const scaled=abs*BigInt(100)/d; return `${negative?"-":""}${scaled/BigInt(100)}.${(scaled%BigInt(100)).toString().padStart(2,"0")}`; }
function stateText(state:KubecostDashboardEnvelope["sourceState"]):string|null { if(state==="complete")return null; if(state==="partial")return "Coverage or reconciliation is partial. The newer attempt has not replaced the accepted complete head."; if(state==="stale")return "The accepted allocation evidence is older than the 24-hour objective."; if(state==="empty")return "The complete export contains no allocations for this filter scope."; if(state==="configuration_required")return "Kubecost/OpenCost export ingestion is not configured for this connection."; return "The latest export failed; failed evidence cannot replace the accepted head."; }
function options(values:readonly (string|null)[]){return [...new Set(values.filter((value):value is string=>value!==null))].sort();}
function isRecord(value:unknown):value is Readonly<Record<string,unknown>>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}
function hasPinnedOfficialDefinition(value:unknown):value is KubecostOfficialDefinition{return isRecord(value)&&isRecord(value.cidFrameworkAudit)&&isRecord(value.quickSightDefinition)&&Array.isArray(value.artifacts)&&isRecord(value.artifacts[0])&&value.schema===KUBECOST_OFFICIAL_DEFINITION.schema&&value.sourceCommit===KUBECOST_OFFICIAL_DEFINITION.sourceCommit&&value.cidFrameworkAudit.commit===KUBECOST_OFFICIAL_DEFINITION.cidFrameworkAudit.commit&&value.artifacts[0].sha256===KUBECOST_OFFICIAL_DEFINITION.artifacts[0]?.sha256&&value.quickSightDefinition.publishedInRepository===false&&value.quickSightDefinition.sheetCount===null&&value.quickSightDefinition.visualCount===null;}

export function KubecostOfficialSourcePanel({definition}:{readonly definition:KubecostOfficialDefinition}){return <section className={styles.panel} aria-label="Official Kubecost dashboard source coverage"><h3>Official Kubecost source audit</h3><p className={styles.muted}>AWS documents three purpose-level tabs. The linked repository publishes the CID manifest, one 62-column SPICE dataset, one Terraform Athena view query, exporter, and deployment source. Its QuickSight template is service-hosted, so sheet, visual, control, parameter, calculated-field, filter-group, and pixel-geometry totals remain unknown rather than inferred.</p><div className={styles.grid}>{definition.documentedAreas.map((area)=><article className={styles.card} key={area.name}><small>AWS-documented area · {area.nativeCoverage.toLocaleLowerCase()}</small><strong>{area.name}</strong><span>{area.documentedPurpose}</span><span><b>Native:</b> {area.nativeEvidence}</span><span><b>Remaining:</b> {area.remainingGap}</span></article>)}</div><div className={styles.notice}><strong>Supplemental OpenCost boundary.</strong> {definition.supplementalOpenCost.disclosure}</div><details className={styles.evidence}><summary>Immutable official artifacts and unpublished definition boundary</summary><p>Official repository <code>{definition.sourceCommit}</code> · CID framework <code>{definition.cidFrameworkAudit.commit}</code> contains {definition.cidFrameworkAudit.kubecostDashboardSpecificArtifactCount} Kubecost-specific artifacts. Complete QuickSight definition: unpublished; exact object totals: null.</p><ul>{definition.artifacts.map((artifact)=><li key={artifact.kind}><strong>{artifact.kind.replaceAll("_"," ")}</strong> · <code>{artifact.sha256}</code> · {artifact.hashBasis}</li>)}</ul></details></section>;}

export function FinopsKubecostAllocationReportView({report,filters,onFiltersChange}:{readonly report:KubecostDashboardEnvelope;readonly filters:Filters;readonly onFiltersChange:(filters:Filters)=>void}){
  const status=stateText(report.sourceState); const set=(key:keyof Filters,value:string)=>onFiltersChange({...filters,[key]:value||undefined});
  const accountOptions=options(report.rows.map((row)=>row.usageAccountId)); const clusterOptions=options(report.rows.map((row)=>row.clusterId)); const namespaceOptions=options(report.rows.map((row)=>row.namespace)); const currencyOptions=options(report.rows.map((row)=>row.currency));
  return <section className={styles.root} aria-label="Kubecost containers cost allocation dashboard">
    <div className={styles.notice}><strong>Allocation, not additional spend.</strong> Official coverage is Kubecost self-hosted; OpenCost is a clearly supplemental Sutra source. Either attribution source is reconciled to the pinned active CUR2 generation and must never be added to CUR2. Currencies remain separate.</div>
    {status?<div role="status" className={`${styles.state} ${report.sourceState==="failed"?styles.error:styles.warning}`}>{status}</div>:null}
    <div className={styles.filters} aria-label="Workloads Explorer filters"><label>Account<select value={filters.accountId??""} onChange={(event)=>set("accountId",event.target.value)}><option value="">All</option>{accountOptions.map((value)=><option key={value}>{value}</option>)}</select></label><label>Cluster<select value={filters.clusterId??""} onChange={(event)=>set("clusterId",event.target.value)}><option value="">All</option>{clusterOptions.map((value)=><option key={value}>{value}</option>)}</select></label><label>Namespace<select value={filters.namespace??""} onChange={(event)=>set("namespace",event.target.value)}><option value="">All</option>{namespaceOptions.map((value)=><option key={value}>{value}</option>)}</select></label><label>Allocation kind<select value={filters.allocationKind??""} onChange={(event)=>set("allocationKind",event.target.value)}><option value="">All</option>{["WORKLOAD","IDLE","SHARED","EXTERNAL","UNALLOCATED","UNMOUNTED"].map((value)=><option key={value}>{value}</option>)}</select></label><label>Currency<select value={filters.currency??""} onChange={(event)=>set("currency",event.target.value)}><option value="">All</option>{currencyOptions.map((value)=><option key={value}>{value}</option>)}</select></label></div>

    <div className={styles.grid} aria-label="Official Kubecost dashboard tabs">{["Executive Summary","Workloads Explorer","EKS Breakdown"].map((tab)=><article className={styles.card} key={tab}><small>Official tab</small><strong>{tab}</strong><span>native evidence view</span></article>)}</div>

    <section className={styles.panel} aria-label="Executive Summary"><h3>Executive Summary</h3><div className={styles.grid}>{report.executiveSummary.totals.map((item)=><article className={styles.card} key={item.currency}><small>Total allocated cost · {item.currency}</small><strong>{decimal(item.totalCost)}</strong><span>reconciled attribution</span></article>)}{report.executiveSummary.efficiencies.map((item)=><article className={styles.card} key={item.metric}><small>{item.metric} usage vs requests</small><strong>{item.ratio===null?"Unknown":`${decimal({numerator:(BigInt(item.ratio.numerator)*BigInt(100)).toString(),denominator:item.ratio.denominator})}%`}</strong><span>{item.state} · {item.contributingGroupCount} groups</span></article>)}{report.executiveSummary.componentCosts.map((item)=><article className={styles.card} key={`${item.currency}:${item.component}`}><small>{item.component.replaceAll("_"," ")} cost · {item.currency}</small><strong>{decimal(item.totalCost)}</strong><span>{item.contributingGroupCount} exact component groups</span></article>)}</div></section>

    <section className={styles.panel} aria-label="Total cost by account and top clusters"><h3>Total cost by account and top clusters</h3><div className={styles.grid}>{report.byAccount.slice(0,8).map((item)=><article className={styles.card} key={`${item.accountId}:${item.currency}`}><small>Account {item.accountId}</small><strong>{item.currency} {decimal(item.totalCost)}</strong><span>{item.groupCount} allocation groups</span></article>)}{report.topClusters.slice(0,8).map((item)=><article className={styles.card} key={`${item.clusterId}:${item.currency}`}><small>Cluster {item.clusterId}</small><strong>{item.currency} {decimal(item.totalCost)}</strong><span>{item.groupCount} allocation groups</span></article>)}</div></section>

    <section className={styles.panel} aria-label="Hourly allocation trend"><h3>Hourly allocated-cost trend</h3><div className={styles.scroll}><table className={styles.table}><thead><tr><th>UTC window</th><th>Currency</th><th>Exact allocated cost</th><th>Source rows</th></tr></thead><tbody>{report.hourlyCosts.map((item)=><tr key={`${item.windowStartIso}:${item.currency}`}><td><time dateTime={item.windowStartIso}>{item.windowStartIso.replace("T"," ").slice(0,16)}</time> – {item.windowEndIso.slice(11,16)}</td><td>{item.currency}</td><td>{decimal(item.totalCost)}</td><td>{item.rowCount}</td></tr>)}</tbody></table></div></section>

    <section className={styles.panel} aria-label="Workloads Explorer"><h3>Workloads Explorer · stacked allocation and pivot</h3><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Account / cluster</th><th>Namespace</th><th>Controller / workload</th><th>Pod / container</th><th>Kind</th><th>Exact total</th><th>CPU efficiency</th><th>RAM efficiency</th></tr></thead><tbody>{report.rows.map((row)=><tr key={`${row.sourceRowIds[0]??row.clusterId}:${row.currency}`}><td>{row.usageAccountId}<br/>{row.clusterId}</td><td>{row.namespace??"Unallocated"}</td><td>{row.controllerKind??"—"} / {row.controller??"—"}<br/>{row.workload??"—"}</td><td>{row.pod??"—"}<br/>{row.container??"—"}</td><td><span className={styles.pill}>{row.allocationKind}</span></td><td>{row.currency} {decimal(row.totalCost)}</td><td>{decimal(row.efficiencies.find((item)=>item.metric==="CPU")?.ratio??null)}</td><td>{decimal(row.efficiencies.find((item)=>item.metric==="RAM")?.ratio??null)}</td></tr>)}</tbody></table></div></section>

    <section className={styles.panel} aria-label="EKS Breakdown"><h3>EKS Breakdown · distribution, coverage, and drilldown</h3><div className={styles.grid}>{report.topClusters.map((item)=><article className={styles.card} key={`eks:${item.clusterId}:${item.currency}`}><small>{item.clusterId}</small><strong>{item.currency} {decimal(item.totalCost)}</strong><span>{item.groupCount} container allocation groups</span></article>)}</div><p className={`${styles.muted} ${styles.unknown}`}>Capacity type and instance-type breakdown unavailable: {report.unsupported.eksCapacityInstanceType}</p></section>

    <section className={styles.panel} aria-label="Showback and chargeback"><h3>Showback / chargeback evidence</h3><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Namespace</th><th>Currency</th><th>Allocated cost</th><th>Groups</th></tr></thead><tbody>{report.pivots.namespaces.map((item)=><tr key={`${item.identity}:${item.currency}`}><td>{item.identity}</td><td>{item.currency}</td><td>{decimal(item.totalCost)}</td><td>{item.groupCount}</td></tr>)}</tbody></table></div><p className={styles.muted}>This is reconciled showback evidence. No invoice, journal entry, transfer, or chargeback posting is created by this read-only dashboard.</p></section>
    <details className={`${styles.panel} ${styles.evidence}`}><summary>Reconciliation, provenance, coverage, and history</summary><pre>{JSON.stringify({reconciliation:report.reconciliation,coverage:report.coverage,source:report.source,freshness:report.freshness,evidence:report.evidence,collection:report.collection,history:report.history,disclosures:report.disclosures},null,2)}</pre></details>
  </section>;
}

export function FinopsKubecostAllocationDashboard({connectionId}:{readonly connectionId:string|null}){
  const [filters,setFilters]=useState<Filters>({}); const [state,setState]=useState<{report:KubecostDashboardEnvelope|null;error:string|null;configurationRequired:boolean;officialDefinition:KubecostOfficialDefinition}>({report:null,error:null,configurationRequired:false,officialDefinition:KUBECOST_OFFICIAL_DEFINITION});
  useEffect(()=>{if(connectionId===null)return; const controller=new AbortController(); const parameters=new URLSearchParams({connectionId}); for(const [key,value] of Object.entries(filters))if(value)parameters.set(key,value);
    fetch(`/api/v1/finops/kubecost-allocation?${parameters.toString()}`,{signal:controller.signal,headers:{Accept:"application/json"}}).then(async(response)=>{if(!response.ok)throw new Error("Kubecost allocation request failed");return response.json() as Promise<KubecostDashboardEnvelope|{readonly dashboard:null;readonly officialDefinition:KubecostOfficialDefinition}>;}).then((report)=>{if(!hasPinnedOfficialDefinition(report.officialDefinition))throw new Error("Sutra returned an unrecognized official Kubecost source audit");if("dashboard" in report&&report.dashboard===null)setState({report:null,error:null,configurationRequired:true,officialDefinition:report.officialDefinition});else setState({report:report as KubecostDashboardEnvelope,error:null,configurationRequired:false,officialDefinition:report.officialDefinition});}).catch((error:unknown)=>{if(!controller.signal.aborted)setState((current)=>({report:null,error:error instanceof Error?error.message:"Kubecost allocation request failed",configurationRequired:false,officialDefinition:current.officialDefinition}));}); return()=>controller.abort();},[connectionId,filters]);
  let content;if(connectionId===null)content=<div role="status" className={`${styles.state} ${styles.warning}`}>Connect an active AWS trust-role account before configuring Kubecost allocation.</div>;
  else if(state.configurationRequired)content=<div role="status" className={`${styles.state} ${styles.warning}`}>Configure the official self-hosted Kubecost exporter (or Sutra&apos;s supplemental OpenCost source) and deploy the signed versioned-object ingest adapter. No allocation state is synthesized.</div>;
  else if(state.error!==null)content=<div role="alert" className={`${styles.state} ${styles.error}`}>{state.error}</div>;
  else if(state.report===null||state.report.connectionId!==connectionId)content=<div role="status" className={styles.state}>Loading reconciled container allocation…</div>;
  else content=<FinopsKubecostAllocationReportView report={state.report} filters={filters} onFiltersChange={setFilters}/>;
  return <section className={styles.root}><KubecostOfficialSourcePanel definition={state.officialDefinition}/>{content}</section>;
}
