"use client";

import { useEffect, useState } from "react";
import { AWS_SUPPORT_CASES_OFFICIAL_DEFINITION, type AwsSupportCasesOfficialDefinition } from "../../lib/finops-aws-support-cases-official-definition";
import type { FinopsDashboardCatalogEntry } from "../../lib/finops-dashboard-catalog";
import { FinopsCapabilityShell, type FinopsCapabilityViewState } from "./finops-capability-shell";
import styles from "./finops-aws-support-cases-radar-dashboard.module.css";

type Filters = { accountId: string; status: string; severity: string; serviceCode: string; categoryCode: string };
const EMPTY: Filters = { accountId: "", status: "", severity: "", serviceCode: "", categoryCode: "" };
type SourceState = "configuration_required" | "unverified" | "unavailable" | "partial" | "stale" | "empty" | "complete";
interface AccountCoverage { readonly accountId: string; readonly supportPlan: string; readonly entitlementState: string; readonly readPermissionsValidated: boolean; readonly status: string; readonly caseCount: number; readonly communicationCount: number; readonly failureCode: string | null }
interface CaseRow { readonly accountId: string; readonly caseReference: string; readonly serviceCode: string; readonly categoryCode: string; readonly severity: string; readonly status: string; readonly createdAt: string; readonly updatedAt: string; readonly resolvedObservedAt: string | null; readonly submittedByKind: string; readonly communicationCount: number; readonly attachmentCount: number; readonly observationCount: number; readonly communicationsComplete: boolean }
interface Report {
  readonly schema: "sutra.finops-aws-support-cases-radar.v1"; readonly connectionId: string; readonly sourceState: SourceState; readonly generatedAt: string;
  readonly officialDefinition: AwsSupportCasesOfficialDefinition;
  readonly source: { readonly latestObservedAt: string; readonly freshness: "fresh" | "stale"; readonly historyCoverage: string; readonly watermarkCoverage: string; readonly organizationCoverageClaimed: false; readonly accountCoverage: readonly AccountCoverage[]; readonly limitations: readonly string[] };
  readonly summary: { readonly caseCount: number; readonly openCount: number; readonly resolvedCount: number; readonly pendingCustomerActionCount: number; readonly highUrgentCriticalCount: number; readonly communicationCount: number; readonly intendedAccountCount: number; readonly completeAccountCount: number; readonly statusCounts: Readonly<Record<string, number>>; readonly severityCounts: Readonly<Record<string, number>>; readonly serviceCounts: readonly { readonly code: string; readonly count: number }[]; readonly categoryCounts: readonly { readonly code: string; readonly count: number }[]; readonly communicationActorCounts: Readonly<Record<"AWS" | "CUSTOMER" | "UNKNOWN", number>>; readonly responseCadence: { readonly awsResponseTransitions: number; readonly customerResponseTransitions: number; readonly averageAwsResponseMinutes: number | null; readonly averageCustomerResponseMinutes: number | null }; readonly openAgeBands: { readonly under7Days: number; readonly days7To30: number; readonly days31To90: number; readonly over90Days: number } };
  readonly cases: readonly CaseRow[]; readonly casesTruncated: boolean; readonly disclosure: string;
  readonly history: readonly { readonly generationId: string; readonly observedAt: string; readonly dataThroughAt: string; readonly collectionState: string; readonly intendedAccountCount: number; readonly completeAccountCount: number; readonly caseCount: number; readonly openCount: number; readonly highUrgentCriticalCount: number }[];
  readonly provenance: { readonly activeGenerationId: string | null; readonly latestGenerationId: string | null; readonly newerIncomplete: boolean; readonly contentSha256: string; readonly latestAttemptContentSha256: string | null; readonly captureId: string; readonly observedAt: string; readonly dataThroughAt: string; readonly organizationCoverageClaimed: false };
  readonly collection: { readonly available: false; readonly reason: string }; readonly summarization: { readonly available: false; readonly provider: null; readonly reason: string };
}
type RequestState = { status: "loading" } | { status: "failed"; message: string } | { status: "loaded"; report: Report | null; officialDefinition: AwsSupportCasesOfficialDefinition };
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function hasPinnedOfficialDefinition(value: unknown): value is AwsSupportCasesOfficialDefinition { if (!isRecord(value) || !isRecord(value.source) || !isRecord(value.source.manifest) || !isRecord(value.quickSightDefinition)) return false; return value.source.commit === AWS_SUPPORT_CASES_OFFICIAL_DEFINITION.source.commit && value.source.manifest.sha256 === AWS_SUPPORT_CASES_OFFICIAL_DEFINITION.source.manifest.sha256 && value.quickSightDefinition.state === "NOT_PUBLICLY_COMMITTED" && Array.isArray(value.documentedTabs) && value.documentedTabs.length === 3; }
async function load(connectionId: string, filters: Filters, signal: AbortSignal): Promise<{ readonly report: Report | null; readonly officialDefinition: AwsSupportCasesOfficialDefinition }> {
  const query = new URLSearchParams({ connectionId }); for (const [key, value] of Object.entries(filters)) if (value) query.set(key, value);
  const response = await fetch(`/api/v1/finops/aws-support-cases-radar?${query}`, { credentials: "same-origin", signal });
  const body = await response.json() as unknown;
  if (!response.ok) throw new Error(isRecord(body) && isRecord(body.error) && typeof body.error.message === "string" ? body.error.message : "Support case evidence could not be loaded.");
  if (!isRecord(body) || body.schema !== "sutra.finops-aws-support-cases-radar.v1" || body.connectionId !== connectionId) throw new Error("Sutra returned invalid Support case evidence.");
  if (!hasPinnedOfficialDefinition(body.officialDefinition)) throw new Error("Sutra returned an unrecognized Support Cases official source audit.");
  if (body.dashboard === null) return { report: null, officialDefinition: body.officialDefinition };
  if (!Array.isArray(body.cases) || !Array.isArray(body.history) || !isRecord(body.source) || !isRecord(body.summary) || !isRecord(body.provenance)) throw new Error("Sutra returned invalid Support case evidence.");
  return { report: body as unknown as Report, officialDefinition: body.officialDefinition };
}
function presentation(connectionId: string | null, state: RequestState): { view: FinopsCapabilityViewState; title: string; detail: string } {
  if (connectionId === null) return { view: "configuration_required", title: "Connect AWS before viewing Support cases", detail: "A tenant-scoped active AWS trust-role connection is required." };
  if (state.status === "loading") return { view: "loading", title: "Loading accepted Support case evidence", detail: "Reading privacy-minimized account-local history." };
  if (state.status === "failed") return { view: "failed", title: "Support case evidence could not be verified", detail: state.message };
  if (state.report === null) return { view: "configuration_required", title: "Support case collection is not configured", detail: "Bind the server-owned account fan-out collector and validate a qualifying Support plan." };
  const source = state.report.sourceState;
  if (source === "complete") return { view: "complete", title: "Support case radar loaded", detail: "The complete accepted generation passed entitlement, permission, and pagination checks." };
  if (source === "empty") return { view: "empty", title: "No cases match this scope", detail: "Complete linked-account coverage returned no cases for the retained window or filters." };
  if (source === "stale") return { view: "stale", title: "Support case evidence is stale", detail: "The active generation is older than the 48-hour target." };
  if (source === "partial") return { view: "partial", title: "Support case coverage is partial", detail: "The prior accepted head remains visible while incomplete account evidence is disclosed." };
  if (source === "unavailable") return { view: "failed", title: "Support API is unavailable", detail: "One or more accounts has a non-qualifying plan or provider failure." };
  return { view: "configuration_required", title: "Support entitlement is unverified", detail: "Validate Business Support+, Enterprise, Unified Operations, or applicable legacy plan entitlement in every linked account." };
}
function Select({ label, value, values, onChange }: { label: string; value: string; values: readonly string[]; onChange(value: string): void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function minutes(value: number | null): string { if (value === null) return "Unavailable"; if (value < 60) return `${value} min`; const hours = Math.floor(value / 60); const remainder = value % 60; return `${hours}h${remainder === 0 ? "" : ` ${remainder}m`}`; }
export function AwsSupportCasesOfficialDefinitionPanel({ definition }: { readonly definition: AwsSupportCasesOfficialDefinition }) { return <section className={styles.official} aria-label="Official AWS Support Cases Radar coverage"><header><div><h3>Official AWS source coverage</h3><p>Managed QuickSight definition not publicly committed · exact object totals unavailable</p></div><small>{definition.source.commit.slice(0, 12)} · {definition.source.manifest.sha256.slice(0, 16)}…</small></header><div className={styles.officialGrid}><article><strong>Documented tabs</strong><ul>{definition.documentedTabs.map((tab) => <li key={tab}>{tab}</li>)}</ul></article><article><strong>Published data contracts</strong><ul>{definition.publishedDatasets.map((dataset) => <li key={dataset.name}><code>{dataset.name}</code><small>{dataset.uniqueInputColumns} unique input columns · {dataset.safePurpose}</small></li>)}</ul></article><article><strong>Preview visual purposes</strong><ul>{definition.documentedPreviewPurposes.map((purpose) => <li key={purpose}>{purpose}</li>)}</ul></article><article><strong>Preview controls</strong><ul>{definition.documentedPreviewControls.map((control) => <li key={control}>{control}</li>)}</ul></article></div><p className={styles.officialNote}>{definition.quickSightDefinition.disclosure} Raw communications and generative summary fields remain excluded from the browser. Frozen source evidence remains visible without a provider report.</p></section>; }
export function AwsSupportCasesRadarReportView({ report, filters, onFiltersChange }: { report: Report; filters: Filters; onFiltersChange(filters: Filters): void }) {
  const set = (key: keyof Filters, value: string) => onFiltersChange({ ...filters, [key]: value });
  const maximum = Math.max(1, ...report.history.map((point) => point.caseCount));
  const accounts = report.source.accountCoverage.map((entry) => entry.accountId); const services = report.summary.serviceCounts.map((entry) => entry.code); const categories = report.summary.categoryCounts.map((entry) => entry.code);
  return <section className={styles.workspace} aria-label="AWS Support Cases Radar">
    <div className={styles.privacy}><strong>Privacy-minimized operational evidence.</strong> Subjects, correspondence, names, email addresses, attachments, provider messages, raw pagination tokens, internal case IDs, and evidence hashes are not returned to this browser.</div>
    <AwsSupportCasesOfficialDefinitionPanel definition={report.officialDefinition} />
    <section className={styles.filters} aria-label="Support case filters"><Select label="Account" value={filters.accountId} values={accounts} onChange={(value) => set("accountId", value)} /><Select label="Status" value={filters.status} values={Object.keys(report.summary.statusCounts)} onChange={(value) => set("status", value)} /><Select label="Severity" value={filters.severity} values={Object.keys(report.summary.severityCounts)} onChange={(value) => set("severity", value)} /><Select label="Service" value={filters.serviceCode} values={services} onChange={(value) => set("serviceCode", value)} /><Select label="Category" value={filters.categoryCode} values={categories} onChange={(value) => set("categoryCode", value)} /><button type="button" onClick={() => onFiltersChange(EMPTY)}>Clear filters</button></section>
    <section className={styles.kpis} aria-label="Support case summary"><article><span>Open cases</span><strong>{report.summary.openCount}</strong><small>{report.summary.caseCount} retained cases</small></article><article><span>High / urgent / critical</span><strong>{report.summary.highUrgentCriticalCount}</strong><small>Metadata severity only</small></article><article><span>Pending customer</span><strong>{report.summary.pendingCustomerActionCount}</strong><small>Action-state signal</small></article><article><span>Account coverage</span><strong>{report.summary.completeAccountCount} / {report.summary.intendedAccountCount}</strong><small>Complete linked accounts</small></article><article><span>Communications</span><strong>{report.summary.communicationCount}</strong><small>Count only; text excluded</small></article></section>
    <section className={styles.two}><article className={styles.panel}><header><h3>Case history</h3><span>Observed snapshots only</span></header><div className={styles.trend} role="img" aria-label="Support case count by accepted generation">{report.history.slice().reverse().map((point) => <div key={point.generationId} title={`${point.observedAt}: ${point.caseCount} cases`}><i style={{ height: `${Math.max(4, point.caseCount / maximum * 100)}%` }} /><small>{point.observedAt.slice(5, 10)}</small></div>)}</div></article><article className={styles.panel}><header><h3>Support-plan readiness</h3><span>Per account</span></header><div className={styles.coverage}>{report.source.accountCoverage.map((account) => <div key={account.accountId} data-state={account.status}><span>{account.accountId}<small>{account.supportPlan.replaceAll("_", " ")} · {account.entitlementState}</small></span><strong>{account.status}</strong></div>)}</div></article></section>
    <section className={styles.two}><article className={styles.panel}><header><h3>Open case age</h3><span>Provider creation time</span></header><div className={styles.metrics}><div><span>Under 7 days</span><strong>{report.summary.openAgeBands.under7Days}</strong></div><div><span>7–30 days</span><strong>{report.summary.openAgeBands.days7To30}</strong></div><div><span>31–90 days</span><strong>{report.summary.openAgeBands.days31To90}</strong></div><div><span>Over 90 days</span><strong>{report.summary.openAgeBands.over90Days}</strong></div></div></article><article className={styles.panel}><header><h3>Response cadence</h3><span>Timestamp transitions; correspondence excluded</span></header><div className={styles.metrics}><div><span>Average AWS response</span><strong>{minutes(report.summary.responseCadence.averageAwsResponseMinutes)}</strong><small>{report.summary.responseCadence.awsResponseTransitions} customer-to-AWS transitions</small></div><div><span>Average customer response</span><strong>{minutes(report.summary.responseCadence.averageCustomerResponseMinutes)}</strong><small>{report.summary.responseCadence.customerResponseTransitions} AWS-to-customer transitions</small></div><div><span>AWS communications</span><strong>{report.summary.communicationActorCounts.AWS}</strong></div><div><span>Customer communications</span><strong>{report.summary.communicationActorCounts.CUSTOMER}</strong><small>{report.summary.communicationActorCounts.UNKNOWN} unclassified</small></div></div></article></section>
    <section className={styles.panel}><header><h3>Severity and service signals</h3><span>Selected scope</span></header><div className={styles.distributions}>{Object.entries(report.summary.severityCounts).map(([label, count]) => <button type="button" key={label} onClick={() => set("severity", label)}><span>{label}</span><strong>{count}</strong></button>)}{report.summary.serviceCounts.slice(0, 8).map((item) => <button type="button" key={item.code} onClick={() => set("serviceCode", item.code)}><span>{item.code}</span><strong>{item.count}</strong></button>)}</div></section>
    <section className={styles.panel}><header><h3>Top case topics</h3><span>Provider category codes</span></header><div className={styles.distributions}>{report.summary.categoryCounts.slice(0, 12).map((item) => <button type="button" key={item.code} onClick={() => set("categoryCode", item.code)}><span>{item.code}</span><strong>{item.count}</strong></button>)}</div></section>
    <section className={styles.panel}><header><h3>Case metadata drilldown</h3><span>{report.cases.length}{report.casesTruncated ? "+" : ""} rows</span></header><div className={styles.tableWrap} role="region" tabIndex={0} aria-label="Privacy-minimized Support case table"><table><caption>Allowlisted metadata only; no correspondence is available</caption><thead><tr><th>Case</th><th>Account</th><th>Status</th><th>Severity</th><th>Service / category</th><th>Observed activity</th><th>Updated</th></tr></thead><tbody>{report.cases.map((item) => <tr key={`${item.accountId}:${item.caseReference}:${item.updatedAt}`}><td>{item.caseReference}</td><td>{item.accountId}</td><td><span data-state={item.status}>{item.status}</span></td><td>{item.severity}</td><td>{item.serviceCode}<small>{item.categoryCode}</small></td><td>{item.communicationCount} communications<small>{item.attachmentCount} attachment references counted</small></td><td>{item.updatedAt}<small>{item.resolvedObservedAt === null ? `${item.observationCount} observations` : `Resolved first observed ${item.resolvedObservedAt}`}</small></td></tr>)}</tbody></table></div></section>
    <details className={styles.evidence}><summary>Evidence, history limits, and disabled optional features</summary><dl><div><dt>Active generation</dt><dd>{report.provenance.activeGenerationId ?? "No complete head"}</dd></div><div><dt>SHA-256</dt><dd>{report.provenance.contentSha256}</dd></div><div><dt>Data through</dt><dd>{report.provenance.dataThroughAt}</dd></div><div><dt>Organization API claim</dt><dd>{report.provenance.organizationCoverageClaimed ? "Claimed" : "Not claimed — explicit account fan-out"}</dd></div><div><dt>Optional Bedrock summaries</dt><dd>{report.summarization.reason}</dd></div><div><dt>Collector activation</dt><dd>{report.collection.reason}</dd></div></dl><ul>{report.source.limitations.map((item) => <li key={item}>{item}</li>)}</ul></details>
  </section>;
}
export function FinopsAwsSupportCasesRadarDashboard({ connectionId, dashboard }: { connectionId: string | null; dashboard: FinopsDashboardCatalogEntry }) {
  const [filters, setFilters] = useState<Filters>(EMPTY); const [state, setState] = useState<RequestState>({ status: "loading" });
  useEffect(() => { if (connectionId === null) return; const abort = new AbortController(); const frame = window.requestAnimationFrame(() => { setState({ status: "loading" }); void load(connectionId, filters, abort.signal).then((loaded) => setState({ status: "loaded", ...loaded }), (error: unknown) => { if (!abort.signal.aborted) setState({ status: "failed", message: error instanceof Error ? error.message : "Support case request failed." }); }); }); return () => { window.cancelAnimationFrame(frame); abort.abort(); }; }, [connectionId, filters]);
  const shown = presentation(connectionId, state); const report = state.status === "loaded" ? state.report : null; const definition = state.status === "loaded" ? state.officialDefinition : AWS_SUPPORT_CASES_OFFICIAL_DEFINITION;
  const evidence = report === null ? null : { sourceLabel: "Account-local AWS Support DescribeCases and DescribeCommunications fan-out", collectedAt: report.provenance.observedAt, dataThroughAt: report.provenance.dataThroughAt, freshnessAgeHours: null, freshnessSlaHours: 48, acceptedRecords: report.summary.caseCount, rejectedRecords: null, generationId: report.provenance.activeGenerationId, contentSha256: report.provenance.contentSha256, limitations: report.source.limitations };
  return <FinopsCapabilityShell dashboard={dashboard} state={shown.view} stateTitle={shown.title} stateDetail={shown.detail} evidence={evidence}>{report === null ? <AwsSupportCasesOfficialDefinitionPanel definition={definition} /> : <AwsSupportCasesRadarReportView report={report} filters={filters} onFiltersChange={setFilters} />}</FinopsCapabilityShell>;
}
