"use client";
import { useEffect, useState } from "react";
import type { FinopsDashboardCatalogEntry } from "../../lib/finops-dashboard-catalog";
import { MARKETPLACE_SPG_OFFICIAL_DEFINITION, type MarketplaceSpgOfficialDefinition } from "../../lib/finops-marketplace-spg-official-definition";
import { FinopsCapabilityShell, type FinopsCapabilityViewState } from "./finops-capability-shell";
import styles from "./finops-marketplace-spg-dashboard.module.css";

type Filters = { accountId: string; product: string; seller: string; currency: string; billingPeriod: string; agreementStatus: string; expirationState: string; licenseStatus: string };
const EMPTY: Filters = { accountId: "", product: "", seller: "", currency: "", billingPeriod: "", agreementStatus: "", expirationState: "", licenseStatus: "" };
interface SpendSummary { currency: string; billedAmountMicros: string; amortizedAmountMicros: string | null; rowCount: number }
interface RankedSpend extends SpendSummary { key: string }
interface Agreement { agreementId: string; sourceAccountId: string; status: string; acceptanceAt: string | null; startAt: string | null; endAt: string | null; offerId: string | null; productId: string | null; expirationState: string; estimatedCharges: { amountMicros: string; currency: string; meaning: string } | null; product: { productName: string; sellerDisplayName: string; deployedOnAws: string; fulfillmentTypes: readonly string[] } | null; terms: readonly { type: string; legalDocumentTypes: readonly string[]; autoRenew: boolean | null; committedAmountMicros: string | null }[]; entitlements: readonly { type: string; status: string; resourceType: string | null }[]; charges: readonly { chargeId: string; chargeAt: string | null; money: { amount: string; currencyCode: string } }[] }
interface License { licenseArn: string; beneficiaryAccountId: string; productName: string; licenseName: string; status: string; validity: { startAt: string; endAt: string } | null; entitlements: readonly { name: string; unit: string; value: string | null; maxCount: string | null; overageAllowed: boolean | null }[] }
interface Grant { grantArn: string; licenseArn: string; granteeAccountId: string; status: string; operations: readonly string[] }
interface SpendRow { linkedAccountId: string; billingPeriod: string; invoiceId: string | null; productCode: string | null; productName: string; sellerName: string; chargeCategory: string; currency: string; billedAmountMicros: string; amortizedAmountMicros: string | null }
export interface MarketplaceSpgReport { schema: "sutra.finops-marketplace-spg-dashboard.v1"; connectionId: string; sourceState: string; dashboard: { filters: Record<string, string | null>; filterOptions: { accounts: readonly string[]; products: readonly string[]; sellers: readonly string[]; currencies: readonly string[]; periods: readonly string[] }; summaries: readonly SpendSummary[]; trends: readonly ({ billingPeriod: string } & SpendSummary)[]; spendBySeller: readonly RankedSpend[]; spendByProduct: readonly RankedSpend[]; spendByAccount: readonly RankedSpend[]; spendByInvoice: readonly RankedSpend[]; agreementDeployment: readonly { status: string; activeAgreementCount: number; lifecycleCommitments: readonly { currency: string; amountMicros: string }[] }[]; agreementChargesByMonth: readonly { month: string; currency: string; amountMicros: string }[]; licenseExpirationSummary: readonly { state: string; count: number }[]; licenseStatusSummary: readonly { status: string; count: number }[]; licenseProductSummary: readonly { productName: string; count: number }[]; projectionTruncation: { filterOptions: boolean; spendRankings: boolean; agreementCharges: boolean; licenseProducts: boolean }; agreements: readonly Agreement[]; agreementsTruncated: boolean; licenses: readonly License[]; licensesTruncated: boolean; grants: readonly Grant[]; grantsTruncated: boolean; spendRows: readonly SpendRow[]; spendRowsTruncated: boolean; counts: { agreements: number; expiringWithin90Days: number; licenses: number; grants: number; activeGrants: number; spendRows: number } }; officialDefinition: MarketplaceSpgOfficialDefinition; history: readonly { generationId: string; capturedAt: string; state: string; agreementCount: number; licenseCount: number; grantCount: number; spendRowCount: number; spendSummaries: readonly SpendSummary[] }[]; source: { organizationCoverage: string; channelStates: Record<string, string>; limitations: readonly string[] }; freshness: { dataThroughAt: string; ageHours: number; staleAfterHours: number }; provenance: { generationId: string; activeGenerationId: string | null; latestGenerationId: string | null; newerIncomplete: boolean; captureId: string; contentSha256: string; cur2GenerationId: string | null; cur2SourceEvidenceId: string | null; cur2Predicate: string | null }; separation: Record<string, string | boolean>; collection: { jobContractAvailable: true; providerAdapterAvailable: false; reason: string }; unsupportedOfficialViews: readonly string[] }
interface MarketplaceSpgConfigurationEnvelope { readonly dashboard: null; readonly officialDefinition: MarketplaceSpgOfficialDefinition }
function hasPinnedOfficialDefinition(value: unknown): value is MarketplaceSpgOfficialDefinition { if (typeof value !== "object" || value === null) return false; const definition = value as Readonly<Record<string, unknown>>; const source = definition.source; return typeof source === "object" && source !== null && (source as Readonly<Record<string, unknown>>).commit === MARKETPLACE_SPG_OFFICIAL_DEFINITION.source.commit && (source as Readonly<Record<string, unknown>>).sha256 === MARKETPLACE_SPG_OFFICIAL_DEFINITION.source.sha256 && definition.documentedTabCount === 5 && definition.documentedVisualAreaCount === 23 && Array.isArray(definition.tabs) && definition.tabs.length === 5; }

function money(micros: string | null, currency: string): string { if (micros === null) return "Not supplied"; const negative = micros.startsWith("-"); const digits = negative ? micros.slice(1) : micros; const padded = digits.padStart(7, "0"); const whole = padded.slice(0, -6).replace(/\B(?=(\d{3})+(?!\d))/gu, ","); const fraction = padded.slice(-6).replace(/0+$/u, ""); return `${negative ? "-" : ""}${currency} ${whole}${fraction ? `.${fraction}` : ""}`; }
function csvCell(value: string): string { const safe = /^[=+\-@\t\r]/u.test(value) ? `'${value}` : value; return `"${safe.replaceAll('"', '""')}"`; }
function exportSpend(rows: readonly SpendRow[]): void { const columns = ["billing_period","account","invoice","product_code","product","seller","charge_category","currency","billed_micros","amortized_micros"]; const lines = rows.map((row) => [row.billingPeriod,row.linkedAccountId,row.invoiceId ?? "",row.productCode ?? "",row.productName,row.sellerName,row.chargeCategory,row.currency,row.billedAmountMicros,row.amortizedAmountMicros ?? ""].map(csvCell).join(",")); const url = URL.createObjectURL(new Blob([[columns.join(","), ...lines].join("\n")], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "sutra-marketplace-cur2-visible-rows.csv"; anchor.click(); URL.revokeObjectURL(url); }
function Select({ label, value, options, onChange }: { label: string; value: string; options: readonly string[]; onChange(value: string): void }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function view(state: string): FinopsCapabilityViewState { if (state === "complete") return "complete"; if (state === "empty") return "empty"; if (state === "stale") return "stale"; if (state === "partial") return "partial"; if (state === "configuration_required") return "configuration_required"; return "failed"; }

export function MarketplaceSpgOfficialDefinitionPanel({ definition }: { readonly definition: MarketplaceSpgOfficialDefinition }) { return <section className={styles.definition} aria-label="Official AWS Marketplace dashboard coverage"><div><span>Authoritative AWS catalog</span><strong>{definition.documentedTabCount} tabs · {definition.documentedVisualAreaCount} documented visual areas</strong><small>Manifest pinned at {definition.source.commit.slice(0, 12)} · SHA-256 {definition.source.sha256.slice(0, 16)}… · QuickSight controls are {definition.source.quickSightControlInventory.toLocaleLowerCase().replaceAll("_", " ")}.</small></div><nav aria-label="Marketplace official dashboard tabs">{definition.tabs.map((tab) => <a href={`#marketplace-${tab.id}`} key={tab.id}>{tab.label}<small>{tab.areas.length} areas</small></a>)}</nav><details><summary>Inspect documented-area support</summary><div className={styles.coverageGrid}>{definition.tabs.map((tab) => <section key={tab.id}><h4>{tab.label}</h4><ul>{tab.areas.map((area) => <li key={area.name}><span className={styles[area.support.toLocaleLowerCase()]}>{area.support}</span><strong>{area.name}</strong>{"limitation" in area ? <small>{area.limitation}</small> : null}</li>)}</ul></section>)}</div></details><p>Frozen source coverage remains visible without a provider report; unpublished QuickSight counts and geometry are not inferred.</p></section>; }

function SpendRanking({ title, items }: { title: string; items: readonly RankedSpend[] }) { return <section className={styles.miniPanel}><h4>{title}</h4>{items.length === 0 ? <p>No accepted rows in the current filter.</p> : <ol>{items.slice(0, 8).map((item) => <li key={`${item.key}:${item.currency}`}><span>{item.key}</span><strong>{money(item.billedAmountMicros, item.currency)}</strong><small>{item.rowCount} CUR2 rows</small></li>)}</ol>}</section>; }
function CountSummary({ title, items }: { title: string; items: readonly { key: string; count: number }[] }) { const maximum = Math.max(1, ...items.map((item) => item.count)); return <section className={styles.miniPanel}><h4>{title}</h4>{items.length === 0 ? <p>No accepted evidence in the current filter.</p> : <ul className={styles.countBars}>{items.map((item) => <li key={item.key}><span>{item.key.replaceAll("_", " ")}</span><i><b style={{ width: `${item.count / maximum * 100}%` }} /></i><strong>{item.count}</strong></li>)}</ul>}</section>; }

export function MarketplaceSpgReportView({ report, filters, onFiltersChange }: { report: MarketplaceSpgReport; filters: Filters; onFiltersChange(filters: Filters): void }) {
  const set = (key: keyof Filters, value: string) => onFiltersChange({ ...filters, [key]: value }); const max = Math.max(1, ...report.dashboard.trends.map((point) => Math.abs(Number(BigInt(point.billedAmountMicros) / BigInt(1_000_000)))));
  return <section className={styles.root} aria-label="AWS Marketplace Single Pane of Glass">
    <div className={styles.notice}><strong>Two evidence planes, never conflated.</strong> Realized spend and usage come only from the active reconciled CUR2 generation. Agreements, accepted terms, entitlements, licenses, grants, and expiration are Marketplace control-plane facts; known agreement commitments are not invoices or realized spend.</div>
    {report.sourceState === "partial" ? <div role="status" className={styles.warning}>A newer incomplete collection is disclosed while the previous complete accepted head remains visible.</div> : null}
    {Object.values(report.dashboard.projectionTruncation).some(Boolean) ? <div role="status" className={styles.warning}>High-cardinality summary output was deterministically bounded. Refine the filters to inspect omitted aggregate values.</div> : null}
    <MarketplaceSpgOfficialDefinitionPanel definition={report.officialDefinition} />
    <section className={styles.filters} aria-label="Marketplace procurement filters"><Select label="Account" value={filters.accountId} options={report.dashboard.filterOptions.accounts} onChange={(v) => set("accountId", v)} /><Select label="Product" value={filters.product} options={report.dashboard.filterOptions.products} onChange={(v) => set("product", v)} /><Select label="Seller" value={filters.seller} options={report.dashboard.filterOptions.sellers} onChange={(v) => set("seller", v)} /><Select label="Currency" value={filters.currency} options={report.dashboard.filterOptions.currencies} onChange={(v) => set("currency", v)} /><Select label="Billing period" value={filters.billingPeriod} options={report.dashboard.filterOptions.periods} onChange={(v) => set("billingPeriod", v)} /><Select label="Agreement status" value={filters.agreementStatus} options={["ACTIVE","ARCHIVED","CANCELLED","EXPIRED","RENEWED","REPLACED","TERMINATED"]} onChange={(v) => set("agreementStatus", v)} /><Select label="Expiration" value={filters.expirationState} options={["EXPIRING_30_DAYS","EXPIRING_60_DAYS","EXPIRING_90_DAYS","ACTIVE_BEYOND_90_DAYS","EXPIRED","NO_END_DATE"]} onChange={(v) => set("expirationState", v)} /><Select label="License status" value={filters.licenseStatus} options={["AVAILABLE","PENDING_AVAILABLE","DEACTIVATED","SUSPENDED","EXPIRED","PENDING_DELETE","DELETED"]} onChange={(v) => set("licenseStatus", v)} /><button type="button" onClick={() => onFiltersChange(EMPTY)}>Clear filters</button></section>
    <header className={styles.sectionTitle} id="marketplace-spend-summary"><span>Official tab 1</span><h2>Spend Summary</h2><p>Reconciled Marketplace CUR2 evidence; currencies remain separate.</p></header>
    <section className={styles.cards} aria-label="Marketplace procurement summary"><article><span>Agreements</span><strong>{report.dashboard.counts.agreements}</strong><small>{report.dashboard.counts.expiringWithin90Days} expire within 90 days</small></article><article><span>Received licenses</span><strong>{report.dashboard.counts.licenses}</strong><small>{report.dashboard.counts.grants} grants · {report.dashboard.counts.activeGrants} active</small></article>{report.dashboard.summaries.map((item) => <article key={item.currency}><span>Reconciled billed spend</span><strong>{money(item.billedAmountMicros, item.currency)}</strong><small>{item.rowCount} CUR2 rows · currencies separate</small></article>)}</section>
    <section className={styles.panel}><header><h3>Marketplace spend and usage trend</h3><span>CUR2 only · signed exact micro-units</span></header><div className={styles.trend} role="img" aria-label="Marketplace billed spend by period and currency">{report.dashboard.trends.map((point) => { const value = Math.abs(Number(BigInt(point.billedAmountMicros) / BigInt(1_000_000))); return <div key={`${point.billingPeriod}:${point.currency}`} title={`${point.billingPeriod}: ${money(point.billedAmountMicros, point.currency)}`}><i style={{ height: `${Math.max(4, value / max * 100)}%` }} /><small>{point.billingPeriod}<br />{point.currency}</small></div>; })}</div></section>
    <section className={styles.rankings} aria-label="Marketplace spend rankings"><SpendRanking title="Cumulative spend by seller" items={report.dashboard.spendBySeller} /><SpendRanking title="Cumulative spend by product" items={report.dashboard.spendByProduct} /><SpendRanking title="Spend by AWS account" items={report.dashboard.spendByAccount} /></section>
    <header className={styles.sectionTitle} id="marketplace-marketplace-agreements"><span>Official tab 5</span><h2>Marketplace Agreements</h2><p>Control-plane agreement facts and lifecycle commitment are kept apart from realized spend.</p></header>
    <section className={styles.two}><CountSummary title="Active agreement count by deployment status" items={report.dashboard.agreementDeployment.map((item) => ({ key: item.status, count: item.activeAgreementCount }))} /><section className={styles.miniPanel}><h4>Active agreement value by deployment status</h4><ul className={styles.moneyList}>{report.dashboard.agreementDeployment.flatMap((item) => item.lifecycleCommitments.map((commitment) => <li key={`${item.status}:${commitment.currency}`}><span>{item.status.replaceAll("_", " ")}</span><strong>{money(commitment.amountMicros, commitment.currency)}</strong><small>Known lifecycle commitment, not spend</small></li>))}</ul>{report.dashboard.agreementDeployment.every((item) => item.lifecycleCommitments.length === 0) ? <p>No commitment evidence supplied.</p> : null}</section></section>
    <section className={styles.panel}><header><h3>Agreement charges by month</h3><span>Buyer agreement charge evidence · not CUR2 spend</span></header><div className={styles.chargeSeries}>{report.dashboard.agreementChargesByMonth.length === 0 ? <p>No dated agreement charges supplied.</p> : report.dashboard.agreementChargesByMonth.map((item) => <div key={`${item.month}:${item.currency}`}><span>{item.month}</span><strong>{money(item.amountMicros, item.currency)}</strong></div>)}</div></section>
    <section className={styles.panel}><header><h3>Agreements, offers, terms and renewal</h3><span>{report.dashboard.counts.agreements}{report.dashboard.agreementsTruncated ? "+" : ""} agreements</span></header><div className={styles.scroll} role="region" tabIndex={0} aria-label="Marketplace agreement drilldown"><table><thead><tr><th>Product / seller</th><th>Account / agreement</th><th>Offer</th><th>Status / expiration</th><th>Terms and commitment</th><th>Entitlements / deployment</th></tr></thead><tbody>{report.dashboard.agreements.map((row) => <tr key={row.agreementId}><td>{row.product?.productName ?? row.productId ?? "Metadata unavailable"}<small>{row.product?.sellerDisplayName ?? "Seller unavailable"}</small></td><td>{row.sourceAccountId}<small>{row.agreementId}</small></td><td>{row.offerId ?? "Not supplied"}<small>Public/private type not proven</small></td><td>{row.status}<small>{row.expirationState.replaceAll("_", " ")} · {row.endAt ?? "No end date"}</small></td><td>{row.terms.map((term) => term.type.replaceAll("_", " ")).join(", ") || "None supplied"}<small>{row.estimatedCharges === null ? "No known commitment" : `${money(row.estimatedCharges.amountMicros, row.estimatedCharges.currency)} known lifecycle commitment`}</small></td><td>{row.entitlements.length} agreement entitlements<small>{row.product?.deployedOnAws ?? "Deployment metadata unavailable"} · {row.product?.fulfillmentTypes.join(", ") || "Fulfillment unavailable"}</small></td></tr>)}</tbody></table></div></section>
    <header className={styles.sectionTitle} id="marketplace-bedrock-3p-foundational-model-spend"><span>Official tab 3</span><h2>Bedrock 3P Foundational Model Spend</h2><p>Unavailable from accepted evidence: product names are not used to infer third-party foundational-model classification or usage units.</p></header>
    <section className={styles.unavailable} role="status"><strong>Authoritative classification required</strong><span>The current CUR2 projection can prove Marketplace spend, seller, product and row counts, but not whether a row is a Bedrock third-party model. This tab remains visibly unavailable until an approved classification source is added.</span></section>
    <header className={styles.sectionTitle} id="marketplace-granted-entitled-licenses"><span>Official tab 4</span><h2>Granted and Entitled Licenses</h2><p>License Manager organization evidence, validity, entitlements and sharing grants.</p></header>
    <section className={styles.rankings}><CountSummary title="Upcoming contract expirations" items={report.dashboard.licenseExpirationSummary.map((item) => ({ key: item.state, count: item.count }))} /><CountSummary title="License status" items={report.dashboard.licenseStatusSummary.map((item) => ({ key: item.status, count: item.count }))} /><CountSummary title="License summary by product" items={report.dashboard.licenseProductSummary.map((item) => ({ key: item.productName, count: item.count }))} /></section>
    <section className={styles.two}><section className={styles.panel}><header><h3>Received licenses and entitlements</h3><span>License Manager</span></header><div className={styles.scroll}><table><thead><tr><th>Product</th><th>Beneficiary</th><th>Status / validity</th><th>Entitlements</th></tr></thead><tbody>{report.dashboard.licenses.map((row) => <tr key={row.licenseArn}><td>{row.productName}<small>{row.licenseName}</small></td><td>{row.beneficiaryAccountId}</td><td>{row.status}<small>{row.validity?.endAt ?? "No validity end supplied"}</small></td><td>{row.entitlements.map((item) => `${item.name}: ${item.value ?? item.maxCount ?? "unspecified"} ${item.unit}`).join(", ") || "None supplied"}</td></tr>)}</tbody></table></div></section><section className={styles.panel}><header><h3>License sharing grants</h3><span>{report.dashboard.counts.grants} matched</span></header><div className={styles.scroll}><table><thead><tr><th>Beneficiary</th><th>Status</th><th>Operations</th><th>Grant evidence</th></tr></thead><tbody>{report.dashboard.grants.map((row) => <tr key={row.grantArn}><td>{row.granteeAccountId}</td><td>{row.status}</td><td>{row.operations.join(", ")}</td><td>{row.grantArn}</td></tr>)}</tbody></table></div></section></section>
    <header className={styles.sectionTitle} id="marketplace-spend-deep-dive"><span>Official tab 2</span><h2>Spend Deep Dive</h2><p>Invoice, account, product, seller and charge-category lineage from visible CUR2 rows.</p></header>
    <section className={styles.panel}><header><h3>Invoice, product and charge-category drilldown</h3><button type="button" onClick={() => exportSpend(report.dashboard.spendRows)}>Export visible CUR2 rows</button></header><div className={styles.scroll} role="region" tabIndex={0} aria-label="Marketplace realized spend drilldown"><table><thead><tr><th>Period / invoice</th><th>Account</th><th>Product / seller</th><th>Category</th><th>Billed</th><th>Amortized</th></tr></thead><tbody>{report.dashboard.spendRows.map((row, index) => <tr key={`${row.billingPeriod}:${row.linkedAccountId}:${row.invoiceId ?? index}`}><td>{row.billingPeriod}<small>{row.invoiceId ?? "Invoice not supplied"}</small></td><td>{row.linkedAccountId}</td><td>{row.productName}<small>{row.sellerName} · {row.productCode ?? "No product code"}</small></td><td>{row.chargeCategory}</td><td>{money(row.billedAmountMicros, row.currency)}</td><td>{money(row.amortizedAmountMicros, row.currency)}</td></tr>)}</tbody></table></div>{report.dashboard.spendRowsTruncated ? <p>Only the first 500 filtered rows are rendered. Refine filters before export.</p> : null}</section>
    <details className={styles.evidence}><summary>Provenance, history, source gaps and privacy boundary</summary><dl><div><dt>Accepted generation</dt><dd>{report.provenance.activeGenerationId ?? "No complete accepted head"}</dd></div><div><dt>Capture</dt><dd>{report.provenance.captureId}</dd></div><div><dt>Data through</dt><dd>{report.freshness.dataThroughAt} · {report.freshness.ageHours} hours old</dd></div><div><dt>Organization coverage</dt><dd>{report.source.organizationCoverage}</dd></div><div><dt>CUR2 generation</dt><dd>{report.provenance.cur2GenerationId ?? "Not configured"}</dd></div><div><dt>Collector adapter</dt><dd>{report.collection.reason}</dd></div></dl><h4>Retained immutable history</h4><ul>{report.history.map((point) => <li key={point.generationId}>{point.capturedAt}: {point.state} · {point.agreementCount} agreements · {point.licenseCount} licenses · {point.spendRowCount} CUR2 rows</li>)}</ul><h4>Unsupported official dimensions</h4><ul>{report.unsupportedOfficialViews.map((item) => <li key={item}>{item}</li>)}</ul><h4>Evidence limitations</h4><ul>{report.source.limitations.map((item) => <li key={item}>{item}</li>)}</ul></details>
  </section>;
}

export function FinopsMarketplaceSpgDashboard({ connectionId, dashboard }: { connectionId: string | null; dashboard: FinopsDashboardCatalogEntry }) {
  const [filters, setFilters] = useState<Filters>(EMPTY); const [state, setState] = useState<{ loading: boolean; report: MarketplaceSpgReport | null; error: string | null; officialDefinition: MarketplaceSpgOfficialDefinition }>({ loading: true, report: null, error: null, officialDefinition: MARKETPLACE_SPG_OFFICIAL_DEFINITION });
  useEffect(() => { if (connectionId === null) return; const controller = new AbortController(); const query = new URLSearchParams({ connectionId }); for (const [key, value] of Object.entries(filters)) if (value) query.set(key, value); const frame = window.requestAnimationFrame(() => { setState((current) => ({ loading: true, report: null, error: null, officialDefinition: current.officialDefinition })); void fetch(`/api/v1/finops/marketplace-spg?${query}`, { signal: controller.signal, credentials: "same-origin" }).then(async (response) => { if (!response.ok) throw new Error("Marketplace evidence request failed"); return response.json() as Promise<MarketplaceSpgReport | MarketplaceSpgConfigurationEnvelope>; }).then((body) => { if (!hasPinnedOfficialDefinition(body.officialDefinition)) throw new Error("Sutra returned an unrecognized Marketplace official definition"); if ("dashboard" in body && body.dashboard === null) setState({ loading: false, report: null, error: null, officialDefinition: body.officialDefinition }); else setState({ loading: false, report: body as MarketplaceSpgReport, error: null, officialDefinition: body.officialDefinition }); }, (error: unknown) => { if (!controller.signal.aborted) setState((current) => ({ loading: false, report: null, error: error instanceof Error ? error.message : "Marketplace evidence request failed", officialDefinition: current.officialDefinition })); }); }); return () => { window.cancelAnimationFrame(frame); controller.abort(); }; }, [connectionId, filters]);
  const shown = connectionId === null ? { state: "configuration_required" as const, title: "Connect AWS to configure Marketplace intelligence", detail: "An active commercial AWS trust-role connection is required." } : state.error ? { state: "failed" as const, title: "Marketplace evidence could not be verified", detail: state.error } : state.loading ? { state: "loading" as const, title: "Loading Marketplace procurement evidence", detail: "Reading the immutable tenant-scoped accepted generation." } : state.report === null ? { state: "configuration_required" as const, title: "Marketplace collection is not configured", detail: "Deploy and bind the signed broker adapter for buyer Agreements, License Manager, organization coverage, and active reconciled CUR2." } : { state: view(state.report.sourceState), title: "AWS Marketplace Single Pane of Glass", detail: "Unified procurement and FinOps views with source evidence kept separate." };
  const report = state.report; const evidence = report === null ? null : { sourceLabel: "Marketplace buyer APIs + License Manager + active reconciled CUR2", collectedAt: report.history[0]?.capturedAt ?? report.freshness.dataThroughAt, dataThroughAt: report.freshness.dataThroughAt, freshnessAgeHours: report.freshness.ageHours, freshnessSlaHours: 48, acceptedRecords: report.dashboard.counts.agreements + report.dashboard.counts.licenses + report.dashboard.counts.grants + report.dashboard.counts.spendRows, rejectedRecords: null, generationId: report.provenance.generationId, contentSha256: report.provenance.contentSha256, limitations: [...report.source.limitations, ...report.unsupportedOfficialViews] };
  return <FinopsCapabilityShell dashboard={dashboard} state={shown.state} stateTitle={shown.title} stateDetail={shown.detail} evidence={evidence}>{report === null ? <MarketplaceSpgOfficialDefinitionPanel definition={state.officialDefinition} /> : <MarketplaceSpgReportView report={report} filters={filters} onFiltersChange={setFilters} />}</FinopsCapabilityShell>;
}
