import { evaluateSecurityControls, summarizeFindings } from "./security-controls.ts";
import type {
  AwsAccount,
  Customer,
  NormalizedResource,
  SecurityGroup,
  SecurityGroupRule,
  SecurityInventory,
} from "./types.ts";

export const DEMO_DATA_NOTICE =
  "Fictional demonstration data only. Account IDs, names, ARNs, contacts, and findings do not represent real customers or live AWS observations.";

const OBSERVED_AT = "2026-07-15T06:30:00.000Z";

export const customers: readonly Customer[] = [
  {
    id: "cust-northstar",
    name: "Northstar Retail (Demo)",
    slug: "northstar-retail-demo",
    status: "active",
    plan: "enterprise",
    primaryContact: "demo.northstar@example.invalid",
    accountIds: ["acct-northstar-prod", "acct-northstar-dev"],
    createdAt: "2026-04-03T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "cust-bluepeak",
    name: "Bluepeak Health (Demo)",
    slug: "bluepeak-health-demo",
    status: "active",
    plan: "managed",
    primaryContact: "demo.bluepeak@example.invalid",
    accountIds: ["acct-bluepeak-prod", "acct-bluepeak-sandbox"],
    createdAt: "2026-05-12T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "cust-harbor",
    name: "Harbor Analytics (Demo)",
    slug: "harbor-analytics-demo",
    status: "trial",
    plan: "foundation",
    primaryContact: "demo.harbor@example.invalid",
    accountIds: ["acct-harbor-prod"],
    createdAt: "2026-06-22T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "cust-evergreen",
    name: "Evergreen Finance (Demo)",
    slug: "evergreen-finance-demo",
    status: "active",
    plan: "managed",
    primaryContact: "demo.evergreen@example.invalid",
    accountIds: ["acct-evergreen-prod"],
    createdAt: "2026-03-18T09:00:00.000Z",
    isDemo: true,
  },
];

export const awsAccounts: readonly AwsAccount[] = [
  {
    id: "acct-northstar-prod",
    customerId: "cust-northstar",
    awsAccountId: "111122223333",
    name: "Retail production (Demo)",
    environment: "production",
    regions: ["us-east-1", "us-west-2"],
    trustRole: {
      roleArn: "arn:aws:iam::111122223333:role/MspCmdbReadOnlyDemoRole",
      externalIdConfigured: true,
      permissionsMode: "read-only",
      status: "connected",
      lastValidatedAt: "2026-07-15T06:25:00.000Z",
    },
    securitySignals: {
      rootMfa: "enabled",
      passwordPolicy: "enabled",
      cloudTrail: { status: "enabled", coveredRegions: ["us-east-1", "us-west-2"] },
      guardDuty: { status: "partial", coveredRegions: ["us-east-1"] },
      observedAt: OBSERVED_AT,
    },
    lastSyncedAt: OBSERVED_AT,
    isDemo: true,
  },
  {
    id: "acct-northstar-dev",
    customerId: "cust-northstar",
    awsAccountId: "111122223334",
    name: "Retail development (Demo)",
    environment: "development",
    regions: ["us-east-1"],
    trustRole: {
      roleArn: "arn:aws:iam::111122223334:role/MspCmdbReadOnlyDemoRole",
      externalIdConfigured: true,
      permissionsMode: "read-only",
      status: "needs-attention",
      lastValidatedAt: "2026-07-15T06:20:00.000Z",
    },
    securitySignals: {
      rootMfa: "disabled",
      passwordPolicy: "disabled",
      cloudTrail: { status: "disabled", coveredRegions: [] },
      guardDuty: { status: "disabled", coveredRegions: [] },
      observedAt: OBSERVED_AT,
    },
    lastSyncedAt: OBSERVED_AT,
    isDemo: true,
  },
  {
    id: "acct-bluepeak-prod",
    customerId: "cust-bluepeak",
    awsAccountId: "222233334444",
    name: "Clinical production (Demo)",
    environment: "production",
    regions: ["us-east-1"],
    trustRole: {
      roleArn: "arn:aws:iam::222233334444:role/MspCmdbReadOnlyDemoRole",
      externalIdConfigured: true,
      permissionsMode: "read-only",
      status: "connected",
      lastValidatedAt: "2026-07-15T06:24:00.000Z",
    },
    securitySignals: {
      rootMfa: "enabled",
      passwordPolicy: "enabled",
      cloudTrail: { status: "enabled", coveredRegions: ["us-east-1"] },
      guardDuty: { status: "enabled", coveredRegions: ["us-east-1"] },
      observedAt: OBSERVED_AT,
    },
    lastSyncedAt: OBSERVED_AT,
    isDemo: true,
  },
  {
    id: "acct-bluepeak-sandbox",
    customerId: "cust-bluepeak",
    awsAccountId: "222233334445",
    name: "Research sandbox (Demo)",
    environment: "sandbox",
    regions: ["us-east-1"],
    trustRole: {
      roleArn: "arn:aws:iam::222233334445:role/MspCmdbReadOnlyDemoRole",
      externalIdConfigured: true,
      permissionsMode: "read-only",
      status: "connected",
      lastValidatedAt: "2026-07-15T06:22:00.000Z",
    },
    securitySignals: {
      rootMfa: "enabled",
      passwordPolicy: "disabled",
      cloudTrail: { status: "enabled", coveredRegions: ["us-east-1"] },
      guardDuty: { status: "disabled", coveredRegions: [] },
      observedAt: OBSERVED_AT,
    },
    lastSyncedAt: OBSERVED_AT,
    isDemo: true,
  },
  {
    id: "acct-harbor-prod",
    customerId: "cust-harbor",
    awsAccountId: "333344445555",
    name: "Analytics production (Demo)",
    environment: "production",
    regions: ["eu-west-1", "eu-central-1"],
    trustRole: {
      roleArn: "arn:aws:iam::333344445555:role/MspCmdbReadOnlyDemoRole",
      externalIdConfigured: true,
      permissionsMode: "read-only",
      status: "connected",
      lastValidatedAt: "2026-07-15T06:21:00.000Z",
    },
    securitySignals: {
      rootMfa: "disabled",
      passwordPolicy: "enabled",
      cloudTrail: { status: "disabled", coveredRegions: [] },
      guardDuty: { status: "partial", coveredRegions: ["eu-west-1"] },
      observedAt: OBSERVED_AT,
    },
    lastSyncedAt: OBSERVED_AT,
    isDemo: true,
  },
  {
    id: "acct-evergreen-prod",
    customerId: "cust-evergreen",
    awsAccountId: "444455556666",
    name: "Payments production (Demo)",
    environment: "production",
    regions: ["ap-south-1"],
    trustRole: {
      roleArn: "arn:aws:iam::444455556666:role/MspCmdbReadOnlyDemoRole",
      externalIdConfigured: true,
      permissionsMode: "read-only",
      status: "connected",
      lastValidatedAt: "2026-07-15T06:23:00.000Z",
    },
    securitySignals: {
      rootMfa: "enabled",
      passwordPolicy: "unknown",
      cloudTrail: { status: "enabled", coveredRegions: ["ap-south-1"] },
      guardDuty: { status: "enabled", coveredRegions: ["ap-south-1"] },
      observedAt: OBSERVED_AT,
    },
    lastSyncedAt: OBSERVED_AT,
    isDemo: true,
  },
];

export const resources: readonly NormalizedResource[] = [
  {
    id: "res-northstar-catalog",
    customerId: "cust-northstar",
    accountId: "acct-northstar-prod",
    arn: "arn:aws:s3:::demo-northstar-public-catalog",
    nativeId: "demo-northstar-public-catalog",
    name: "Public product catalog (Demo)",
    service: "s3",
    resourceType: "s3-bucket",
    region: "us-east-1",
    state: "active",
    tags: { Environment: "production", Owner: "commerce" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      publicAccess: "public",
      blockPublicAccessEnabled: false,
      encryptionEnabled: true,
      versioningEnabled: true,
    },
  },
  {
    id: "res-northstar-data-volume",
    customerId: "cust-northstar",
    accountId: "acct-northstar-prod",
    arn: "arn:aws:ec2:us-east-1:111122223333:volume/vol-demo0001",
    nativeId: "vol-demo0001",
    name: "Orders data volume (Demo)",
    service: "ec2",
    resourceType: "ebs-volume",
    region: "us-east-1",
    state: "in-use",
    tags: { Environment: "production", Owner: "orders" },
    lastSeenAt: OBSERVED_AT,
    configuration: { encrypted: false, kmsKeyId: null, sizeGiB: 500, volumeType: "gp3" },
  },
  {
    id: "res-northstar-web",
    customerId: "cust-northstar",
    accountId: "acct-northstar-prod",
    arn: "arn:aws:ec2:us-east-1:111122223333:instance/i-demo0001",
    nativeId: "i-demo0001",
    name: "Storefront web 01 (Demo)",
    service: "ec2",
    resourceType: "ec2-instance",
    region: "us-east-1",
    state: "running",
    tags: { Environment: "production", Owner: "commerce" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      instanceType: "m7g.large",
      platform: "Amazon Linux 2023",
      publicIpAddress: "198.51.100.10",
      securityGroupIds: ["sg-demo-north-ssh", "sg-demo-north-web"],
    },
  },
  {
    id: "res-northstar-orders-db",
    customerId: "cust-northstar",
    accountId: "acct-northstar-prod",
    arn: "arn:aws:rds:us-east-1:111122223333:db:demo-orders-primary",
    nativeId: "demo-orders-primary",
    name: "Orders primary database (Demo)",
    service: "rds",
    resourceType: "rds-instance",
    region: "us-east-1",
    state: "available",
    tags: { Environment: "production", Owner: "orders" },
    lastSeenAt: OBSERVED_AT,
    configuration: { engine: "postgres", encrypted: true, publiclyAccessible: false, multiAz: true },
  },
  {
    id: "res-northstar-deploy-user",
    customerId: "cust-northstar",
    accountId: "acct-northstar-prod",
    arn: "arn:aws:iam::111122223333:user/demo-deploy-bot",
    nativeId: "demo-deploy-bot",
    name: "Deploy automation user (Demo)",
    service: "iam",
    resourceType: "iam-user",
    region: "global",
    state: "active",
    tags: { Environment: "production", Owner: "platform" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      consoleAccess: false,
      mfaEnabled: null,
      accessKeys: [{ id: "AKIADEMO0001", status: "active", ageDays: 142, lastUsedDaysAgo: 2 }],
    },
  },
  {
    id: "res-northstar-dev-assets",
    customerId: "cust-northstar",
    accountId: "acct-northstar-dev",
    arn: "arn:aws:s3:::demo-northstar-dev-assets",
    nativeId: "demo-northstar-dev-assets",
    name: "Development assets (Demo)",
    service: "s3",
    resourceType: "s3-bucket",
    region: "us-east-1",
    state: "active",
    tags: { Environment: "development", Owner: "engineering" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      publicAccess: "blocked",
      blockPublicAccessEnabled: true,
      encryptionEnabled: true,
      versioningEnabled: false,
    },
  },
  {
    id: "res-northstar-dev-reports-db",
    customerId: "cust-northstar",
    accountId: "acct-northstar-dev",
    arn: "arn:aws:rds:us-east-1:111122223334:db:demo-reports-dev",
    nativeId: "demo-reports-dev",
    name: "Reports development database (Demo)",
    service: "rds",
    resourceType: "rds-instance",
    region: "us-east-1",
    state: "available",
    tags: { Environment: "development", Owner: "analytics" },
    lastSeenAt: OBSERVED_AT,
    configuration: { engine: "mysql", encrypted: false, publiclyAccessible: true, multiAz: false },
  },
  {
    id: "res-northstar-importer",
    customerId: "cust-northstar",
    accountId: "acct-northstar-dev",
    arn: "arn:aws:lambda:us-east-1:111122223334:function:demo-catalog-importer",
    nativeId: "demo-catalog-importer",
    name: "Catalog importer (Demo)",
    service: "lambda",
    resourceType: "lambda-function",
    region: "us-east-1",
    state: "active",
    tags: { Environment: "development", Owner: "commerce" },
    lastSeenAt: OBSERVED_AT,
    configuration: { runtime: "nodejs22.x", publicFunctionUrl: false },
  },
  {
    id: "res-bluepeak-records",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-prod",
    arn: "arn:aws:s3:::demo-bluepeak-clinical-records",
    nativeId: "demo-bluepeak-clinical-records",
    name: "Clinical records archive (Demo)",
    service: "s3",
    resourceType: "s3-bucket",
    region: "us-east-1",
    state: "active",
    tags: { Environment: "production", DataClass: "restricted" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      publicAccess: "blocked",
      blockPublicAccessEnabled: true,
      encryptionEnabled: true,
      versioningEnabled: true,
    },
  },
  {
    id: "res-bluepeak-app-volume",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-prod",
    arn: "arn:aws:ec2:us-east-1:222233334444:volume/vol-demo0002",
    nativeId: "vol-demo0002",
    name: "Clinical app volume (Demo)",
    service: "ec2",
    resourceType: "ebs-volume",
    region: "us-east-1",
    state: "in-use",
    tags: { Environment: "production", Owner: "clinical-app" },
    lastSeenAt: OBSERVED_AT,
    configuration: { encrypted: true, kmsKeyId: "alias/demo-bluepeak-ebs", sizeGiB: 250, volumeType: "gp3" },
  },
  {
    id: "res-bluepeak-clinical-db",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-prod",
    arn: "arn:aws:rds:us-east-1:222233334444:db:demo-clinical-primary",
    nativeId: "demo-clinical-primary",
    name: "Clinical primary database (Demo)",
    service: "rds",
    resourceType: "rds-instance",
    region: "us-east-1",
    state: "available",
    tags: { Environment: "production", DataClass: "restricted" },
    lastSeenAt: OBSERVED_AT,
    configuration: { engine: "aurora-postgresql", encrypted: true, publiclyAccessible: false, multiAz: true },
  },
  {
    id: "res-bluepeak-app",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-prod",
    arn: "arn:aws:ec2:us-east-1:222233334444:instance/i-demo0002",
    nativeId: "i-demo0002",
    name: "Clinical application 01 (Demo)",
    service: "ec2",
    resourceType: "ec2-instance",
    region: "us-east-1",
    state: "running",
    tags: { Environment: "production", Owner: "clinical-app" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      instanceType: "m7i.large",
      platform: "Ubuntu 24.04",
      publicIpAddress: null,
      securityGroupIds: ["sg-demo-bluepeak-app"],
    },
  },
  {
    id: "res-bluepeak-sandbox-share",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-sandbox",
    arn: "arn:aws:s3:::demo-bluepeak-research-share",
    nativeId: "demo-bluepeak-research-share",
    name: "Research exchange bucket (Demo)",
    service: "s3",
    resourceType: "s3-bucket",
    region: "us-east-1",
    state: "active",
    tags: { Environment: "sandbox", Owner: "research" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      publicAccess: "public",
      blockPublicAccessEnabled: false,
      encryptionEnabled: true,
      versioningEnabled: false,
    },
  },
  {
    id: "res-bluepeak-qa-user",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-sandbox",
    arn: "arn:aws:iam::222233334445:user/demo-qa-bot",
    nativeId: "demo-qa-bot",
    name: "QA automation user (Demo)",
    service: "iam",
    resourceType: "iam-user",
    region: "global",
    state: "active",
    tags: { Environment: "sandbox", Owner: "quality" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      consoleAccess: false,
      mfaEnabled: null,
      accessKeys: [{ id: "AKIADEMO0002", status: "active", ageDays: 34, lastUsedDaysAgo: 1 }],
    },
  },
  {
    id: "res-harbor-audit",
    customerId: "cust-harbor",
    accountId: "acct-harbor-prod",
    arn: "arn:aws:s3:::demo-harbor-audit-archive",
    nativeId: "demo-harbor-audit-archive",
    name: "Audit archive (Demo)",
    service: "s3",
    resourceType: "s3-bucket",
    region: "eu-west-1",
    state: "active",
    tags: { Environment: "production", Owner: "security" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      publicAccess: "blocked",
      blockPublicAccessEnabled: true,
      encryptionEnabled: true,
      versioningEnabled: true,
    },
  },
  {
    id: "res-harbor-legacy-volume",
    customerId: "cust-harbor",
    accountId: "acct-harbor-prod",
    arn: "arn:aws:ec2:eu-west-1:333344445555:volume/vol-demo0003",
    nativeId: "vol-demo0003",
    name: "Legacy analytics volume (Demo)",
    service: "ec2",
    resourceType: "ebs-volume",
    region: "eu-west-1",
    state: "available",
    tags: { Environment: "production", Owner: "analytics" },
    lastSeenAt: OBSERVED_AT,
    configuration: { encrypted: false, kmsKeyId: null, sizeGiB: 1000, volumeType: "gp2" },
  },
  {
    id: "res-harbor-alb",
    customerId: "cust-harbor",
    accountId: "acct-harbor-prod",
    arn: "arn:aws:elasticloadbalancing:eu-west-1:333344445555:loadbalancer/app/demo-analytics/0003",
    nativeId: "demo-analytics",
    name: "Analytics gateway (Demo)",
    service: "elasticloadbalancing",
    resourceType: "load-balancer",
    region: "eu-west-1",
    state: "active",
    tags: { Environment: "production", Owner: "platform" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      scheme: "internet-facing",
      loadBalancerType: "application",
      securityGroupIds: ["sg-demo-harbor-web"],
    },
  },
  {
    id: "res-harbor-analytics-db",
    customerId: "cust-harbor",
    accountId: "acct-harbor-prod",
    arn: "arn:aws:rds:eu-west-1:333344445555:db:demo-analytics",
    nativeId: "demo-analytics",
    name: "Analytics database (Demo)",
    service: "rds",
    resourceType: "rds-instance",
    region: "eu-west-1",
    state: "available",
    tags: { Environment: "production", Owner: "analytics" },
    lastSeenAt: OBSERVED_AT,
    configuration: { engine: "postgres", encrypted: true, publiclyAccessible: true, multiAz: false },
  },
  {
    id: "res-evergreen-vpc",
    customerId: "cust-evergreen",
    accountId: "acct-evergreen-prod",
    arn: "arn:aws:ec2:ap-south-1:444455556666:vpc/vpc-demo0004",
    nativeId: "vpc-demo0004",
    name: "Payments production VPC (Demo)",
    service: "vpc",
    resourceType: "vpc",
    region: "ap-south-1",
    state: "available",
    tags: { Environment: "production", Owner: "platform" },
    lastSeenAt: OBSERVED_AT,
    configuration: { cidrBlock: "10.40.0.0/16", isDefault: false },
  },
  {
    id: "res-evergreen-sync-user",
    customerId: "cust-evergreen",
    accountId: "acct-evergreen-prod",
    arn: "arn:aws:iam::444455556666:user/demo-settlement-sync",
    nativeId: "demo-settlement-sync",
    name: "Settlement sync user (Demo)",
    service: "iam",
    resourceType: "iam-user",
    region: "global",
    state: "active",
    tags: { Environment: "production", Owner: "payments" },
    lastSeenAt: OBSERVED_AT,
    configuration: {
      consoleAccess: false,
      mfaEnabled: null,
      accessKeys: [{ id: "AKIADEMO0004", status: "active", ageDays: 188, lastUsedDaysAgo: 12 }],
    },
  },
];

const allEgress: SecurityGroupRule = {
  id: "rule-egress-all",
  protocol: "-1",
  fromPort: null,
  toPort: null,
  ipv4Ranges: ["0.0.0.0/0"],
  ipv6Ranges: [],
  sourceSecurityGroupIds: [],
  description: "Default outbound access",
};

export const securityGroups: readonly SecurityGroup[] = [
  {
    id: "secgrp-northstar-ssh",
    customerId: "cust-northstar",
    accountId: "acct-northstar-prod",
    groupId: "sg-demo-north-ssh",
    name: "storefront-admin-demo",
    description: "Demo administration path",
    region: "us-east-1",
    vpcId: "vpc-demo0001",
    isDefault: false,
    ingress: [
      {
        id: "rule-northstar-open-ssh",
        protocol: "tcp",
        fromPort: 22,
        toPort: 22,
        ipv4Ranges: ["0.0.0.0/0"],
        ipv6Ranges: [],
        sourceSecurityGroupIds: [],
        description: "Demo rule intentionally open for control evaluation",
      },
    ],
    egress: [allEgress],
    lastSeenAt: OBSERVED_AT,
  },
  {
    id: "secgrp-northstar-web",
    customerId: "cust-northstar",
    accountId: "acct-northstar-prod",
    groupId: "sg-demo-north-web",
    name: "storefront-web-demo",
    description: "HTTPS ingress",
    region: "us-east-1",
    vpcId: "vpc-demo0001",
    isDefault: false,
    ingress: [
      {
        id: "rule-northstar-https",
        protocol: "tcp",
        fromPort: 443,
        toPort: 443,
        ipv4Ranges: ["0.0.0.0/0"],
        ipv6Ranges: ["::/0"],
        sourceSecurityGroupIds: [],
        description: "Public HTTPS",
      },
    ],
    egress: [allEgress],
    lastSeenAt: OBSERVED_AT,
  },
  {
    id: "secgrp-northstar-default",
    customerId: "cust-northstar",
    accountId: "acct-northstar-dev",
    groupId: "sg-demo-north-default",
    name: "default",
    description: "Default VPC security group",
    region: "us-east-1",
    vpcId: "vpc-demo0002",
    isDefault: true,
    ingress: [
      {
        id: "rule-northstar-default-self",
        protocol: "-1",
        fromPort: null,
        toPort: null,
        ipv4Ranges: [],
        ipv6Ranges: [],
        sourceSecurityGroupIds: ["sg-demo-north-default"],
        description: "Self-referencing default rule",
      },
    ],
    egress: [allEgress],
    lastSeenAt: OBSERVED_AT,
  },
  {
    id: "secgrp-bluepeak-app",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-prod",
    groupId: "sg-demo-bluepeak-app",
    name: "clinical-app-demo",
    description: "Private application ingress",
    region: "us-east-1",
    vpcId: "vpc-demo0003",
    isDefault: false,
    ingress: [
      {
        id: "rule-bluepeak-private-https",
        protocol: "tcp",
        fromPort: 443,
        toPort: 443,
        ipv4Ranges: ["10.30.0.0/16"],
        ipv6Ranges: [],
        sourceSecurityGroupIds: [],
        description: "Private application clients",
      },
    ],
    egress: [allEgress],
    lastSeenAt: OBSERVED_AT,
  },
  {
    id: "secgrp-bluepeak-rdp",
    customerId: "cust-bluepeak",
    accountId: "acct-bluepeak-sandbox",
    groupId: "sg-demo-bluepeak-rdp",
    name: "research-windows-demo",
    description: "Demo Windows administration",
    region: "us-east-1",
    vpcId: "vpc-demo0005",
    isDefault: false,
    ingress: [
      {
        id: "rule-bluepeak-open-rdp",
        protocol: "tcp",
        fromPort: 3389,
        toPort: 3389,
        ipv4Ranges: ["0.0.0.0/0"],
        ipv6Ranges: [],
        sourceSecurityGroupIds: [],
        description: "Demo rule intentionally open for control evaluation",
      },
    ],
    egress: [allEgress],
    lastSeenAt: OBSERVED_AT,
  },
  {
    id: "secgrp-harbor-web",
    customerId: "cust-harbor",
    accountId: "acct-harbor-prod",
    groupId: "sg-demo-harbor-web",
    name: "analytics-gateway-demo",
    description: "Public HTTPS gateway",
    region: "eu-west-1",
    vpcId: "vpc-demo0006",
    isDefault: false,
    ingress: [
      {
        id: "rule-harbor-https",
        protocol: "tcp",
        fromPort: 443,
        toPort: 443,
        ipv4Ranges: ["0.0.0.0/0"],
        ipv6Ranges: ["::/0"],
        sourceSecurityGroupIds: [],
        description: "Public HTTPS",
      },
    ],
    egress: [allEgress],
    lastSeenAt: OBSERVED_AT,
  },
  {
    id: "secgrp-evergreen-default",
    customerId: "cust-evergreen",
    accountId: "acct-evergreen-prod",
    groupId: "sg-demo-evergreen-default",
    name: "default",
    description: "Hardened default security group",
    region: "ap-south-1",
    vpcId: "vpc-demo0004",
    isDefault: true,
    ingress: [],
    egress: [],
    lastSeenAt: OBSERVED_AT,
  },
];

export const demoInventory: SecurityInventory = {
  accounts: awsAccounts,
  resources,
  securityGroups,
};

export const demoFindings = evaluateSecurityControls(demoInventory);
export const demoPostureSummary = summarizeFindings(demoFindings);

// Friendly aliases for consumers that prefer explicit demo-prefixed imports.
export const demoCustomers = customers;
export const demoAwsAccounts = awsAccounts;
export const demoResources = resources;
export const demoSecurityGroups = securityGroups;
export const findings = demoFindings;
export const accounts = awsAccounts;
