import type { ScadPersistenceScope,StoredScadSnapshot } from "../db/finops-scad-allocation-repository.ts";
import { SCAD_BOUNDS,SCAD_CUR2_BASE_COLUMNS,SCAD_CUR2_SPLIT_COLUMNS,SCAD_RUNTIME_S3_READ_IAM_ACTIONS,type ScadCapture,type ScadScope } from "./finops-scad-allocation.ts";
export const SCAD_MATERIALIZATION_JOB_KIND="finops-scad-cur2-daily-materialize";export const SCAD_MATERIALIZATION_INTERVAL_MS=24*60*60*1_000;const WINDOW=/^\d{4}-\d{2}-\d{2}T00:00:00\.000Z$/u;
export interface ScadMaterializationJob{readonly id:string;readonly orgId:string;readonly customerId:string|null;readonly connectionId:string|null;readonly payload:unknown}
export interface ScadMaterializationTarget{readonly scope:ScadScope;readonly exportArn:string;readonly bucket:string;readonly prefix:string;readonly lastAcceptedGenerationId:string|null}
export interface ScadCur2Adapter{collect(request:{readonly schemaVersion:"sutra.scad-materializer-request.v1";readonly scope:ScadScope;readonly exportArn:string;readonly bucket:string;readonly prefix:string;readonly scheduledWindow:string;readonly lastAcceptedGenerationId:string|null;readonly requiredColumns:readonly string[];readonly operations:typeof SCAD_RUNTIME_S3_READ_IAM_ACTIONS;readonly bounds:typeof SCAD_BOUNDS},signal:AbortSignal):Promise<ScadCapture>}
export interface ScadMaterializationDependencies{readonly listTargets:(scope:ScadPersistenceScope)=>Promise<readonly ScadMaterializationTarget[]>;readonly adapter:ScadCur2Adapter;readonly recordCapture:(scope:ScadPersistenceScope,trusted:ScadScope,capture:ScadCapture,nowMs:number)=>Promise<{readonly snapshot:StoredScadSnapshot;readonly becameActive:boolean}>;readonly now?:()=>number}
function invalid():never{throw new Error("finops-scad-materialization-job-invalid")}
export function scadMaterializationWindow(nowMs=Date.now()):string{if(!Number.isSafeInteger(nowMs)||nowMs<0)invalid();return new Date(Math.floor(nowMs/SCAD_MATERIALIZATION_INTERVAL_MS)*SCAD_MATERIALIZATION_INTERVAL_MS).toISOString()}
export function scadMaterializationIdempotencyKey(scope:ScadPersistenceScope,window:string):string{if(!WINDOW.test(window))invalid();return `scad-materialize:${scope.organizationId}:${scope.customerId}:${scope.connectionId}:${window}`}
export async function runScadMaterializationJob(job:ScadMaterializationJob,dependencies:ScadMaterializationDependencies):Promise<{readonly targetCount:number;readonly acceptedHeadCount:number;readonly incompleteCount:number;readonly generations:readonly string[]}>{if(job.customerId===null||job.connectionId===null||typeof job.payload!=="object"||job.payload===null||Array.isArray(job.payload))invalid();const payload=job.payload as Record<string,unknown>;if(Object.keys(payload).length!==1||Object.keys(payload)[0]!=="scheduledWindow"||typeof payload.scheduledWindow!=="string"||!WINDOW.test(payload.scheduledWindow))invalid();const persistence={organizationId:job.orgId,customerId:job.customerId,connectionId:job.connectionId};const targets=await dependencies.listTargets(persistence);if(targets.length>16)invalid();const unique=new Set<string>();for(const target of targets){if(target.scope.orgId!==persistence.organizationId||target.scope.customerId!==persistence.customerId||target.scope.connectionId!==persistence.connectionId||!target.prefix.endsWith("/")||target.prefix.startsWith("/")||!target.exportArn.includes(`:${target.scope.payerAccountIds[0]}:export/`))invalid();const key=`${target.exportArn}:${target.bucket}:${target.prefix}`;if(unique.has(key))invalid();unique.add(key)}const now=dependencies.now??Date.now;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),SCAD_BOUNDS.maximumCaptureDurationMs);const generations:string[]=[];let acceptedHeadCount=0;let incompleteCount=0;let cursor=0;try{const workers=Array.from({length:Math.min(4,targets.length)},async()=>{while(cursor<targets.length){const target=targets[cursor++]!;const capture=await dependencies.adapter.collect({schemaVersion:"sutra.scad-materializer-request.v1",scope:target.scope,exportArn:target.exportArn,bucket:target.bucket,prefix:target.prefix,scheduledWindow:payload.scheduledWindow as string,lastAcceptedGenerationId:target.lastAcceptedGenerationId,requiredColumns:[...SCAD_CUR2_BASE_COLUMNS,...SCAD_CUR2_SPLIT_COLUMNS],operations:SCAD_RUNTIME_S3_READ_IAM_ACTIONS,bounds:SCAD_BOUNDS},controller.signal);if(capture.exportArn!==target.exportArn||capture.destination.bucket!==target.bucket||capture.destination.prefix!==target.prefix)invalid();const recorded=await dependencies.recordCapture(persistence,target.scope,capture,now());generations.push(recorded.snapshot.generationId);if(recorded.becameActive)acceptedHeadCount+=1;if(!recorded.snapshot.snapshot.complete)incompleteCount+=1}});await Promise.all(workers)}finally{clearTimeout(timeout)}return{targetCount:targets.length,acceptedHeadCount,incompleteCount,generations:generations.sort()}}
