/** Permanent, replay-safe runtime boundary for ADD-06 versioned exports. */
import type { JobHandler, RunnableJob } from "./background-job-runner.ts";
import {
  buildKubecostAllocationSnapshot,
  KUBECOST_ALLOCATION_BOUNDS,
  KUBECOST_EXPORT_CONTRACT,
  KUBECOST_RUNTIME_S3_READ_IAM_ACTIONS,
  KUBECOST_SSE_KMS_READ_IAM_ACTIONS,
  KUBECOST_VERSIONED_OBJECT_READ_IAM_ACTIONS,
  type KubecostAllocationCapture,
  type KubecostAllocationScope,
  type KubecostCur2Evidence,
} from "./finops-kubecost-allocation.ts";

const JOB=/^job_[a-f0-9]{32}$/u,REQUEST=/^kur_[a-f0-9]{64}$/u,GENERATION=/^kcg_[a-f0-9]{64}$/u,CAPTURE=/^kubecost_[a-f0-9]{64}$/u,SHA=/^[a-f0-9]{64}$/u;
const WINDOW=/^\d{4}-\d{2}-\d{2}T\d{2}:00:00\.000Z$/u,BUCKET=/^(?!\d+\.\d+\.\d+\.\d+$)(?!.*\.\.)[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/u,KEY=/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u;
const ID=/^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,255}$/u,CONNECTION=/^conn_[a-f0-9]{32}$/u,ACCOUNT=/^\d{12}$/u,CLUSTER=/^[A-Za-z0-9][A-Za-z0-9._:@/+-]{0,255}$/u,PERIOD=/^\d{4}-(?:0[1-9]|1[0-2])$/u,CUR2=/^fbg_[a-f0-9]{64}$/u;
export const KUBECOST_DURABLE_JOB_KIND="finops.kubecost-allocation.collect";
export const KUBECOST_SCHEDULER_CADENCE="rate(6 hours)";
export const KUBECOST_RUNTIME_TIMEOUT_MS=5*60*1_000;
export const KUBECOST_RUNTIME_ACTIVATION_REASON="KUBECOST_SIGNED_VERSIONED_EXPORT_RUNTIME_NOT_REGISTERED";

export interface KubecostRuntimeDestination{readonly bucket:string;readonly prefix:string;readonly expectedBucketOwner:string;readonly requireObjectVersionIds:true;readonly kmsKeyArn:string|null}
export interface KubecostRuntimeContext{readonly scope:KubecostAllocationScope;readonly destination:KubecostRuntimeDestination;readonly activeCur2:KubecostCur2Evidence}
export interface KubecostRuntimeRequest{readonly schemaVersion:"sutra.kubecost-versioned-runtime-request.v1";readonly requestId:string;readonly jobId:string;readonly scheduledWindow:string;readonly scope:KubecostAllocationScope;readonly destination:KubecostRuntimeDestination;readonly activeCur2:KubecostCur2Evidence;readonly activeCur2Sha256:string;readonly exportContract:typeof KUBECOST_EXPORT_CONTRACT;readonly runtimeReadActions:typeof KUBECOST_RUNTIME_S3_READ_IAM_ACTIONS;readonly versionedReadActions:typeof KUBECOST_VERSIONED_OBJECT_READ_IAM_ACTIONS;readonly conditionalKmsActions:typeof KUBECOST_SSE_KMS_READ_IAM_ACTIONS;readonly exporterWriteActions:readonly never[];readonly bounds:typeof KUBECOST_ALLOCATION_BOUNDS;readonly maximumDurationMs:number}
export interface VerifiedKubecostRuntimeResult{readonly capture:KubecostAllocationCapture;readonly verification:{readonly requestBodySha256:string;readonly responseBodySha256:string;readonly brokerKeyId:string}}
export type KubecostRuntimeFailureCode="BROKER_AUTHENTICATION_FAILED"|"BROKER_TIMEOUT"|"BROKER_UNAVAILABLE"|"BROKER_RESPONSE_INVALID"|"SCOPE_REJECTED"|"DESTINATION_REJECTED"|"VERSION_PIN_REJECTED"|"CUR2_LINEAGE_REJECTED"|"EVIDENCE_REJECTED"|"PERSISTENCE_REJECTED"|"INTERNAL_ERROR";
export interface KubecostRuntimeAttempt{readonly requestId:string;readonly jobAttempt:number;readonly state:"CONFIGURATION_REQUIRED"|"WAITING_FIRST_DELIVERY"|"UNKNOWN"|"ERROR"|"EMPTY"|"PARTIAL"|"STALE"|"READY"|"FAILED";readonly generationId:string|null;readonly captureId:string|null;readonly failureCode:KubecostRuntimeFailureCode|null}
export interface KubecostRuntimeAttemptStore{getAttempt(scope:KubecostAllocationScope,requestId:string,jobAttempt:number):Promise<KubecostRuntimeAttempt|null>;recordAttempt(input:{readonly scope:KubecostAllocationScope;readonly requestId:string;readonly jobId:string;readonly jobAttempt:number;readonly scheduledWindow:string;readonly destinationSha256:string;readonly activeCur2Sha256:string;readonly state:KubecostRuntimeAttempt["state"];readonly generationId:string|null;readonly captureId:string|null;readonly requestBodySha256:string|null;readonly responseBodySha256:string|null;readonly brokerKeyId:string|null;readonly failureCode:KubecostRuntimeFailureCode|null;readonly completedAtMs:number}):Promise<KubecostRuntimeAttempt>}
export class KubecostRuntimeError extends Error{constructor(public readonly code:KubecostRuntimeFailureCode|"INVALID_JOB"){super("Kubecost versioned export runtime failed");this.name="KubecostRuntimeError"}}
async function sha(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(part=>part.toString(16).padStart(2,"0")).join("")}
function validWindow(value:string){return WINDOW.test(value)&&Number.isFinite(Date.parse(value))&&new Date(Date.parse(value)).toISOString()===value}
function sortedUnique(values:readonly string[]){return new Set(values).size===values.length&&JSON.stringify(values)===JSON.stringify([...values].sort((a,b)=>a.localeCompare(b,"en-US")))}
function sameStrings(a:readonly string[],b:readonly string[]){return JSON.stringify([...a].sort())===JSON.stringify([...b].sort())}
function validScope(value:KubecostAllocationScope){return ID.test(value.orgId)&&ID.test(value.customerId)&&CONNECTION.test(value.connectionId)&&["aws","aws-us-gov","aws-cn"].includes(value.partition)&&PERIOD.test(value.billingPeriod)&&CUR2.test(value.activeCur2GenerationId)&&value.awsAccountIds.length>=1&&value.awsAccountIds.length<=KUBECOST_ALLOCATION_BOUNDS.maximumAccounts&&value.awsAccountIds.every(item=>ACCOUNT.test(item))&&sortedUnique(value.awsAccountIds)&&value.clusterIds.length>=1&&value.clusterIds.length<=KUBECOST_ALLOCATION_BOUNDS.maximumClusters&&value.clusterIds.every(item=>CLUSTER.test(item))&&sortedUnique(value.clusterIds)}
function validCur2(value:KubecostCur2Evidence,scope:KubecostAllocationScope){return value.source==="AWS_CUR2_ACTIVE_GENERATION"&&value.generationState==="ACTIVE"&&value.generationId===scope.activeCur2GenerationId&&SHA.test(value.manifestSha256)&&value.billingPeriod===scope.billingPeriod&&Number.isFinite(Date.parse(value.dataThroughAtIso))&&new Date(value.dataThroughAtIso).toISOString()===value.dataThroughAtIso&&value.rowsExhausted&&value.payerAccountIds.length>=1&&value.payerAccountIds.every(item=>ACCOUNT.test(item))&&new Set(value.payerAccountIds).size===value.payerAccountIds.length&&sameStrings(value.usageAccountIds,scope.awsAccountIds)&&sameStrings(value.clusterIds,scope.clusterIds)&&value.totals.every(item=>/^[A-Z]{3}$/u.test(item.currency)&&/^-?(?:0|[1-9]\d{0,60})$/u.test(item.amountMicros))&&new Set(value.totals.map(item=>item.currency)).size===value.totals.length}
function immutableContext(value:KubecostRuntimeContext):KubecostRuntimeContext{const scope=Object.freeze({...value.scope,awsAccountIds:Object.freeze([...value.scope.awsAccountIds]),clusterIds:Object.freeze([...value.scope.clusterIds])});const destination=Object.freeze({...value.destination});const activeCur2=Object.freeze({...value.activeCur2,payerAccountIds:Object.freeze([...value.activeCur2.payerAccountIds]),usageAccountIds:Object.freeze([...value.activeCur2.usageAccountIds]),clusterIds:Object.freeze([...value.activeCur2.clusterIds]),totals:Object.freeze(value.activeCur2.totals.map(item=>Object.freeze({...item})))});return Object.freeze({scope,destination,activeCur2})}
function sameScope(a:KubecostAllocationScope,b:KubecostAllocationScope){return a.orgId===b.orgId&&a.customerId===b.customerId&&a.connectionId===b.connectionId&&a.partition===b.partition&&a.billingPeriod===b.billingPeriod&&a.activeCur2GenerationId===b.activeCur2GenerationId&&JSON.stringify(a.awsAccountIds)===JSON.stringify(b.awsAccountIds)&&JSON.stringify(a.clusterIds)===JSON.stringify(b.clusterIds)}
function validDestination(value:KubecostRuntimeDestination){return BUCKET.test(value.bucket)&&/^\d{12}$/u.test(value.expectedBucketOwner)&&value.prefix.length>=2&&value.prefix.length<=1024&&value.prefix.endsWith("/")&&!value.prefix.includes("..")&&!/[\u0000-\u001f\u007f<>]/u.test(value.prefix)&&value.requireObjectVersionIds===true&&(value.kmsKeyArn===null||/^arn:(aws|aws-us-gov|aws-cn):kms:[a-z0-9-]+:\d{12}:key\/[a-f0-9-]{36}$/u.test(value.kmsKeyArn))}
function sameDestination(capture:KubecostAllocationCapture,destination:KubecostRuntimeDestination){return capture.destination.bucket===destination.bucket&&capture.destination.prefix===destination.prefix}
function completeCandidate(capture:KubecostAllocationCapture){const c=capture.coverage;return c.configured&&c.deliveryObserved&&c.runtimeS3PermissionsValidated&&c.status==="SUCCEEDED"&&c.rowsExhausted&&c.failedObjectCount===0&&c.expectedObjectCount===c.processedObjectCount&&JSON.stringify([...c.expectedClusterIds].sort())===JSON.stringify([...c.capturedClusterIds].sort())}
function parseJob(job:RunnableJob){if(job.kind!==KUBECOST_DURABLE_JOB_KIND||job.customerId===null||job.connectionId===null||!JOB.test(job.id)||!Number.isSafeInteger(job.attempt)||job.attempt<1||job.attempt>5||job.maxAttempts!==5||typeof job.payload!=="object"||job.payload===null||Array.isArray(job.payload))throw new KubecostRuntimeError("INVALID_JOB");const value=job.payload as Record<string,unknown>;if(Object.keys(value).length!==1||typeof value.scheduledWindow!=="string"||!validWindow(value.scheduledWindow))throw new KubecostRuntimeError("INVALID_JOB");return value.scheduledWindow}
function sanitized(error:unknown):KubecostRuntimeFailureCode{return error instanceof KubecostRuntimeError&&error.code!=="INVALID_JOB"?error.code:"INTERNAL_ERROR"}

export async function scheduleKubecostCollections(input:{readonly scheduledWindow:string;readonly loadEligibleContexts:()=>Promise<readonly KubecostRuntimeContext[]>;readonly enqueue:(value:{readonly orgId:string;readonly customerId:string;readonly connectionId:string;readonly kind:string;readonly payload:{readonly scheduledWindow:string};readonly maxAttempts:5;readonly idempotencyKey:string})=>Promise<unknown>}){if(!validWindow(input.scheduledWindow))throw new KubecostRuntimeError("INVALID_JOB");const contexts=await input.loadEligibleContexts();if(contexts.length>10_000)throw new KubecostRuntimeError("SCOPE_REJECTED");const seen=new Set<string>();for(const context of [...contexts].sort((a,b)=>a.scope.connectionId.localeCompare(b.scope.connectionId))){if(!validScope(context.scope)||!validDestination(context.destination)||!validCur2(context.activeCur2,context.scope)||seen.has(context.scope.connectionId))throw new KubecostRuntimeError("SCOPE_REJECTED");seen.add(context.scope.connectionId);const parts=[context.scope.orgId,context.scope.customerId,context.scope.connectionId,input.scheduledWindow].map(encodeURIComponent);await input.enqueue({orgId:context.scope.orgId,customerId:context.scope.customerId,connectionId:context.scope.connectionId,kind:KUBECOST_DURABLE_JOB_KIND,payload:{scheduledWindow:input.scheduledWindow},maxAttempts:5,idempotencyKey:`kubecost:${parts.join(":")}`})}return contexts.length}

export async function runKubecostRuntimeJob(job:RunnableJob,deps:{readonly loadRuntimeContext:(scope:{readonly orgId:string;readonly customerId:string;readonly connectionId:string})=>Promise<KubecostRuntimeContext>;readonly broker:{collect(request:KubecostRuntimeRequest):Promise<VerifiedKubecostRuntimeResult>};readonly recordCapture:(scope:KubecostAllocationScope,capture:KubecostAllocationCapture,nowMs:number)=>Promise<{readonly generation:{readonly generationId:string;readonly snapshot:{readonly captureId:string;readonly state:string}}}>;readonly attempts:KubecostRuntimeAttemptStore;readonly now?:()=>number}){
  const scheduledWindow=parseJob(job),now=deps.now??Date.now,started=now();if(!Number.isSafeInteger(started)||started<0)throw new KubecostRuntimeError("INTERNAL_ERROR");let loaded:KubecostRuntimeContext;try{loaded=await deps.loadRuntimeContext({orgId:job.orgId,customerId:job.customerId!,connectionId:job.connectionId!})}catch{throw new KubecostRuntimeError("INTERNAL_ERROR")}
  if(!validScope(loaded.scope)||loaded.scope.orgId!==job.orgId||loaded.scope.customerId!==job.customerId||loaded.scope.connectionId!==job.connectionId||!validDestination(loaded.destination)||!validCur2(loaded.activeCur2,loaded.scope))throw new KubecostRuntimeError("SCOPE_REJECTED");const context=immutableContext(loaded);
  const destinationSha256=await sha(JSON.stringify(context.destination)),activeCur2Sha256=await sha(JSON.stringify(context.activeCur2));const requestId=`kur_${await sha(JSON.stringify({schema:"sutra.kubecost-runtime-id.v1",scope:context.scope,destinationSha256,activeCur2Sha256,scheduledWindow}))}`;if(!REQUEST.test(requestId))throw new KubecostRuntimeError("INTERNAL_ERROR");let prior;try{prior=await deps.attempts.getAttempt(context.scope,requestId,job.attempt)}catch{throw new KubecostRuntimeError("PERSISTENCE_REJECTED")}if(prior!==null){if(prior.failureCode!==null||prior.generationId===null)throw new KubecostRuntimeError(prior.failureCode??"INTERNAL_ERROR");return{requestId,generationId:prior.generationId,state:prior.state,replayed:true}}
  const request:KubecostRuntimeRequest=Object.freeze({schemaVersion:"sutra.kubecost-versioned-runtime-request.v1",requestId,jobId:job.id,scheduledWindow,scope:context.scope,destination:context.destination,activeCur2:context.activeCur2,activeCur2Sha256,exportContract:KUBECOST_EXPORT_CONTRACT,runtimeReadActions:KUBECOST_RUNTIME_S3_READ_IAM_ACTIONS,versionedReadActions:KUBECOST_VERSIONED_OBJECT_READ_IAM_ACTIONS,conditionalKmsActions:KUBECOST_SSE_KMS_READ_IAM_ACTIONS,exporterWriteActions:Object.freeze([]),bounds:KUBECOST_ALLOCATION_BOUNDS,maximumDurationMs:KUBECOST_RUNTIME_TIMEOUT_MS}),requestSha=await sha(JSON.stringify(request));
  try{const response=await deps.broker.collect(request);if(response.verification.requestBodySha256!==requestSha||!SHA.test(response.verification.responseBodySha256)||!KEY.test(response.verification.brokerKeyId))throw new KubecostRuntimeError("BROKER_RESPONSE_INVALID");if(!sameScope(response.capture.scope,context.scope))throw new KubecostRuntimeError("SCOPE_REJECTED");if(!sameDestination(response.capture,context.destination))throw new KubecostRuntimeError("DESTINATION_REJECTED");if(await sha(JSON.stringify(response.capture.cur2Evidence))!==activeCur2Sha256)throw new KubecostRuntimeError("CUR2_LINEAGE_REJECTED");if(completeCandidate(response.capture)&&response.capture.objects.some(object=>object.versionId===null))throw new KubecostRuntimeError("VERSION_PIN_REJECTED");let snapshot;try{snapshot=buildKubecostAllocationSnapshot(response.capture,context.scope,now())}catch{throw new KubecostRuntimeError("EVIDENCE_REJECTED")}let stored;try{stored=await deps.recordCapture(context.scope,response.capture,now())}catch{throw new KubecostRuntimeError("PERSISTENCE_REJECTED")}if(!GENERATION.test(stored.generation.generationId)||stored.generation.snapshot.captureId!==snapshot.captureId||stored.generation.snapshot.state!==snapshot.state||!CAPTURE.test(snapshot.captureId))throw new KubecostRuntimeError("PERSISTENCE_REJECTED");let recorded;try{recorded=await deps.attempts.recordAttempt({scope:context.scope,requestId,jobId:job.id,jobAttempt:job.attempt,scheduledWindow,destinationSha256,activeCur2Sha256,state:snapshot.state,generationId:stored.generation.generationId,captureId:snapshot.captureId,requestBodySha256:requestSha,responseBodySha256:response.verification.responseBodySha256,brokerKeyId:response.verification.brokerKeyId,failureCode:null,completedAtMs:now()})}catch{throw new KubecostRuntimeError("PERSISTENCE_REJECTED")}return{requestId,generationId:stored.generation.generationId,state:recorded.state,replayed:false}
  }catch(error){const code=sanitized(error);try{await deps.attempts.recordAttempt({scope:context.scope,requestId,jobId:job.id,jobAttempt:job.attempt,scheduledWindow,destinationSha256,activeCur2Sha256,state:"FAILED",generationId:null,captureId:null,requestBodySha256:requestSha,responseBodySha256:null,brokerKeyId:null,failureCode:code,completedAtMs:now()})}catch{/* sanitized */}throw new KubecostRuntimeError(code)}
}
export function createKubecostRuntimeHandler(deps:Parameters<typeof runKubecostRuntimeJob>[1]):JobHandler{return async job=>{await runKubecostRuntimeJob(job,deps)}}
export const KUBECOST_RUNTIME_BINDING=Object.freeze({jobKind:KUBECOST_DURABLE_JOB_KIND,cadence:KUBECOST_SCHEDULER_CADENCE,registeredInSharedRuntime:false,activationReason:KUBECOST_RUNTIME_ACTIVATION_REASON});
