/** Provider-neutral, version-explicit FOCUS consolidation contract. */
const ID=/^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,255}$/u,CURRENCY=/^[A-Z]{3}$/u,MICROS=/^-?(?:0|[1-9]\d{0,127})$/u,MONTH=/^\d{4}-(?:0[1-9]|1[0-2])$/u,SHA=/^[a-f0-9]{64}$/u;
export const FINOPS_FOCUS_NEUTRAL_BOUNDS=Object.freeze({maximumSources:36,maximumRows:250000,maximumTagsPerRow:64,maximumGovernedKeys:64});
export type FinopsFocusProvider="AWS"|"AZURE"|"GCP"|"OCI"|"SAAS"|"OTHER";
export type FinopsFocusVersion="1.0"|"1.0r2"|"1.1"|"1.2";
export interface FinopsFocusNeutralScope{readonly orgId:string;readonly customerId:string}
export interface FinopsFocusNeutralSource{readonly orgId:string;readonly customerId:string;readonly sourceId:string;readonly provider:FinopsFocusProvider;readonly focusVersion:FinopsFocusVersion;readonly datasetName:string;readonly generationId:string;readonly contentSha256:string;readonly collectedAt:string;readonly dataThroughAt:string;readonly normalizedSchema:"sutra.focus-neutral-line.v1"}
export interface FinopsFocusNeutralTag{readonly key:string;readonly value:string}
export interface FinopsFocusNeutralLine{readonly sourceId:string;readonly lineId:string;readonly billingPeriod:string;readonly billingCurrency:string;readonly billedCostMicros:string;readonly effectiveCostMicros:string|null;readonly listCostMicros:string|null;readonly contractedCostMicros:string|null;readonly providerName:string;readonly serviceName:string;readonly chargeCategory:string;readonly chargeClass:string|null;readonly chargeClassEvidence:"PRESENT"|"NOT_PROVIDED";readonly tags:readonly FinopsFocusNeutralTag[]}
export interface FinopsFocusTagTaxonomyPolicy{readonly policyId:string;readonly governedKeys:readonly{readonly key:string;readonly label:string}[];readonly providerTagPrefixes:Readonly<Partial<Record<FinopsFocusProvider,readonly string[]>>>}
export interface FinopsFocusNeutralInput{readonly scope:FinopsFocusNeutralScope;readonly sources:readonly FinopsFocusNeutralSource[];readonly rows:readonly FinopsFocusNeutralLine[];readonly taxonomy:FinopsFocusTagTaxonomyPolicy|null}
export interface FinopsFocusEffectiveDiscountRate{readonly state:"AVAILABLE"|"UNAVAILABLE";readonly basisPoints:string|null;readonly numeratorMicros:string|null;readonly denominatorMicros:string|null;readonly formula:"(LIST_COST-EFFECTIVE_COST)/LIST_COST";readonly reason:"VALID_FOCUS_COST_COMPARISON"|"MISSING_EFFECTIVE_COST"|"MISSING_LIST_COST"|"CHARGE_CLASS_SEMANTICS_NOT_PROVIDED"|"NON_POSITIVE_LIST_COST"|"NO_ELIGIBLE_ROWS"}
export interface FinopsFocusNeutralReport{readonly schema:"sutra.finops-focus-neutral-report.v1";readonly scope:FinopsFocusNeutralScope;readonly sources:readonly FinopsFocusNeutralSource[];readonly versions:readonly FinopsFocusVersion[];readonly providers:readonly FinopsFocusProvider[];readonly currencies:readonly{readonly currency:string;readonly billedCostMicros:string;readonly effectiveCostMicros:string|null;readonly effectiveDiscountRate:FinopsFocusEffectiveDiscountRate;readonly tags:readonly{readonly key:string;readonly label:string;readonly classification:"GOVERNED"|"PROVIDER_DEFINED"|"UNGOVERNED";readonly value:string;readonly billedCostMicros:string;readonly lineCount:number}[]}[];readonly taxonomy:{readonly state:"GOVERNED"|"NOT_CONFIGURED";readonly policyId:string|null;readonly governedKeys:readonly string[]};readonly invariants:readonly["source_versions_and_provenance_are_retained","currencies_are_never_combined","money_uses_signed_integer_micros","missing_cost_columns_are_never_substituted","discount_rate_requires_valid_focus_denominator_semantics"]}
export class FinopsFocusNeutralError extends Error{public readonly code:"INVALID_INPUT"|"SCOPE_MISMATCH"|"DUPLICATE_SOURCE"|"DUPLICATE_LINE"|"LIMIT_EXCEEDED";public constructor(code:FinopsFocusNeutralError["code"]){super("Provider-neutral FOCUS evidence was rejected");this.name="FinopsFocusNeutralError";this.code=code}}
function fail(code:FinopsFocusNeutralError["code"]="INVALID_INPUT"):never{throw new FinopsFocusNeutralError(code)}
function text(value:unknown):value is string{return typeof value==="string"&&value.length>0&&value.length<=4096&&!/[\0\r\n<>]/u.test(value)}
function record(value:unknown):value is Readonly<Record<string,unknown>>{return typeof value==="object"&&value!==null&&!Array.isArray(value)}
function exactMoney(value:unknown):value is string{return typeof value==="string"&&MICROS.test(value)}
function validDate(value:unknown):value is string{return typeof value==="string"&&Number.isFinite(Date.parse(value))}
function rate(rows:readonly FinopsFocusNeutralLine[]):FinopsFocusEffectiveDiscountRate{const base={basisPoints:null,numeratorMicros:null,denominatorMicros:null,formula:"(LIST_COST-EFFECTIVE_COST)/LIST_COST" as const};if(rows.length===0)return{state:"UNAVAILABLE",...base,reason:"NO_ELIGIBLE_ROWS"};if(rows.some(row=>row.chargeClassEvidence!=="PRESENT"))return{state:"UNAVAILABLE",...base,reason:"CHARGE_CLASS_SEMANTICS_NOT_PROVIDED"};const eligible=rows.filter(row=>row.chargeClass===null);if(eligible.length===0)return{state:"UNAVAILABLE",...base,reason:"NO_ELIGIBLE_ROWS"};if(eligible.some(row=>row.effectiveCostMicros===null))return{state:"UNAVAILABLE",...base,reason:"MISSING_EFFECTIVE_COST"};if(eligible.some(row=>row.listCostMicros===null))return{state:"UNAVAILABLE",...base,reason:"MISSING_LIST_COST"};let list=BigInt(0),effective=BigInt(0);for(const row of eligible){const special=row.chargeCategory.toLowerCase()==="usage"&&BigInt(row.billedCostMicros)===BigInt(0)&&BigInt(row.effectiveCostMicros!)!==BigInt(0);list+=special?BigInt(0):BigInt(row.listCostMicros!);effective+=BigInt(row.effectiveCostMicros!)}if(list<=BigInt(0))return{state:"UNAVAILABLE",...base,reason:"NON_POSITIVE_LIST_COST"};const numerator=list-effective;return{state:"AVAILABLE",basisPoints:((numerator*BigInt(10000))/list).toString(),numeratorMicros:numerator.toString(),denominatorMicros:list.toString(),formula:base.formula,reason:"VALID_FOCUS_COST_COMPARISON"}}
export function buildProviderNeutralFocusReport(input:FinopsFocusNeutralInput):FinopsFocusNeutralReport{if(!input||!input.scope||!ID.test(input.scope.orgId)||!ID.test(input.scope.customerId)||!Array.isArray(input.sources)||input.sources.length<1||input.sources.length>FINOPS_FOCUS_NEUTRAL_BOUNDS.maximumSources||!Array.isArray(input.rows)||input.rows.length>FINOPS_FOCUS_NEUTRAL_BOUNDS.maximumRows)fail();const sourceIds=new Set<string>();for(const source of input.sources){if(!record(source)||!ID.test(source.sourceId as string)||sourceIds.has(source.sourceId as string))fail(sourceIds.has(source.sourceId as string)?"DUPLICATE_SOURCE":"INVALID_INPUT");if(source.orgId!==input.scope.orgId||source.customerId!==input.scope.customerId)fail("SCOPE_MISMATCH");sourceIds.add(source.sourceId as string);if(!["AWS","AZURE","GCP","OCI","SAAS","OTHER"].includes(source.provider as string)||!["1.0","1.0r2","1.1","1.2"].includes(source.focusVersion as string)||!text(source.datasetName)||!ID.test(source.generationId as string)||!SHA.test(source.contentSha256 as string)||!validDate(source.collectedAt)||!validDate(source.dataThroughAt)||source.normalizedSchema!=="sutra.focus-neutral-line.v1")fail()}let governed=new Map<string,string>();if(input.taxonomy!==null){if(!record(input.taxonomy)||!ID.test(input.taxonomy.policyId as string)||!Array.isArray(input.taxonomy.governedKeys)||input.taxonomy.governedKeys.length>FINOPS_FOCUS_NEUTRAL_BOUNDS.maximumGovernedKeys||!record(input.taxonomy.providerTagPrefixes))fail();governed=new Map(input.taxonomy.governedKeys.map(item=>{if(!record(item)||!text(item.key)||!text(item.label))fail();return[item.key,item.label]}));if(governed.size!==input.taxonomy.governedKeys.length)fail();for(const[provider,prefixes]of Object.entries(input.taxonomy.providerTagPrefixes)){if(!["AWS","AZURE","GCP","OCI","SAAS","OTHER"].includes(provider)||!Array.isArray(prefixes)||prefixes.length>32||prefixes.some(prefix=>!text(prefix)))fail()}}
 const identities=new Set<string>(),currencies=new Map<string,FinopsFocusNeutralLine[]>();for(const row of input.rows){if(!sourceIds.has(row.sourceId))fail("SCOPE_MISMATCH");const identity=`${row.sourceId}\0${row.lineId}`;if(identities.has(identity))fail("DUPLICATE_LINE");identities.add(identity);if(!text(row.lineId)||!MONTH.test(row.billingPeriod)||!CURRENCY.test(row.billingCurrency)||!exactMoney(row.billedCostMicros)||(row.effectiveCostMicros!==null&&!exactMoney(row.effectiveCostMicros))||(row.listCostMicros!==null&&!exactMoney(row.listCostMicros))||(row.contractedCostMicros!==null&&!exactMoney(row.contractedCostMicros))||!text(row.providerName)||!text(row.serviceName)||!text(row.chargeCategory)||(row.chargeClass!==null&&!text(row.chargeClass))||!["PRESENT","NOT_PROVIDED"].includes(row.chargeClassEvidence)||!Array.isArray(row.tags)||row.tags.length>FINOPS_FOCUS_NEUTRAL_BOUNDS.maximumTagsPerRow)fail();const keys=new Set<string>();for(const tag of row.tags){if(!text(tag.key)||!text(tag.value)||keys.has(tag.key))fail();keys.add(tag.key)}currencies.set(row.billingCurrency,[...(currencies.get(row.billingCurrency)??[]),row])}
 const sourceById=new Map<string,FinopsFocusNeutralSource>(input.sources.map(source=>[source.sourceId,source]));const reports=[...currencies].sort(([a],[b])=>a.localeCompare(b)).map(([currency,rows])=>{let billed=BigInt(0),effective=BigInt(0),hasEffective=true;const tagGroups=new Map<string,{key:string;label:string;classification:"GOVERNED"|"PROVIDER_DEFINED"|"UNGOVERNED";value:string;billed:bigint;count:number}>();for(const row of rows){billed+=BigInt(row.billedCostMicros);if(row.effectiveCostMicros===null)hasEffective=false;else effective+=BigInt(row.effectiveCostMicros);const provider:FinopsFocusProvider=sourceById.get(row.sourceId)!.provider,prefixes:readonly string[]=input.taxonomy?.providerTagPrefixes[provider]??[];for(const tag of row.tags){const label=governed.get(tag.key),classification=label!==undefined?"GOVERNED" as const:prefixes.some((prefix:string)=>tag.key.startsWith(prefix))?"PROVIDER_DEFINED" as const:"UNGOVERNED" as const,key=`${classification}\0${tag.key}\0${tag.value}`,current=tagGroups.get(key)??{key:tag.key,label:label??tag.key,classification,value:tag.value,billed:BigInt(0),count:0};current.billed+=BigInt(row.billedCostMicros);current.count+=1;tagGroups.set(key,current)}}return{currency,billedCostMicros:billed.toString(),effectiveCostMicros:hasEffective?effective.toString():null,effectiveDiscountRate:rate(rows),tags:[...tagGroups.values()].sort((a,b)=>a.key.localeCompare(b.key)||a.value.localeCompare(b.value)).map(tag=>({key:tag.key,label:tag.label,classification:tag.classification,value:tag.value,billedCostMicros:tag.billed.toString(),lineCount:tag.count}))}});return{schema:"sutra.finops-focus-neutral-report.v1",scope:input.scope,sources:[...input.sources].sort((a,b)=>a.sourceId.localeCompare(b.sourceId)),versions:[...new Set(input.sources.map(source=>source.focusVersion))].sort(),providers:[...new Set(input.sources.map(source=>source.provider))].sort(),currencies:reports,taxonomy:{state:input.taxonomy===null?"NOT_CONFIGURED":"GOVERNED",policyId:input.taxonomy?.policyId??null,governedKeys:[...governed.keys()].sort()},invariants:["source_versions_and_provenance_are_retained","currencies_are_never_combined","money_uses_signed_integer_micros","missing_cost_columns_are_never_substituted","discount_rate_requires_valid_focus_denominator_semantics"]}}
