/** Production dependency composition for complete local ADD-05 runtime. */
import type { RunnableJob } from "./background-job-runner.ts";
import { EvidenceRepository } from "../db/evidence-repository.ts";
import { JobQueueRepository } from "../db/job-queue-repository.ts";
import { MarketplaceSpgRuntimeRepository } from "../db/finops-marketplace-spg-runtime-repository.ts";
import { FinopsEvidenceReferenceSealer } from "./finops-source-evidence-reference.ts";
import { createMarketplaceSpgSignedBroker, type MarketplaceSpgSignedBrokerConfiguration } from "./finops-marketplace-spg-signed-broker.ts";
import { runMarketplaceSpgRuntimeHandler, scheduleMarketplaceSpgCollections, type MarketplaceSpgRuntimeSignedBroker } from "./finops-marketplace-spg-runtime-binding.ts";

export const MARKETPLACE_SPG_PRODUCTION_COMPOSITION_SCHEMA="sutra.marketplace-spg-production-composition.v1" as const;
export const MARKETPLACE_SPG_REQUIRED_PERMISSION_PACK="standard-2026-08.13" as const;
export const MARKETPLACE_SPG_PRODUCTION_STATUS=Object.freeze({schemaVersion:MARKETPLACE_SPG_PRODUCTION_COMPOSITION_SCHEMA,credentialOwningProviderRouteImplemented:true,signedBrokerClientImplemented:true,durableReplayRepositoryImplemented:true,immutableControlPlaneAndCur2HistoryImplemented:true,approvedProductTypingImplemented:true,bedrockClassificationImplemented:false,explicitRuntimeStatesImplemented:true,deterministicDailyTickImplemented:true,requiredPermissionPack:MARKETPLACE_SPG_REQUIRED_PERMISSION_PACK,sharedWorkerRegistered:false,activationState:"AWAITING_SHARED_REGISTRY_HOOK" as const});
const DAY_MS=24*60*60*1_000;
export function marketplaceSpgScheduledWindow(atMs:number){if(!Number.isSafeInteger(atMs)||atMs<0)throw new Error("MARKETPLACE_SPG_SCHEDULE_INVALID");return new Date(Math.floor(atMs/DAY_MS)*DAY_MS).toISOString()}
export interface MarketplaceSpgProductionOptions { readonly database?:D1Database; readonly now?:()=>number; readonly env:Readonly<Record<string,string|undefined>>; readonly brokerConfiguration?:MarketplaceSpgSignedBrokerConfiguration; readonly fetcher?:typeof fetch; readonly broker?:MarketplaceSpgRuntimeSignedBroker }
export async function createMarketplaceSpgProductionComposition(options:MarketplaceSpgProductionOptions){if((options.broker===undefined)===(options.brokerConfiguration===undefined))throw new Error("MARKETPLACE_SPG_EXACTLY_ONE_BROKER_REQUIRED");if(options.fetcher!==undefined&&options.brokerConfiguration===undefined)throw new Error("MARKETPLACE_SPG_FETCHER_REQUIRES_SIGNED_CONFIGURATION");const now=options.now??Date.now;const runtime=new MarketplaceSpgRuntimeRepository(options.database,{now});const evidence=new EvidenceRepository(options.database);const sealer=await FinopsEvidenceReferenceSealer.fromEnvironment(options.env);const broker=options.broker??createMarketplaceSpgSignedBroker({configuration:options.brokerConfiguration!,...(options.fetcher===undefined?{}:{fetcher:options.fetcher}),now});const queue=new JobQueueRepository(options.database);return Object.freeze({schemaVersion:MARKETPLACE_SPG_PRODUCTION_COMPOSITION_SCHEMA,runtimeRepository:runtime,handler:async(job:RunnableJob)=>{const attempt=new MarketplaceSpgRuntimeRepository(options.database,{now});await runMarketplaceSpgRuntimeHandler(job,{loadBoundary:attempt.loadBoundary.bind(attempt),broker,evidence,sealer,handoff:attempt,now})},scheduleTick:(atMs:number)=>scheduleMarketplaceSpgCollections({loadEligibleScopes:runtime.listEligibleScopes.bind(runtime),queue,scheduledWindow:marketplaceSpgScheduledWindow(atMs)})})}
