/** Immutable FND-03 audit of the AWS KPI Dashboard v2.2.1 definition. */
export const FINOPS_KPI_OFFICIAL_DEFINITION = Object.freeze({
  source: Object.freeze({
    repository: "aws-solutions-library-samples/cloud-intelligence-dashboards-framework",
    commit: "f9e36d88c47709f10e8fa784ad11d5cc0e728021",
    manifestPath: "dashboards/kpi_dashboard/KPI.yaml",
    manifestSha256: "fd669f207c5589b4b54b981d6d85affb3af449871e908b85a4c1b9b357c35b1a",
    definitionPath: "dashboards/kpi_dashboard/KPI-definition.yaml",
    definitionSha256: "299c6d39c55c28221b0d0d771358f526931d60fb5f4d00ba4f663d22554b89a1",
    dashboardId: "kpi_dashboard",
    version: "v2.2.1",
    category: "Foundational",
    theme: "MIDNIGHT",
  }),
  documentationUrl:
    "https://docs.aws.amazon.com/guidance/latest/cloud-intelligence-dashboards/cudos-cid-kpi.html#kpi-dashboard",
  totals: Object.freeze({
    sheets: 10,
    visuals: 91,
    parameterControls: 60,
    filterControls: 34,
    parameterDeclarations: 50,
    calculatedFields: 191,
    filterGroups: 161,
    goalSliders: 19,
    visualTypes: Object.freeze({
      BarChartVisual: 15,
      ComboChartVisual: 9,
      InsightVisual: 39,
      LineChartVisual: 1,
      PieChartVisual: 3,
      PivotTableVisual: 20,
      TableVisual: 3,
      WordCloudVisual: 1,
    }),
  }),
  sheets: Object.freeze([
    Object.freeze({
      id: "f5a6e45e-eb00-47c5-9aba-70a41d43696e",
      name: "KPI Tracker",
      visualCount: 6,
      visualTypes: Object.freeze({ InsightVisual: 2, PivotTableVisual: 4 }),
      parameterControls: Object.freeze(["Group By", "Account ID", "Payer Account ID"]),
      filterControls: Object.freeze({ CrossSheet: 2 }),
      support: "PARTIAL",
      formulaIds: Object.freeze([
        "ec2_previous_generation", "ec2_spot_share", "ec2_graviton_share",
        "ec2_amd_share", "ebs_gp3_adoption", "aged_snapshots",
        "s3_standard_concentration", "rds_graviton_share",
        "rds_open_source_engine_share", "elasticache_graviton_share",
        "opensearch_graviton_share", "lambda_graviton_share",
        "compute_on_demand_ratio", "sagemaker_on_demand_ratio",
        "rds_on_demand_ratio", "elasticache_on_demand_ratio",
        "opensearch_on_demand_ratio", "redshift_on_demand_ratio",
        "dynamodb_on_demand_ratio",
      ]),
      gaps: Object.freeze(["Additional monthly savings at goal remains unavailable without an approved savings assumption."]),
    }),
    Object.freeze({
      id: "fececc73-dabe-4a4e-9477-e8abdf8337f6",
      name: "Set KPI Goals",
      visualCount: 8,
      visualTypes: Object.freeze({ InsightVisual: 8 }),
      parameterControls: Object.freeze([
        "Compute OD Goal (%)", "ElastiCache Graviton Goal (%)",
        "OpenSearch Graviton Goal (%)", "Lambda Graviton Goal (%)",
        "Sagemaker OD Goal (%)", "RDS OD Goal (%)",
        "ElastiCache OD Goal (%)", "OpenSearch OD Goal (%)",
        "Redshift OD Goal (%)", "DynamoDB OD Goal (%)",
        "EBS gp3 of gp Goal (%)", "EBS Snapshot over 1yr Goal (%)",
        "EC2 AMD Goal (%)", "EC2 Graviton Goal (%)", "EC2 Spot Goal (%)",
        "RDS Graviton Goal (%)", "S3 Standard Storage Goal (%)",
        "EC2 Previous Generation Goal (%)", "RDS Open Source Engines Goal (%)",
      ]),
      filterControls: Object.freeze({ CrossSheet: 2 }),
      support: "PARTIAL",
      formulaIds: Object.freeze([]),
      gaps: Object.freeze(["Goals are versioned and RBAC-protected in Sutra; the native panel is read-only and does not silently reproduce QuickSight parameter mutations."]),
    }),
    Object.freeze({
      id: "4064f1e2-7cdf-4a48-846d-4f9c8033e38f",
      name: "Metrics Summary",
      visualCount: 14,
      visualTypes: Object.freeze({ InsightVisual: 7, PivotTableVisual: 7 }),
      parameterControls: Object.freeze(["S3 Coverage Type", "EBS Coverage Type", "EC2 Coverage Type", "Snap Coverage Type", "Graviton Type", "OnDemand Type", "RDS Coverage Type", "Group By", "Account ID", "Payer Account ID"]),
      filterControls: Object.freeze({ CrossSheet: 2 }),
      support: "PARTIAL",
      formulaIds: Object.freeze([]),
      gaps: Object.freeze(["The selected-period scorecard is supported; official month-over-month pivots require multiple simultaneously evaluated generations."]),
    }),
    Object.freeze({
      id: "8c55242a-ab85-46b6-8255-7f820f503cf9",
      name: "EC2",
      visualCount: 10,
      visualTypes: Object.freeze({ BarChartVisual: 2, ComboChartVisual: 2, InsightVisual: 4, PieChartVisual: 1, PivotTableVisual: 1 }),
      parameterControls: Object.freeze(["Group By", "Account ID", "Payer Account ID", "Enter EC2 Instance"]),
      filterControls: Object.freeze({ CrossSheet: 2, Dropdown: 6 }),
      support: "PARTIAL",
      formulaIds: Object.freeze(["ec2_previous_generation", "ec2_spot_share", "ec2_graviton_share", "ec2_amd_share"]),
      gaps: Object.freeze(["Processor and generation coverage are CUR candidates; compatible migration and savings rankings require approved inventory and rate evidence."]),
    }),
    Object.freeze({
      id: "b409d597-aeb8-4875-81e0-cf896265dc84",
      name: "EBS",
      visualCount: 18,
      visualTypes: Object.freeze({ BarChartVisual: 3, ComboChartVisual: 4, InsightVisual: 5, PieChartVisual: 2, PivotTableVisual: 3, TableVisual: 1 }),
      parameterControls: Object.freeze(["Group By", "Payer Account ID", "Account ID", "Enter Volume IDs", "Enter EBS Snapshot ID"]),
      filterControls: Object.freeze({ CrossSheet: 2 }),
      support: "PARTIAL",
      formulaIds: Object.freeze(["ebs_gp3_adoption", "aged_snapshots"]),
      gaps: Object.freeze(["Volume lookup, gp2-to-gp3 savings and snapshot-age detail require authoritative EBS inventory and versioned pricing assumptions."]),
    }),
    Object.freeze({
      id: "c5d7c096-a4f2-46b0-97e7-5e7f1c808994",
      name: "S3",
      visualCount: 11,
      visualTypes: Object.freeze({ BarChartVisual: 3, ComboChartVisual: 1, InsightVisual: 3, LineChartVisual: 1, PivotTableVisual: 1, TableVisual: 2 }),
      parameterControls: Object.freeze(["Group By", "Account ID", "Payer Account ID", "Enter S3 Bucket Name"]),
      filterControls: Object.freeze({ CrossSheet: 2 }),
      support: "PARTIAL",
      formulaIds: Object.freeze(["s3_standard_concentration"]),
      gaps: Object.freeze(["Bucket lookup, request inactivity and storage-class migration savings require S3 activity and approved pricing evidence not present in CUR alone."]),
    }),
    Object.freeze({
      id: "6c933301-c929-4cc8-85e5-040ea87d5bdd",
      name: "RDS",
      visualCount: 15,
      visualTypes: Object.freeze({ BarChartVisual: 7, ComboChartVisual: 1, InsightVisual: 4, PivotTableVisual: 2, WordCloudVisual: 1 }),
      parameterControls: Object.freeze(["RDS Engines with Licensing Options", "Group By", "Account ID", "Payer Account ID"]),
      filterControls: Object.freeze({ CrossSheet: 2 }),
      support: "PARTIAL",
      formulaIds: Object.freeze(["rds_graviton_share", "rds_open_source_engine_share"]),
      gaps: Object.freeze(["Open-source and Graviton coverage are candidates; engine migration compatibility and potential savings are unavailable without approved evidence."]),
    }),
    Object.freeze({
      id: "7a59ce7f-bcb0-4169-b90a-983d6785dfec",
      name: "Other Graviton",
      visualCount: 5,
      visualTypes: Object.freeze({ ComboChartVisual: 1, InsightVisual: 3, PivotTableVisual: 1 }),
      parameterControls: Object.freeze(["Other Graviton Services", "Group By", "Account ID", "Payer Account ID", "Enter Resource ID"]),
      filterControls: Object.freeze({ CrossSheet: 2, Dropdown: 1 }),
      support: "PARTIAL",
      formulaIds: Object.freeze(["elasticache_graviton_share", "opensearch_graviton_share", "lambda_graviton_share"]),
      gaps: Object.freeze(["Sutra reports classifiable current architecture only and withholds compatible migration savings."]),
    }),
    Object.freeze({
      id: "68587d15-fcd6-45ff-a7f0-30966f8ac763",
      name: "Commit Optimizations",
      visualCount: 2,
      visualTypes: Object.freeze({ InsightVisual: 1, PivotTableVisual: 1 }),
      parameterControls: Object.freeze(["Show Values", "Compute Savings Plan", "Group By", "Account ID", "Payer Account ID", "Enter Resource ID"]),
      filterControls: Object.freeze({ CrossSheet: 2, Dropdown: 5, List: 2 }),
      support: "PARTIAL",
      formulaIds: Object.freeze(["compute_on_demand_ratio", "sagemaker_on_demand_ratio", "rds_on_demand_ratio", "elasticache_on_demand_ratio", "opensearch_on_demand_ratio", "redshift_on_demand_ratio", "dynamodb_on_demand_ratio"]),
      gaps: Object.freeze(["On-Demand ratios are supported; detailed commitment purchase recommendations and savings are not inferred from coverage ratios."]),
    }),
    Object.freeze({
      id: "510c6e7c-929f-4da4-b007-e633099f672f",
      name: "About",
      visualCount: 2,
      visualTypes: Object.freeze({ InsightVisual: 2 }),
      parameterControls: Object.freeze([]),
      filterControls: Object.freeze({ CrossSheet: 2 }),
      support: "SUPPORTED",
      formulaIds: Object.freeze([]),
      gaps: Object.freeze([]),
    }),
  ]),
} as const);

export type FinopsKpiOfficialDefinition =
  typeof FINOPS_KPI_OFFICIAL_DEFINITION;
