/** Server-owned dual-channel materialization contract. No proxy-to-carbon conversion exists. */
import { AWS_CARBON_EMISSIONS_COLUMNS, SUSTAINABILITY_CARBON_BOUNDS, type SustainabilityCarbonCapture, type SustainabilityScope } from "./finops-sustainability-carbon.ts";

export const SUSTAINABILITY_EXPORT_READ_ACTIONS = Object.freeze(["s3:GetBucketLocation","s3:ListBucket","s3:GetObject"] as const);
export const SUSTAINABILITY_VERSIONED_READ_ACTIONS = Object.freeze(["s3:GetObjectVersion"] as const);
export interface SustainabilityMaterializationRequest {
  readonly schemaVersion:"sutra.sustainability-materialization-request.v1"; readonly scope:SustainabilityScope;
  readonly allowedUsageAccountIds:readonly string[]; readonly activeCur2GenerationId:string;
  readonly carbonExport:{readonly bucket:string;readonly prefix:string;readonly expectedBucketOwner:string;readonly expectedUsagePeriods:readonly string[]};
  readonly channels:{readonly proxy:{readonly source:"AWS_CUR2_ACTIVE_GENERATION";readonly interpretation:"RESOURCE_USE_PROXY_NOT_CARBON"};readonly providerCarbon:{readonly source:"AWS_SUSTAINABILITY_CARBON_DATA_EXPORT";readonly tableName:"CARBON_EMISSIONS";readonly schemaColumns:typeof AWS_CARBON_EMISSIONS_COLUMNS;readonly interpretation:"PROVIDER_ESTIMATE_MTCO2E_NOT_WORKLOAD_ATTRIBUTION"}};
  readonly currentObjectReadActions:typeof SUSTAINABILITY_EXPORT_READ_ACTIONS; readonly versionedObjectReadActions:typeof SUSTAINABILITY_VERSIONED_READ_ACTIONS;
  readonly bounds:typeof SUSTAINABILITY_CARBON_BOUNDS; readonly deadlineAtIso:string;
}
export interface SustainabilitySignedMaterializer { collect(request:SustainabilityMaterializationRequest):Promise<SustainabilityCarbonCapture> }
export interface SustainabilitySnapshotStore { recordCapture(scope:SustainabilityScope,capture:SustainabilityCarbonCapture,nowMs:number):Promise<{readonly generation:{readonly generationId:string;readonly snapshot:{readonly captureId:string;readonly state:string}};readonly becameActive:boolean}> }
export class SustainabilityMaterializationJobError extends Error { public constructor(){super("Sustainability materialization failed");this.name="SustainabilityMaterializationJobError";} }
function sameScope(left:SustainabilityScope,right:SustainabilityScope){return left.orgId===right.orgId&&left.customerId===right.customerId&&left.connectionId===right.connectionId&&left.accountId===right.accountId&&left.partition===right.partition;}
export async function runSustainabilityMaterializationJob(input:{readonly scope:SustainabilityScope;readonly allowedUsageAccountIds:readonly string[];readonly activeCur2GenerationId:string;readonly carbonExport:SustainabilityMaterializationRequest["carbonExport"];readonly materializer:SustainabilitySignedMaterializer;readonly store:SustainabilitySnapshotStore;readonly nowMs?:number}){
  const nowMs=input.nowMs??Date.now();
  if(!Number.isSafeInteger(nowMs)||nowMs<0||!/^fbg_[a-f0-9]{64}$/u.test(input.activeCur2GenerationId)||!/^\d{12}$/u.test(input.carbonExport.expectedBucketOwner)||!input.carbonExport.prefix.endsWith("/")||input.carbonExport.prefix.includes("..")||input.allowedUsageAccountIds.length<1||input.allowedUsageAccountIds.some((id)=>!/^\d{12}$/u.test(id)))throw new SustainabilityMaterializationJobError();
  const request:SustainabilityMaterializationRequest=Object.freeze({schemaVersion:"sutra.sustainability-materialization-request.v1",scope:Object.freeze({...input.scope}),allowedUsageAccountIds:Object.freeze([...input.allowedUsageAccountIds]),activeCur2GenerationId:input.activeCur2GenerationId,carbonExport:Object.freeze({...input.carbonExport,expectedUsagePeriods:Object.freeze([...input.carbonExport.expectedUsagePeriods])}),channels:Object.freeze({proxy:Object.freeze({source:"AWS_CUR2_ACTIVE_GENERATION",interpretation:"RESOURCE_USE_PROXY_NOT_CARBON"}),providerCarbon:Object.freeze({source:"AWS_SUSTAINABILITY_CARBON_DATA_EXPORT",tableName:"CARBON_EMISSIONS",schemaColumns:AWS_CARBON_EMISSIONS_COLUMNS,interpretation:"PROVIDER_ESTIMATE_MTCO2E_NOT_WORKLOAD_ATTRIBUTION"})}),currentObjectReadActions:SUSTAINABILITY_EXPORT_READ_ACTIONS,versionedObjectReadActions:SUSTAINABILITY_VERSIONED_READ_ACTIONS,bounds:SUSTAINABILITY_CARBON_BOUNDS,deadlineAtIso:new Date(nowMs+SUSTAINABILITY_CARBON_BOUNDS.maximumCaptureDurationMs).toISOString()});
  try{const capture=await input.materializer.collect(request);if(!sameScope(capture.scope,input.scope)||JSON.stringify(capture.allowedUsageAccountIds)!==JSON.stringify(input.allowedUsageAccountIds)||capture.proxyEvidence?.generationId!==input.activeCur2GenerationId||(capture.carbonEvidence!==null&&(capture.carbonEvidence.bucket!==input.carbonExport.bucket||capture.carbonEvidence.prefix!==input.carbonExport.prefix||JSON.stringify(capture.carbonEvidence.expectedUsagePeriods)!==JSON.stringify(input.carbonExport.expectedUsagePeriods))))throw new SustainabilityMaterializationJobError();const stored=await input.store.recordCapture(input.scope,capture,nowMs);return{generationId:stored.generation.generationId,sourceCaptureId:stored.generation.snapshot.captureId,state:stored.generation.snapshot.state,becameActive:stored.becameActive};}catch{throw new SustainabilityMaterializationJobError();}
}
