/** Durable >=17 minute CORA provider lease and crash-recovery ledger. */
import { getRawDb } from "./index.ts";
import { ensureRuntimeSchema } from "./runtime-migrations.ts";
import type { CoraExportObjectScope } from "./finops-cora-export-object-repository.ts";

export const CORA_RUNTIME_LEASE_MS = 17 * 60 * 1_000;
export type CoraRuntimeFailureCode = "ADAPTER_TIMEOUT" | "ADAPTER_UNAVAILABLE" | "CAPTURE_REJECTED" | "PERSISTENCE_REJECTED";
export interface CoraRuntimeAttemptIdentity extends CoraExportObjectScope { readonly requestKey: string; readonly jobId: string; readonly scheduledWindow: string; readonly jobAttempt: number; readonly maxAttempts: number; }
interface Row { readonly request_key: string; readonly org_id: string; readonly customer_id: string; readonly connection_id: string; readonly job_id: string; readonly scheduled_window: string; readonly state: "IN_PROGRESS" | "SUCCEEDED" | "RETRYABLE_FAILED" | "FAILED"; readonly lease_token: string | null; readonly lease_expires_at: number | string | null; readonly attempt_count: number | string; readonly generation_id: string | null; readonly failure_code: CoraRuntimeFailureCode | null; readonly started_at: number | string; readonly completed_at: number | string | null; readonly updated_at: number | string; }
export class CoraRuntimeAttemptError extends Error { public readonly code: "INVALID_INPUT" | "SCOPE_NOT_FOUND" | "ATTEMPT_IN_PROGRESS" | "TERMINAL_FAILURE" | "LEASE_LOST" | "STORED_STATE_INVALID"; public constructor(code: CoraRuntimeAttemptError["code"]) { super("CORA runtime attempt rejected"); this.name = "CoraRuntimeAttemptError"; this.code = code; } }
function reject(code: CoraRuntimeAttemptError["code"]): never { throw new CoraRuntimeAttemptError(code); }
const SAFE = /^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,255}$/u; const CONNECTION = /^conn_[a-f0-9]{32}$/u; const REQUEST = /^corarq_[a-f0-9]{64}$/u; const JOB = /^job_(?:[a-f0-9]{32}|[a-f0-9]{64})$/u; const WINDOW = /^\d{4}-\d{2}-\d{2}T00:00:00\.000Z$/u; const GENERATION = /^core_[a-f0-9]{64}$/u;
function integer(value: unknown): number { const result = typeof value === "string" ? Number(value) : value; if (typeof result !== "number" || !Number.isSafeInteger(result) || result < 0) reject("STORED_STATE_INVALID"); return result; }
function valid(input: CoraRuntimeAttemptIdentity): void { if (!SAFE.test(input.organizationId) || !SAFE.test(input.customerId) || !CONNECTION.test(input.connectionId) || !REQUEST.test(input.requestKey) || !JOB.test(input.jobId) || !WINDOW.test(input.scheduledWindow) || !Number.isSafeInteger(input.jobAttempt) || input.jobAttempt < 1 || !Number.isSafeInteger(input.maxAttempts) || input.maxAttempts < input.jobAttempt || input.maxAttempts > 25) reject("INVALID_INPUT"); }
export class CoraRuntimeAttemptRepository {
  private readonly leases = new Map<string, string>();
  public constructor(private readonly database: D1Database = getRawDb(), private readonly now: () => number = Date.now) {}
  private async ready(): Promise<D1Database> { await ensureRuntimeSchema(this.database); return this.database; }
  private async row(requestKey: string): Promise<Row | null> { return (await this.ready()).prepare("SELECT * FROM finops_cora_runtime_attempts WHERE request_key=? LIMIT 1").bind(requestKey).first<Row>(); }
  public async prepare(input: CoraRuntimeAttemptIdentity): Promise<{ readonly state: "leased" | "replayed"; readonly generationId: string | null }> {
    valid(input); const now = this.now(); if (!Number.isSafeInteger(now) || now < 0) reject("INVALID_INPUT"); const token = `coral_${crypto.randomUUID().replaceAll("-", "")}`; const expires = now + CORA_RUNTIME_LEASE_MS; const db = await this.ready();
    await db.prepare(`INSERT INTO finops_cora_runtime_attempts(request_key,org_id,customer_id,connection_id,job_id,scheduled_window,state,lease_token,lease_expires_at,attempt_count,generation_id,failure_code,started_at,completed_at,updated_at) SELECT ?,c.org_id,c.customer_id,c.id,?,?,'IN_PROGRESS',?,?,1,NULL,NULL,?,NULL,? FROM aws_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status IN ('active','trial') WHERE c.org_id=? AND c.customer_id=? AND c.id=? AND c.source_kind='aws_trust_role' AND c.status='active' AND c.permission_pack_version='standard-2026-08.14' ON CONFLICT DO NOTHING`).bind(input.requestKey, input.jobId, input.scheduledWindow, token, expires, now, now, input.organizationId, input.customerId, input.connectionId).run();
    let row = await this.row(input.requestKey); if (row === null || row.org_id !== input.organizationId || row.customer_id !== input.customerId || row.connection_id !== input.connectionId || row.scheduled_window !== input.scheduledWindow) reject("SCOPE_NOT_FOUND");
    if (row.state === "SUCCEEDED") { if (row.generation_id === null || !GENERATION.test(row.generation_id)) reject("STORED_STATE_INVALID"); return { state: "replayed", generationId: row.generation_id }; }
    if (row.state === "FAILED") reject("TERMINAL_FAILURE");
    if (row.lease_token === token) { this.leases.set(input.requestKey, token); return { state: "leased", generationId: null }; }
    if (row.state === "IN_PROGRESS" && row.lease_expires_at !== null && integer(row.lease_expires_at) > now) reject("ATTEMPT_IN_PROGRESS");
    const reclaimed = await db.prepare(`UPDATE finops_cora_runtime_attempts SET job_id=?,state='IN_PROGRESS',lease_token=?,lease_expires_at=?,attempt_count=attempt_count+1,generation_id=NULL,failure_code=NULL,started_at=?,completed_at=NULL,updated_at=? WHERE request_key=? AND org_id=? AND customer_id=? AND connection_id=? AND state IN ('IN_PROGRESS','RETRYABLE_FAILED') AND (state='RETRYABLE_FAILED' OR lease_expires_at<=?) AND attempt_count<25`).bind(input.jobId, token, expires, now, now, input.requestKey, input.organizationId, input.customerId, input.connectionId, now).run();
    if ((reclaimed.meta?.changes ?? 0) !== 1) reject("ATTEMPT_IN_PROGRESS"); row = await this.row(input.requestKey); if (row === null || row.lease_token !== token) reject("LEASE_LOST"); this.leases.set(input.requestKey, token); return { state: "leased", generationId: null };
  }
  public async recoverPersistedGeneration(input: Pick<CoraRuntimeAttemptIdentity, "organizationId" | "customerId" | "connectionId" | "requestKey">): Promise<string | null> {
    const token = this.leases.get(input.requestKey); if (token === undefined) reject("LEASE_LOST"); const now = this.now(); const found = await (await this.ready()).prepare(`SELECT generation_id FROM finops_cora_export_object_generations WHERE org_id=? AND customer_id=? AND connection_id=? AND request_key=? ORDER BY created_at DESC LIMIT 1`).bind(input.organizationId, input.customerId, input.connectionId, input.requestKey).first<{ readonly generation_id: string }>(); if (found === null) return null; await this.commitSuccess({ ...input, generationId: found.generation_id, completedAtMs: now }); return found.generation_id;
  }
  public async commitSuccess(input: Pick<CoraRuntimeAttemptIdentity, "organizationId" | "customerId" | "connectionId" | "requestKey"> & { readonly generationId: string; readonly completedAtMs: number }): Promise<void> {
    const token = this.leases.get(input.requestKey); if (token === undefined || !GENERATION.test(input.generationId) || !Number.isSafeInteger(input.completedAtMs) || input.completedAtMs < 0) reject("LEASE_LOST"); const result = await (await this.ready()).prepare(`UPDATE finops_cora_runtime_attempts SET state='SUCCEEDED',lease_token=NULL,lease_expires_at=NULL,generation_id=?,failure_code=NULL,completed_at=?,updated_at=? WHERE request_key=? AND org_id=? AND customer_id=? AND connection_id=? AND state='IN_PROGRESS' AND lease_token=? AND lease_expires_at>=? AND EXISTS(SELECT 1 FROM finops_cora_export_object_generations g WHERE g.generation_id=? AND g.org_id=? AND g.customer_id=? AND g.connection_id=? AND g.request_key=?)`).bind(input.generationId, input.completedAtMs, input.completedAtMs, input.requestKey, input.organizationId, input.customerId, input.connectionId, token, input.completedAtMs, input.generationId, input.organizationId, input.customerId, input.connectionId, input.requestKey).run(); if ((result.meta?.changes ?? 0) !== 1) reject("LEASE_LOST"); this.leases.delete(input.requestKey);
  }
  public async recordFailure(input: Pick<CoraRuntimeAttemptIdentity, "organizationId" | "customerId" | "connectionId" | "requestKey"> & { readonly code: CoraRuntimeFailureCode; readonly terminal: boolean; readonly completedAtMs: number }): Promise<void> {
    const token = this.leases.get(input.requestKey); if (token === undefined || !Number.isSafeInteger(input.completedAtMs) || input.completedAtMs < 0) reject("LEASE_LOST"); const result = await (await this.ready()).prepare(`UPDATE finops_cora_runtime_attempts SET state=?,lease_token=NULL,lease_expires_at=NULL,generation_id=NULL,failure_code=?,completed_at=?,updated_at=? WHERE request_key=? AND org_id=? AND customer_id=? AND connection_id=? AND state='IN_PROGRESS' AND lease_token=?`).bind(input.terminal ? "FAILED" : "RETRYABLE_FAILED", input.code, input.completedAtMs, input.completedAtMs, input.requestKey, input.organizationId, input.customerId, input.connectionId, token).run(); if ((result.meta?.changes ?? 0) !== 1) reject("LEASE_LOST"); this.leases.delete(input.requestKey);
  }
}
