/** Durable trusted boundary and crash-safe replay ledger for ADD-05. */
import { getRawDb } from "./index";
import { ensureRuntimeSchema } from "./runtime-migrations";
import { AwsMarketplaceSpgRepository, type AwsMarketplaceSpgPersistenceScope, type StoredAwsMarketplaceSpgSnapshot } from "./finops-marketplace-spg-repository.ts";
import { normalizeAwsMarketplaceSpgCapture } from "../lib/finops-marketplace-spg.ts";
import type { MarketplaceSpgAcceptedRuntimeAttempt, MarketplaceSpgImmutableEvidenceHandoff, MarketplaceSpgRuntimeFailureCode, MarketplaceSpgServerBoundary } from "../lib/finops-marketplace-spg-runtime-binding.ts";

const IDENTIFIER=/^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,255}$/u, CONNECTION=/^conn_[a-f0-9]{32}$/u, REQUEST=/^mpr_[a-f0-9]{64}$/u, SHA=/^[a-f0-9]{64}$/u;
const MAX_SCOPES=10_000, LEASE_MS=20*60*1_000;
interface BoundaryRow { org_id:string; customer_id:string; connection_id:string; boundary_json:string; content_sha256:string }
interface AttemptRow { request_id:string; org_id:string; customer_id:string; connection_id:string; scheduled_window:string|null; source_boundary_sha256:string|null; state:"IN_PROGRESS"|"SUCCEEDED"|"FAILED"; failure_code:MarketplaceSpgRuntimeFailureCode|null; generation_id:string|null; evidence_generation_id:string|null; evidence_object_id:string|null; evidence_content_sha256:string|null; evidence_reference_ciphertext:string|null; evidence_reference_key_version:string|null; lease_token_sha256:string; lease_expires_at:number|string; started_at:number|string; completed_at:number|string|null; updated_at:number|string }
export interface MarketplaceSpgRuntimeStatus { readonly state:"unavailable"|"collecting"|"failed"|"ready"; readonly reason:string; readonly lastAttemptAt:string|null }
export class MarketplaceSpgRuntimeRepositoryError extends Error { public readonly code:"INVALID_INPUT"|"SCOPE_NOT_FOUND"|"STORED_STATE_INVALID"|"BOUND_REACHED"|"ATTEMPT_IN_PROGRESS"|"LEASE_LOST"; public constructor(code:MarketplaceSpgRuntimeRepositoryError["code"]){super("Marketplace SPG durable runtime rejected");this.name="MarketplaceSpgRuntimeRepositoryError";this.code=code;} }
function reject(code:MarketplaceSpgRuntimeRepositoryError["code"]):never{throw new MarketplaceSpgRuntimeRepositoryError(code)}
function valid(scope:AwsMarketplaceSpgPersistenceScope){return IDENTIFIER.test(scope.organizationId)&&IDENTIFIER.test(scope.customerId)&&CONNECTION.test(scope.connectionId)}
function integer(value:number|string){const parsed=typeof value==="string"?Number(value):value;if(!Number.isSafeInteger(parsed)||parsed<0)reject("STORED_STATE_INVALID");return parsed}
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
const LIVE=`FROM aws_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status IN ('active','trial') WHERE c.source_kind='aws_trust_role' AND c.status='active' AND c.partition='aws' AND c.permission_pack_version='standard-2026-08.13'`;
export class MarketplaceSpgRuntimeRepository implements MarketplaceSpgImmutableEvidenceHandoff {
  private readonly snapshots:AwsMarketplaceSpgRepository; private readonly leases=new Map<string,string>(); private readonly now:()=>number;
  public constructor(private readonly database:D1Database=getRawDb(), options:{readonly now?:()=>number;readonly skipRuntimeSchema?:boolean}={}){this.snapshots=new AwsMarketplaceSpgRepository(database);this.now=options.now??Date.now;this.skip=options.skipRuntimeSchema??false} private readonly skip:boolean;
  private async ready(){if(!this.skip)await ensureRuntimeSchema(this.database);return this.database} private clock(){const value=this.now();if(!Number.isSafeInteger(value)||value<0)reject("INVALID_INPUT");return value}
  private async scope(scope:AwsMarketplaceSpgPersistenceScope){if(!valid(scope))reject("INVALID_INPUT");const row=await(await this.ready()).prepare(`SELECT c.id ${LIVE} AND c.org_id=? AND c.customer_id=? AND c.id=? LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId).first<{id:string}>();if(row===null)reject("SCOPE_NOT_FOUND")}
  public async listEligibleScopes(limit=MAX_SCOPES){if(!Number.isSafeInteger(limit)||limit<1||limit>MAX_SCOPES)reject("INVALID_INPUT");const rows=await(await this.ready()).prepare(`SELECT c.org_id,c.customer_id,c.id AS connection_id ${LIVE} AND EXISTS(SELECT 1 FROM finops_marketplace_spg_runtime_boundaries b WHERE b.org_id=c.org_id AND b.customer_id=c.customer_id AND b.connection_id=c.id) ORDER BY c.id LIMIT ?`).bind(limit+1).all<{org_id:string;customer_id:string;connection_id:string}>();if((rows.results??[]).length>limit)reject("BOUND_REACHED");return Object.freeze((rows.results??[]).map(row=>Object.freeze({organizationId:row.org_id,customerId:row.customer_id,connectionId:row.connection_id})))}
  public async loadBoundary(scope:AwsMarketplaceSpgPersistenceScope):Promise<MarketplaceSpgServerBoundary|null>{await this.scope(scope);const row=await(await this.ready()).prepare(`SELECT b.* FROM finops_marketplace_spg_runtime_boundaries b WHERE b.org_id=? AND b.customer_id=? AND b.connection_id=? LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId).first<BoundaryRow>();if(row===null)return null;if(!SHA.test(row.content_sha256)||await sha256(row.boundary_json)!==row.content_sha256)reject("STORED_STATE_INVALID");let parsed:unknown;try{parsed=JSON.parse(row.boundary_json)}catch{reject("STORED_STATE_INVALID")}return parsed as MarketplaceSpgServerBoundary}
  private accepted(row:AttemptRow,snapshot:StoredAwsMarketplaceSpgSnapshot):MarketplaceSpgAcceptedRuntimeAttempt{if(row.state!=="SUCCEEDED"||row.scheduled_window===null||row.source_boundary_sha256===null||row.generation_id!==snapshot.generationId||row.evidence_generation_id===null||row.evidence_object_id===null||row.evidence_content_sha256===null||row.evidence_reference_ciphertext===null||row.evidence_reference_key_version===null)reject("STORED_STATE_INVALID");return Object.freeze({requestId:row.request_id,scheduledWindow:row.scheduled_window,sourceBoundarySha256:row.source_boundary_sha256,snapshot,evidence:Object.freeze({generationId:row.evidence_generation_id,objectId:row.evidence_object_id,contentSha256:row.evidence_content_sha256,reference:Object.freeze({ciphertext:row.evidence_reference_ciphertext,keyVersion:row.evidence_reference_key_version})})})}
  public async getAccepted(scope:AwsMarketplaceSpgPersistenceScope,requestId:string){if(!valid(scope)||!REQUEST.test(requestId))reject("INVALID_INPUT");await this.scope(scope);const db=await this.ready();const row=await db.prepare(`SELECT * FROM finops_marketplace_spg_runtime_attempts WHERE request_id=? AND org_id=? AND customer_id=? AND connection_id=? LIMIT 1`).bind(requestId,scope.organizationId,scope.customerId,scope.connectionId).first<AttemptRow>();if(row?.state==="SUCCEEDED"){if(row.generation_id===null)reject("STORED_STATE_INVALID");const snapshot=await this.snapshots.getSnapshotByGeneration(scope,row.generation_id);if(snapshot===null)reject("STORED_STATE_INVALID");return this.accepted(row,snapshot)}const now=this.clock();if(row?.state==="IN_PROGRESS"&&integer(row.lease_expires_at)>now)reject("ATTEMPT_IN_PROGRESS");const lease=await sha256(crypto.randomUUID());if(row===null){await db.prepare(`INSERT INTO finops_marketplace_spg_runtime_attempts(request_id,org_id,customer_id,connection_id,scheduled_window,source_boundary_sha256,state,failure_code,generation_id,evidence_generation_id,evidence_object_id,evidence_content_sha256,evidence_reference_ciphertext,evidence_reference_key_version,lease_token_sha256,lease_expires_at,started_at,completed_at,updated_at)VALUES(?,?,?,?,NULL,NULL,'IN_PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,?,?,?,NULL,?)`).bind(requestId,scope.organizationId,scope.customerId,scope.connectionId,lease,now+LEASE_MS,now,now).run()}else{const changed=await db.prepare(`UPDATE finops_marketplace_spg_runtime_attempts SET state='IN_PROGRESS',failure_code=NULL,lease_token_sha256=?,lease_expires_at=?,completed_at=NULL,updated_at=? WHERE request_id=? AND state='FAILED'`).bind(lease,now+LEASE_MS,now,requestId).run();if((changed.meta?.changes??0)!==1)reject("LEASE_LOST")}this.leases.set(requestId,lease);return null}
  public async commit(input:Parameters<MarketplaceSpgImmutableEvidenceHandoff["commit"]>[0]){const lease=this.leases.get(input.requestId);if(lease===undefined)reject("LEASE_LOST");const normalized=normalizeAwsMarketplaceSpgCapture(input.capture,input.trustedScope,input.nowMs);if(JSON.stringify(normalized)!==JSON.stringify(input.normalizedSnapshot))reject("INVALID_INPUT");const stored=await this.snapshots.recordCapture(input.trustedScope,input.capture,input.nowMs);const changed=await(await this.ready()).prepare(`UPDATE finops_marketplace_spg_runtime_attempts SET scheduled_window=?,source_boundary_sha256=?,state='SUCCEEDED',failure_code=NULL,generation_id=?,evidence_generation_id=?,evidence_object_id=?,evidence_content_sha256=?,evidence_reference_ciphertext=?,evidence_reference_key_version=?,completed_at=?,updated_at=? WHERE request_id=? AND state='IN_PROGRESS' AND lease_token_sha256=? AND lease_expires_at>=?`).bind(input.scheduledWindow,input.sourceBoundarySha256,stored.snapshot.generationId,input.evidence.generationId,input.evidence.objectId,input.evidence.contentSha256,input.evidence.reference.ciphertext,input.evidence.reference.keyVersion,input.nowMs,input.nowMs,input.requestId,lease,input.nowMs).run();if((changed.meta?.changes??0)!==1)reject("LEASE_LOST");this.leases.delete(input.requestId);const row=await(await this.ready()).prepare(`SELECT * FROM finops_marketplace_spg_runtime_attempts WHERE request_id=?`).bind(input.requestId).first<AttemptRow>();if(row===null)reject("STORED_STATE_INVALID");return Object.freeze({accepted:this.accepted(row,stored.snapshot),becameActive:stored.becameActive})}
  public async recordFailure(input:Parameters<MarketplaceSpgImmutableEvidenceHandoff["recordFailure"]>[0]){const lease=this.leases.get(input.requestId);if(lease===undefined)reject("LEASE_LOST");const result=await(await this.ready()).prepare(`UPDATE finops_marketplace_spg_runtime_attempts SET scheduled_window=COALESCE(scheduled_window,?),state='FAILED',failure_code=?,completed_at=?,updated_at=? WHERE request_id=? AND state='IN_PROGRESS' AND lease_token_sha256=?`).bind(input.scheduledWindow,input.code,input.completedAtMs,input.completedAtMs,input.requestId,lease).run();if((result.meta?.changes??0)!==1)reject("LEASE_LOST");this.leases.delete(input.requestId)}
  public async getRuntimeStatus(scope:AwsMarketplaceSpgPersistenceScope):Promise<MarketplaceSpgRuntimeStatus>{await this.scope(scope);const row=await(await this.ready()).prepare(`SELECT * FROM finops_marketplace_spg_runtime_attempts WHERE org_id=? AND customer_id=? AND connection_id=? ORDER BY updated_at DESC,request_id DESC LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId).first<AttemptRow>();if(row===null)return{state:"unavailable",reason:"MARKETPLACE_COLLECTION_NOT_STARTED",lastAttemptAt:null};const at=new Date(integer(row.updated_at)).toISOString();if(row.state==="IN_PROGRESS")return integer(row.lease_expires_at)>this.clock()?{state:"collecting",reason:"MARKETPLACE_COLLECTION_IN_PROGRESS",lastAttemptAt:at}:{state:"failed",reason:"MARKETPLACE_COLLECTION_LEASE_EXPIRED",lastAttemptAt:at};if(row.state==="FAILED")return{state:"failed",reason:row.failure_code??"MARKETPLACE_COLLECTION_FAILED",lastAttemptAt:at};return{state:"ready",reason:"MARKETPLACE_COLLECTION_READY",lastAttemptAt:at}}
}
