/** Immutable tenant-scoped persistence for normalized Amazon Connect cost snapshots. */
import { normalizeAmazonConnectCostInsightCapture, type AmazonConnectCostInsightCapture, type AmazonConnectCostInsightSnapshot, type AmazonConnectScope } from "../lib/finops-amazon-connect-cost-insight.ts";
import { getRawDb } from "./index"; import { ensureRuntimeSchema } from "./runtime-migrations";
const ID=/^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,255}$/u, CONNECTION=/^conn_[a-f0-9]{32}$/u, GENERATION=/^acig_[a-f0-9]{64}$/u, CAPTURE=/^connect_[a-f0-9]{64}$/u, SHA=/^[a-f0-9]{64}$/u; const MAX=80*1_024*1_024;
export interface AmazonConnectCostInsightPersistenceScope { readonly organizationId:string; readonly customerId:string; readonly connectionId:string; }
export interface StoredAmazonConnectCostInsightSnapshot { readonly scope:AmazonConnectCostInsightPersistenceScope; readonly generationId:string; readonly contentSha256:string; readonly snapshot:AmazonConnectCostInsightSnapshot; readonly createdAtIso:string; readonly committedAtIso:string|null; }
export interface AmazonConnectCostInsightHistoryItem { readonly generationId:string; readonly captureId:string; readonly state:string; readonly completedAtIso:string; readonly dataThroughAtIso:string; readonly instanceCount:number; readonly phoneAggregateCount:number; readonly costRowCount:number; readonly currency:string; readonly costBasis:string; }
export class AmazonConnectCostInsightRepositoryError extends Error { public readonly code:"INVALID_INPUT"|"SCOPE_NOT_FOUND"|"IMMUTABLE_CONFLICT"|"STORED_STATE_INVALID"; public constructor(code:AmazonConnectCostInsightRepositoryError["code"]){super("Amazon Connect cost persistence rejected");this.name="AmazonConnectCostInsightRepositoryError";this.code=code;} }
interface Row {generation_id:string;org_id:string;customer_id:string;connection_id:string;account_id:string;partition:AmazonConnectScope["partition"];region:string;source_capture_id:string;source_state:AmazonConnectCostInsightSnapshot["state"];complete:number|string;content_sha256:string;snapshot_json:string;completed_at:string;data_through_at:string;billing_generation_id:string;billing_manifest_sha256:string;instance_count:number|string;phone_aggregate_count:number|string;cost_row_count:number|string;created_at:number|string;advanced_at?:number|string|null}
function reject(code:AmazonConnectCostInsightRepositoryError["code"]="INVALID_INPUT"):never{throw new AmazonConnectCostInsightRepositoryError(code);} function scopeValid(s:AmazonConnectCostInsightPersistenceScope){if(!ID.test(s.organizationId)||!ID.test(s.customerId)||!CONNECTION.test(s.connectionId))reject();}
function integer(v:unknown){const n=typeof v==="string"?Number(v):v;if(typeof n!=="number"||!Number.isSafeInteger(n)||n<0)reject("STORED_STATE_INVALID");return n;}
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function materialize(row:Row):Promise<StoredAmazonConnectCostInsightSnapshot>{if(!GENERATION.test(row.generation_id)||!CAPTURE.test(row.source_capture_id)||!SHA.test(row.content_sha256)||new TextEncoder().encode(row.snapshot_json).byteLength>MAX)reject("STORED_STATE_INVALID");let snapshot:AmazonConnectCostInsightSnapshot;try{snapshot=JSON.parse(row.snapshot_json) as AmazonConnectCostInsightSnapshot;}catch{reject("STORED_STATE_INVALID");}
  const phoneCount=snapshot.collections.reduce((sum,item)=>sum+item.phoneInventory.length,0);if(snapshot.scope.orgId!==row.org_id||snapshot.scope.customerId!==row.customer_id||snapshot.scope.connectionId!==row.connection_id||snapshot.scope.accountId!==row.account_id||snapshot.scope.partition!==row.partition||snapshot.scope.region!==row.region||snapshot.captureId!==row.source_capture_id||snapshot.state!==row.source_state||Number(snapshot.complete)!==integer(row.complete)||snapshot.completedAtIso!==row.completed_at||snapshot.costEvidence.dataThroughAtIso!==row.data_through_at||snapshot.costEvidence.generationId!==row.billing_generation_id||snapshot.costEvidence.manifestSha256!==row.billing_manifest_sha256||snapshot.collections.filter(x=>x.instance!==null).length!==integer(row.instance_count)||phoneCount!==integer(row.phone_aggregate_count)||snapshot.costEvidence.rows.length!==integer(row.cost_row_count)||await sha256(row.snapshot_json)!==row.content_sha256||row.generation_id!==`acig_${row.content_sha256}`)reject("STORED_STATE_INVALID");
  const created=integer(row.created_at),advanced=row.advanced_at==null?null:integer(row.advanced_at);return{scope:{organizationId:row.org_id,customerId:row.customer_id,connectionId:row.connection_id},generationId:row.generation_id,contentSha256:row.content_sha256,snapshot,createdAtIso:new Date(created).toISOString(),committedAtIso:advanced===null?null:new Date(advanced).toISOString()};}
function history(x:StoredAmazonConnectCostInsightSnapshot):AmazonConnectCostInsightHistoryItem{return{generationId:x.generationId,captureId:x.snapshot.captureId,state:x.snapshot.state,completedAtIso:x.snapshot.completedAtIso,dataThroughAtIso:x.snapshot.costEvidence.dataThroughAtIso,instanceCount:x.snapshot.collections.filter(y=>y.instance!==null).length,phoneAggregateCount:x.snapshot.collections.reduce((s,y)=>s+y.phoneInventory.length,0),costRowCount:x.snapshot.costEvidence.rows.length,currency:x.snapshot.costEvidence.currency,costBasis:x.snapshot.costEvidence.costBasis};}
const LIVE=`JOIN aws_connections c ON c.id=s.connection_id AND c.org_id=s.org_id AND c.customer_id=s.customer_id AND c.aws_account_id=s.account_id AND c.partition=s.partition JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status='active'`;
export class AmazonConnectCostInsightRepository { public constructor(private readonly db:D1Database=getRawDb()){} private async live(s:AmazonConnectCostInsightPersistenceScope){scopeValid(s);await ensureRuntimeSchema(this.db);const row=await this.db.prepare(`SELECT c.id FROM aws_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status='active' WHERE c.org_id=? AND c.customer_id=? AND c.id=? AND c.source_kind='aws_trust_role' AND c.status='active' LIMIT 1`).bind(s.organizationId,s.customerId,s.connectionId).first();if(row===null)reject("SCOPE_NOT_FOUND");return this.db;}
  private async byGeneration(db:D1Database,s:AmazonConnectCostInsightPersistenceScope,id:string){const row=await db.prepare(`SELECT s.* FROM finops_amazon_connect_cost_snapshots s ${LIVE} WHERE s.org_id=? AND s.customer_id=? AND s.connection_id=? AND s.generation_id=? AND c.source_kind='aws_trust_role' AND c.status='active' LIMIT 1`).bind(s.organizationId,s.customerId,s.connectionId,id).first<Row>();return row===null?null:materialize(row);}
  public async recordCapture(expectedScope:AmazonConnectScope,capture:AmazonConnectCostInsightCapture,nowMs=Date.now()){const s={organizationId:expectedScope.orgId,customerId:expectedScope.customerId,connectionId:expectedScope.connectionId};scopeValid(s);if(!Number.isSafeInteger(nowMs)||nowMs<0)reject();const completed=Date.parse(capture.completedAtIso);if(!Number.isFinite(completed)||completed>nowMs+300000)reject();const snapshot=normalizeAmazonConnectCostInsightCapture(capture,expectedScope,completed),json=JSON.stringify(snapshot);if(new TextEncoder().encode(json).byteLength>MAX)reject();const digest=await sha256(json),id=`acig_${digest}`,db=await this.live(s),before=await this.getActiveSnapshot(s),phones=snapshot.collections.reduce((sum,x)=>sum+x.phoneInventory.length,0);
    const statements=[db.prepare(`INSERT INTO finops_amazon_connect_cost_snapshots (generation_id,org_id,customer_id,connection_id,account_id,partition,region,source_capture_id,source_state,complete,content_sha256,snapshot_json,completed_at,data_through_at,billing_generation_id,billing_manifest_sha256,instance_count,phone_aggregate_count,cost_row_count,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING`).bind(id,s.organizationId,s.customerId,s.connectionId,snapshot.scope.accountId,snapshot.scope.partition,snapshot.scope.region,snapshot.captureId,snapshot.state,snapshot.complete?1:0,digest,json,snapshot.completedAtIso,snapshot.costEvidence.dataThroughAtIso,snapshot.costEvidence.generationId,snapshot.costEvidence.manifestSha256,snapshot.collections.filter(x=>x.instance!==null).length,phones,snapshot.costEvidence.rows.length,nowMs)];
    if(snapshot.complete)statements.push(db.prepare(`INSERT INTO finops_amazon_connect_cost_heads (org_id,customer_id,connection_id,active_generation_id,advanced_at) VALUES (?,?,?,?,?) ON CONFLICT (org_id,customer_id,connection_id) DO UPDATE SET active_generation_id=excluded.active_generation_id,advanced_at=excluded.advanced_at WHERE excluded.active_generation_id<>finops_amazon_connect_cost_heads.active_generation_id AND EXISTS (SELECT 1 FROM finops_amazon_connect_cost_snapshots candidate JOIN finops_amazon_connect_cost_snapshots active ON active.generation_id=finops_amazon_connect_cost_heads.active_generation_id WHERE candidate.generation_id=excluded.active_generation_id AND candidate.org_id=finops_amazon_connect_cost_heads.org_id AND candidate.customer_id=finops_amazon_connect_cost_heads.customer_id AND candidate.connection_id=finops_amazon_connect_cost_heads.connection_id AND candidate.completed_at>active.completed_at)`).bind(s.organizationId,s.customerId,s.connectionId,id,nowMs));await db.batch(statements);const stored=await this.byGeneration(db,s,id);if(stored===null)reject("IMMUTABLE_CONFLICT");const active=await this.getActiveSnapshot(s);return{snapshot:stored,becameActive:active?.generationId===id&&before?.generationId!==id};}
  public async getActiveSnapshot(s:AmazonConnectCostInsightPersistenceScope){const db=await this.live(s),row=await db.prepare(`SELECT s.*,h.advanced_at FROM finops_amazon_connect_cost_heads h JOIN finops_amazon_connect_cost_snapshots s ON s.generation_id=h.active_generation_id AND s.org_id=h.org_id AND s.customer_id=h.customer_id AND s.connection_id=h.connection_id ${LIVE} WHERE h.org_id=? AND h.customer_id=? AND h.connection_id=? AND c.source_kind='aws_trust_role' AND c.status='active' LIMIT 1`).bind(s.organizationId,s.customerId,s.connectionId).first<Row>();return row===null?null:materialize(row);}
  public async getLatestSnapshot(s:AmazonConnectCostInsightPersistenceScope){const db=await this.live(s),row=await db.prepare(`SELECT s.* FROM finops_amazon_connect_cost_snapshots s ${LIVE} WHERE s.org_id=? AND s.customer_id=? AND s.connection_id=? AND c.source_kind='aws_trust_role' AND c.status='active' ORDER BY s.completed_at DESC,s.generation_id DESC LIMIT 1`).bind(s.organizationId,s.customerId,s.connectionId).first<Row>();return row===null?null:materialize(row);}
  public async listHistory(s:AmazonConnectCostInsightPersistenceScope,limit=30):Promise<readonly AmazonConnectCostInsightHistoryItem[]>{if(!Number.isSafeInteger(limit)||limit<1||limit>93)reject();const db=await this.live(s),rows=await db.prepare(`SELECT s.* FROM finops_amazon_connect_cost_snapshots s ${LIVE} WHERE s.org_id=? AND s.customer_id=? AND s.connection_id=? AND c.source_kind='aws_trust_role' AND c.status='active' ORDER BY s.completed_at DESC,s.generation_id DESC LIMIT ?`).bind(s.organizationId,s.customerId,s.connectionId,limit).all<Row>();return Promise.all((rows.results??[]).map(async r=>history(await materialize(r))));}
}
