/** Immutable, provider-specific persistence for GCP Cloud Billing exports. */
import { normalizeGcpBillingExportCapture, validateGcpBillingScope, type GcpBillingExportCapture, type GcpBillingScope, type GcpBillingSnapshot } from "../lib/finops-gcp-cloud-intelligence.ts";
import { getRawDb } from "./index";
import { ensureRuntimeSchema } from "./runtime-migrations";

const SAFE=/^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,255}$/u,CONNECTION=/^gcpconn_[a-f0-9]{32}$/u,GENERATION=/^gcpg_[a-f0-9]{64}$/u,SHA=/^[a-f0-9]{64}$/u;
const MAX=256*1_024*1_024;
export interface GcpBillingPersistenceScope{readonly organizationId:string;readonly customerId:string;readonly connectionId:string;}
export interface GcpBillingConnection{readonly id:string;readonly orgId:string;readonly customerId:string;readonly billingAccountId:string;readonly exportProjectId:string;readonly datasetId:string;readonly billingTableId:string;readonly pricingProjectId:string;readonly pricingDatasetId:string;readonly pricingTableId:string;readonly location:string;readonly identityBindingId:string;readonly status:"pending"|"active"|"disabled";}
export interface StoredGcpBillingSnapshot{readonly scope:GcpBillingPersistenceScope;readonly generationId:string;readonly contentSha256:string;readonly snapshot:GcpBillingSnapshot;readonly createdAtIso:string;readonly committedAtIso:string|null;}
export interface GcpBillingHistoryItem{readonly generationId:string;readonly captureId:string;readonly sourceState:string;readonly complete:boolean;readonly completedAt:string;readonly dataThroughAt:string|null;readonly billingRowCount:number;readonly opportunityRowCount:number;}
export class GcpBillingRepositoryError extends Error{public readonly code:"INVALID_INPUT"|"SCOPE_NOT_FOUND"|"IMMUTABLE_CONFLICT"|"STORED_STATE_INVALID";public constructor(code:GcpBillingRepositoryError["code"]){super("GCP billing persistence rejected");this.name="GcpBillingRepositoryError";this.code=code;}}
interface ConnectionRow{id:string;org_id:string;customer_id:string;billing_account_id:string;export_project_id:string;dataset_id:string;billing_table_id:string;pricing_project_id:string;pricing_dataset_id:string;pricing_table_id:string;location:string;identity_binding_id:string;status:GcpBillingConnection["status"]}
interface SnapshotRow{generation_id:string;org_id:string;customer_id:string;connection_id:string;billing_account_id:string;capture_id:string;source_state:GcpBillingSnapshot["sourceState"];complete:number|string;content_sha256:string;snapshot_json:string;completed_at:string;data_through_at:string|null;billing_row_count:number|string;opportunity_row_count:number|string;created_at:number|string;advanced_at?:number|string|null}
function reject(code:GcpBillingRepositoryError["code"]="INVALID_INPUT"):never{throw new GcpBillingRepositoryError(code)}
function scopeValid(scope:GcpBillingPersistenceScope){if(!SAFE.test(scope.organizationId)||!SAFE.test(scope.customerId)||!CONNECTION.test(scope.connectionId))reject()}
function integer(value:unknown){const parsed=typeof value==="string"?Number(value):value;if(typeof parsed!=="number"||!Number.isSafeInteger(parsed)||parsed<0)reject("STORED_STATE_INVALID");return parsed}
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(item=>item.toString(16).padStart(2,"0")).join("")}
function connection(row:ConnectionRow):GcpBillingConnection{return{id:row.id,orgId:row.org_id,customerId:row.customer_id,billingAccountId:row.billing_account_id,exportProjectId:row.export_project_id,datasetId:row.dataset_id,billingTableId:row.billing_table_id,pricingProjectId:row.pricing_project_id,pricingDatasetId:row.pricing_dataset_id,pricingTableId:row.pricing_table_id,location:row.location,identityBindingId:row.identity_binding_id,status:row.status}}
function expected(connection:GcpBillingConnection):GcpBillingScope{return{orgId:connection.orgId,customerId:connection.customerId,connectionId:connection.id,provider:"GCP",billingAccountId:connection.billingAccountId,exportProjectId:connection.exportProjectId,datasetId:connection.datasetId,billingTableId:connection.billingTableId,pricingProjectId:connection.pricingProjectId,pricingDatasetId:connection.pricingDatasetId,pricingTableId:connection.pricingTableId,location:connection.location}}
async function materialize(row:SnapshotRow):Promise<StoredGcpBillingSnapshot>{if(!GENERATION.test(row.generation_id)||!SHA.test(row.content_sha256)||new TextEncoder().encode(row.snapshot_json).byteLength>MAX)reject("STORED_STATE_INVALID");let snapshot:GcpBillingSnapshot;try{snapshot=JSON.parse(row.snapshot_json) as GcpBillingSnapshot}catch{reject("STORED_STATE_INVALID")}
  const{sourceState,complete,limitations,schemaVersion,...captureRest}=snapshot;if(schemaVersion!=="sutra.gcp-cloud-billing-snapshot.v1"||!Array.isArray(limitations))reject("STORED_STATE_INVALID");const capture={...captureRest,schemaVersion:"sutra.gcp-cloud-billing-export.v1" as const};let normalized:GcpBillingSnapshot;try{normalized=normalizeGcpBillingExportCapture(capture,snapshot.scope,Date.parse(snapshot.completedAt)+300_000)}catch{reject("STORED_STATE_INVALID")}
  if(normalized.sourceState!==sourceState||normalized.complete!==complete||snapshot.scope.orgId!==row.org_id||snapshot.scope.customerId!==row.customer_id||snapshot.scope.connectionId!==row.connection_id||snapshot.scope.billingAccountId!==row.billing_account_id||snapshot.captureId!==row.capture_id||snapshot.sourceState!==row.source_state||Number(snapshot.complete)!==integer(row.complete)||snapshot.completedAt!==row.completed_at||snapshot.dataThroughAt!==row.data_through_at||snapshot.rows.length!==integer(row.billing_row_count)||snapshot.opportunities.rows.length!==integer(row.opportunity_row_count)||await sha256(row.snapshot_json)!==row.content_sha256||row.generation_id!==`gcpg_${row.content_sha256}`)reject("STORED_STATE_INVALID");
  const created=integer(row.created_at),advanced=row.advanced_at==null?null:integer(row.advanced_at);return{scope:{organizationId:row.org_id,customerId:row.customer_id,connectionId:row.connection_id},generationId:row.generation_id,contentSha256:row.content_sha256,snapshot,createdAtIso:new Date(created).toISOString(),committedAtIso:advanced===null?null:new Date(advanced).toISOString()}}
function history(item:StoredGcpBillingSnapshot):GcpBillingHistoryItem{return{generationId:item.generationId,captureId:item.snapshot.captureId,sourceState:item.snapshot.sourceState,complete:item.snapshot.complete,completedAt:item.snapshot.completedAt,dataThroughAt:item.snapshot.dataThroughAt,billingRowCount:item.snapshot.rows.length,opportunityRowCount:item.snapshot.opportunities.rows.length}}
const LIVE=`JOIN gcp_billing_connections c ON c.id=s.connection_id AND c.org_id=s.org_id AND c.customer_id=s.customer_id AND c.billing_account_id=s.billing_account_id JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status='active'`;
export class GcpCloudIntelligenceRepository{
  public constructor(private readonly db:D1Database=getRawDb()){}
  public async listConnectionsForOrg(orgId:string):Promise<readonly GcpBillingConnection[]>{if(!SAFE.test(orgId))reject();await ensureRuntimeSchema(this.db);const rows=await this.db.prepare(`SELECT c.* FROM gcp_billing_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status='active' WHERE c.org_id=? AND c.provider='GCP' AND c.status='active' ORDER BY c.billing_account_id,c.id`).bind(orgId).all<ConnectionRow>();return(rows.results??[]).map(connection)}
  public async getConnectionForOrg(orgId:string,connectionId:string):Promise<GcpBillingConnection|null>{if(!SAFE.test(orgId)||!CONNECTION.test(connectionId))reject();await ensureRuntimeSchema(this.db);const row=await this.db.prepare(`SELECT c.* FROM gcp_billing_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status='active' WHERE c.org_id=? AND c.id=? AND c.provider='GCP' AND c.status='active' LIMIT 1`).bind(orgId,connectionId).first<ConnectionRow>();return row===null?null:connection(row)}
  private async live(scope:GcpBillingPersistenceScope){scopeValid(scope);const found=await this.getConnectionForOrg(scope.organizationId,scope.connectionId);if(found===null||found.customerId!==scope.customerId)reject("SCOPE_NOT_FOUND");return{db:this.db,connection:found}}
  private async byGeneration(db:D1Database,scope:GcpBillingPersistenceScope,generationId:string){const row=await db.prepare(`SELECT s.* FROM finops_gcp_billing_snapshots s ${LIVE} WHERE s.org_id=? AND s.customer_id=? AND s.connection_id=? AND s.generation_id=? AND c.provider='GCP' AND c.status='active' LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId,generationId).first<SnapshotRow>();return row===null?null:materialize(row)}
  public async recordCapture(expectedScope:GcpBillingScope,capture:GcpBillingExportCapture,nowMs=Date.now()){validateGcpBillingScope(expectedScope);if(!Number.isSafeInteger(nowMs)||nowMs<0)reject();const scope={organizationId:expectedScope.orgId,customerId:expectedScope.customerId,connectionId:expectedScope.connectionId},live=await this.live(scope);if(JSON.stringify(expected(live.connection))!==JSON.stringify(expectedScope))reject("SCOPE_NOT_FOUND");const snapshot=normalizeGcpBillingExportCapture(capture,expectedScope,nowMs),json=JSON.stringify(snapshot);if(new TextEncoder().encode(json).byteLength>MAX)reject();const digest=await sha256(json),generationId=`gcpg_${digest}`,before=await this.getActiveSnapshot(scope);
    const statements=[live.db.prepare(`INSERT INTO finops_gcp_billing_snapshots(generation_id,org_id,customer_id,connection_id,billing_account_id,capture_id,source_state,complete,content_sha256,snapshot_json,completed_at,data_through_at,billing_row_count,opportunity_row_count,created_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)ON CONFLICT DO NOTHING`).bind(generationId,scope.organizationId,scope.customerId,scope.connectionId,snapshot.scope.billingAccountId,snapshot.captureId,snapshot.sourceState,snapshot.complete?1:0,digest,json,snapshot.completedAt,snapshot.dataThroughAt,snapshot.rows.length,snapshot.opportunities.rows.length,nowMs)];
    if(snapshot.complete)statements.push(live.db.prepare(`INSERT INTO finops_gcp_billing_snapshot_heads(org_id,customer_id,connection_id,active_generation_id,advanced_at)VALUES(?,?,?,?,?)ON CONFLICT(org_id,customer_id,connection_id)DO UPDATE SET active_generation_id=excluded.active_generation_id,advanced_at=excluded.advanced_at WHERE excluded.active_generation_id<>finops_gcp_billing_snapshot_heads.active_generation_id AND EXISTS(SELECT 1 FROM finops_gcp_billing_snapshots candidate JOIN finops_gcp_billing_snapshots active ON active.generation_id=finops_gcp_billing_snapshot_heads.active_generation_id WHERE candidate.generation_id=excluded.active_generation_id AND candidate.org_id=finops_gcp_billing_snapshot_heads.org_id AND candidate.customer_id=finops_gcp_billing_snapshot_heads.customer_id AND candidate.connection_id=finops_gcp_billing_snapshot_heads.connection_id AND(candidate.completed_at>active.completed_at OR(candidate.completed_at=active.completed_at AND candidate.generation_id>active.generation_id)))`).bind(scope.organizationId,scope.customerId,scope.connectionId,generationId,nowMs));
    await live.db.batch(statements);const stored=await this.byGeneration(live.db,scope,generationId);if(stored===null)reject("IMMUTABLE_CONFLICT");const active=await this.getActiveSnapshot(scope);return{snapshot:stored,becameActive:active?.generationId===generationId&&before?.generationId!==generationId}}
  public async getActiveSnapshot(scope:GcpBillingPersistenceScope){const{db}=await this.live(scope),row=await db.prepare(`SELECT s.*,h.advanced_at FROM finops_gcp_billing_snapshot_heads h JOIN finops_gcp_billing_snapshots s ON s.generation_id=h.active_generation_id AND s.org_id=h.org_id AND s.customer_id=h.customer_id AND s.connection_id=h.connection_id ${LIVE} WHERE h.org_id=? AND h.customer_id=? AND h.connection_id=? AND c.provider='GCP' AND c.status='active' LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId).first<SnapshotRow>();return row===null?null:materialize(row)}
  public async getLatestSnapshot(scope:GcpBillingPersistenceScope){const{db}=await this.live(scope),row=await db.prepare(`SELECT s.* FROM finops_gcp_billing_snapshots s ${LIVE} WHERE s.org_id=? AND s.customer_id=? AND s.connection_id=? AND c.provider='GCP' AND c.status='active' ORDER BY s.completed_at DESC,s.generation_id DESC LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId).first<SnapshotRow>();return row===null?null:materialize(row)}
  public async listHistory(scope:GcpBillingPersistenceScope,limit=36):Promise<readonly GcpBillingHistoryItem[]>{if(!Number.isSafeInteger(limit)||limit<1||limit>120)reject();const{db}=await this.live(scope),rows=await db.prepare(`SELECT s.* FROM finops_gcp_billing_snapshots s ${LIVE} WHERE s.org_id=? AND s.customer_id=? AND s.connection_id=? AND c.provider='GCP' AND c.status='active' ORDER BY s.completed_at DESC,s.generation_id DESC LIMIT ?`).bind(scope.organizationId,scope.customerId,scope.connectionId,limit).all<SnapshotRow>();return Promise.all((rows.results??[]).map(async row=>history(await materialize(row))))}
}
