/** Immutable ADV-11 scheduler/broker attempt history. */
import { getRawDb } from "./index";
import { ensureRuntimeSchema } from "./runtime-migrations";
import type { EndUserComputingBoundary } from "../lib/finops-end-user-computing.ts";
import type { EndUserComputingRuntimeAttempt, EndUserComputingRuntimeAttemptStore, EndUserComputingRuntimeFailureCode } from "../lib/finops-end-user-computing-runtime-binding.ts";

const REQUEST=/^eur_[a-f0-9]{64}$/u,EXECUTION=/^eue_[a-f0-9]{64}$/u,JOB=/^job_[a-f0-9]{32}$/u;
const GENERATION=/^eucg_[a-f0-9]{64}$/u,CAPTURE=/^euc_[a-f0-9]{64}$/u,CUR=/^fbg_[a-f0-9]{64}$/u,SHA=/^[a-f0-9]{64}$/u;
const KEY=/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u,WINDOW=/^\d{4}-\d{2}-\d{2}T\d{2}:00:00\.000Z$/u;
const ID=/^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,127}$/u,CONNECTION=/^conn_[a-f0-9]{32}$/u,ACCOUNT=/^\d{12}$/u,REGION=/^[a-z]{2}(?:-gov)?-[a-z]+-\d$/u;
const STATES=["READY","PARTIAL","STALE","UNAVAILABLE","FAILED"] as const;
const FAILURES=["BROKER_AUTHENTICATION_FAILED","BROKER_TIMEOUT","BROKER_UNAVAILABLE","BROKER_RESPONSE_INVALID","SCOPE_REJECTED","PRIVACY_REJECTED","CUR2_LINEAGE_REJECTED","EVIDENCE_REJECTED","PERSISTENCE_REJECTED","INTERNAL_ERROR"] as const;

interface Row { execution_id:string;org_id:string;customer_id:string;connection_id:string;partition:EndUserComputingBoundary["partition"];boundary_sha256:string;account_count:number|string;region_count:number|string;request_id:string;job_id:string;job_attempt:number|string;scheduled_window:string;state:EndUserComputingRuntimeAttempt["state"];generation_id:string|null;capture_id:string|null;cur2_generation_id:string|null;cur2_projection_sha256:string|null;request_body_sha256:string|null;response_body_sha256:string|null;broker_key_id:string|null;failure_code:EndUserComputingRuntimeFailureCode|null;content_sha256:string;completed_at:number|string;created_at:number|string }
export interface StoredEndUserComputingRuntimeAttempt extends EndUserComputingRuntimeAttempt { readonly executionId:string;readonly boundarySha256:string;readonly jobId:string;readonly scheduledWindow:string;readonly cur2GenerationId:string|null;readonly cur2ProjectionSha256:string|null;readonly requestBodySha256:string|null;readonly responseBodySha256:string|null;readonly brokerKeyId:string|null;readonly contentSha256:string;readonly completedAtIso:string }
export class EndUserComputingRuntimeAttemptRepositoryError extends Error { constructor(public readonly code:"INVALID_INPUT"|"SCOPE_NOT_FOUND"|"IMMUTABLE_CONFLICT"|"STORED_STATE_INVALID"){super("End User Computing runtime attempt persistence rejected");this.name="EndUserComputingRuntimeAttemptRepositoryError"} }
function fail(code:EndUserComputingRuntimeAttemptRepositoryError["code"]="INVALID_INPUT"):never{throw new EndUserComputingRuntimeAttemptRepositoryError(code)}
async function sha(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(p=>p.toString(16).padStart(2,"0")).join("")}
function integer(value:number|string){const number=Number(value);if(!Number.isSafeInteger(number)||number<0)fail("STORED_STATE_INVALID");return number}
async function boundaryHash(boundary:EndUserComputingBoundary){return sha(JSON.stringify(boundary))}
function validBoundary(boundary:EndUserComputingBoundary){return ID.test(boundary.scope.orgId)&&ID.test(boundary.scope.customerId)&&CONNECTION.test(boundary.scope.connectionId)&&["aws","aws-us-gov","aws-cn"].includes(boundary.partition)&&boundary.accountIds.length>=1&&boundary.accountIds.length<=200&&boundary.accountIds.every(value=>ACCOUNT.test(value))&&new Set(boundary.accountIds).size===boundary.accountIds.length&&JSON.stringify(boundary.accountIds)===JSON.stringify([...boundary.accountIds].sort())&&boundary.regions.length>=1&&boundary.regions.length<=50&&boundary.regions.every(value=>REGION.test(value))&&new Set(boundary.regions).size===boundary.regions.length&&JSON.stringify(boundary.regions)===JSON.stringify([...boundary.regions].sort())}
function payload(row:Omit<Row,"execution_id"|"content_sha256"|"created_at">){return JSON.stringify({schema:"sutra.euc-runtime-attempt.v1",orgId:row.org_id,customerId:row.customer_id,connectionId:row.connection_id,partition:row.partition,boundarySha256:row.boundary_sha256,accountCount:Number(row.account_count),regionCount:Number(row.region_count),requestId:row.request_id,jobId:row.job_id,jobAttempt:Number(row.job_attempt),scheduledWindow:row.scheduled_window,state:row.state,generationId:row.generation_id,captureId:row.capture_id,cur2GenerationId:row.cur2_generation_id,cur2ProjectionSha256:row.cur2_projection_sha256,requestBodySha256:row.request_body_sha256,responseBodySha256:row.response_body_sha256,brokerKeyId:row.broker_key_id,failureCode:row.failure_code,completedAtMs:Number(row.completed_at)})}
function validOutcome(row:Row){const success=row.state!=="FAILED",attempt=integer(row.job_attempt),accounts=integer(row.account_count),regions=integer(row.region_count);return STATES.includes(row.state)&&WINDOW.test(row.scheduled_window)&&REQUEST.test(row.request_id)&&JOB.test(row.job_id)&&attempt>=1&&attempt<=25&&SHA.test(row.boundary_sha256)&&accounts>=1&&accounts<=200&&regions>=1&&regions<=50&&((row.cur2_generation_id===null&&row.cur2_projection_sha256===null)||(row.cur2_generation_id!==null&&CUR.test(row.cur2_generation_id)&&row.cur2_projection_sha256!==null&&SHA.test(row.cur2_projection_sha256)))&&(row.request_body_sha256===null||SHA.test(row.request_body_sha256))&&(success?row.generation_id!==null&&GENERATION.test(row.generation_id)&&row.capture_id!==null&&CAPTURE.test(row.capture_id)&&row.request_body_sha256!==null&&row.response_body_sha256!==null&&SHA.test(row.response_body_sha256)&&row.broker_key_id!==null&&KEY.test(row.broker_key_id)&&row.failure_code===null:row.generation_id===null&&row.capture_id===null&&row.response_body_sha256===null&&row.broker_key_id===null&&row.failure_code!==null&&FAILURES.includes(row.failure_code))}
async function materialize(row:Row,boundary:EndUserComputingBoundary):Promise<StoredEndUserComputingRuntimeAttempt>{if(!validBoundary(boundary)||!EXECUTION.test(row.execution_id)||!SHA.test(row.content_sha256)||!validOutcome(row)||row.org_id!==boundary.scope.orgId||row.customer_id!==boundary.scope.customerId||row.connection_id!==boundary.scope.connectionId||row.partition!==boundary.partition||Number(row.account_count)!==boundary.accountIds.length||Number(row.region_count)!==boundary.regions.length||integer(row.created_at)!==integer(row.completed_at)||row.boundary_sha256!==await boundaryHash(boundary))fail("STORED_STATE_INVALID");const content=await sha(payload(row));if(content!==row.content_sha256||row.execution_id!==`eue_${content}`)fail("STORED_STATE_INVALID");return{executionId:row.execution_id,boundarySha256:row.boundary_sha256,requestId:row.request_id,jobId:row.job_id,jobAttempt:integer(row.job_attempt),scheduledWindow:row.scheduled_window,state:row.state,generationId:row.generation_id,captureId:row.capture_id,cur2GenerationId:row.cur2_generation_id,cur2ProjectionSha256:row.cur2_projection_sha256,requestBodySha256:row.request_body_sha256,responseBodySha256:row.response_body_sha256,brokerKeyId:row.broker_key_id,failureCode:row.failure_code,contentSha256:content,completedAtIso:new Date(integer(row.completed_at)).toISOString()}}

const LIVE=`JOIN aws_connections c ON c.id=e.connection_id AND c.org_id=e.org_id AND c.customer_id=e.customer_id AND c.partition=e.partition AND c.source_kind='aws_trust_role' AND c.status='active' JOIN organizations o ON o.id=e.org_id AND o.status='active' JOIN customers cu ON cu.id=e.customer_id AND cu.org_id=e.org_id AND cu.status IN ('active','trial')`;
export class EndUserComputingRuntimeAttemptRepository implements EndUserComputingRuntimeAttemptStore{
  constructor(private readonly database:D1Database=getRawDb()){}
  private async ready(){await ensureRuntimeSchema(this.database);return this.database}
  async getAttempt(boundary:EndUserComputingBoundary,requestId:string,jobAttempt:number):Promise<StoredEndUserComputingRuntimeAttempt|null>{if(!validBoundary(boundary)||!REQUEST.test(requestId)||!Number.isSafeInteger(jobAttempt)||jobAttempt<1||jobAttempt>25)fail();const db=await this.ready();const row=await db.prepare(`SELECT e.* FROM finops_euc_runtime_attempts e ${LIVE} WHERE e.org_id=? AND e.customer_id=? AND e.connection_id=? AND e.partition=? AND e.request_id=? AND e.job_attempt=? LIMIT 1`).bind(boundary.scope.orgId,boundary.scope.customerId,boundary.scope.connectionId,boundary.partition,requestId,jobAttempt).first<Row>();return row===null?null:materialize(row,boundary)}
  async recordAttempt(input:Parameters<EndUserComputingRuntimeAttemptStore["recordAttempt"]>[0]):Promise<StoredEndUserComputingRuntimeAttempt>{
    if(!validBoundary(input.boundary))fail();const boundarySha256=await boundaryHash(input.boundary);const base={org_id:input.boundary.scope.orgId,customer_id:input.boundary.scope.customerId,connection_id:input.boundary.scope.connectionId,partition:input.boundary.partition,boundary_sha256:boundarySha256,account_count:input.boundary.accountIds.length,region_count:input.boundary.regions.length,request_id:input.requestId,job_id:input.jobId,job_attempt:input.jobAttempt,scheduled_window:input.scheduledWindow,state:input.state,generation_id:input.generationId,capture_id:input.captureId,cur2_generation_id:input.cur2GenerationId,cur2_projection_sha256:input.cur2ProjectionSha256,request_body_sha256:input.requestBodySha256,response_body_sha256:input.responseBodySha256,broker_key_id:input.brokerKeyId,failure_code:input.failureCode,completed_at:input.completedAtMs} satisfies Omit<Row,"execution_id"|"content_sha256"|"created_at">;
    const check={...base,execution_id:`eue_${"0".repeat(64)}`,content_sha256:"0".repeat(64),created_at:input.completedAtMs};if(!validOutcome(check))fail();const contentSha256=await sha(payload(base)),executionId=`eue_${contentSha256}`,db=await this.ready();
    await db.prepare(`INSERT INTO finops_euc_runtime_attempts(execution_id,org_id,customer_id,connection_id,partition,boundary_sha256,account_count,region_count,request_id,job_id,job_attempt,scheduled_window,state,generation_id,capture_id,cur2_generation_id,cur2_projection_sha256,request_body_sha256,response_body_sha256,broker_key_id,failure_code,content_sha256,completed_at,created_at) SELECT ?,c.org_id,c.customer_id,c.id,c.partition,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM aws_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active' JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status IN ('active','trial') WHERE c.id=? AND c.org_id=? AND c.customer_id=? AND c.partition=? AND c.source_kind='aws_trust_role' AND c.status='active' AND (? IS NULL OR EXISTS(SELECT 1 FROM finops_euc_snapshots s WHERE s.generation_id=? AND s.org_id=c.org_id AND s.customer_id=c.customer_id AND s.connection_id=c.id AND s.partition=c.partition AND s.source_capture_id=?)) ON CONFLICT DO NOTHING`).bind(executionId,boundarySha256,input.boundary.accountIds.length,input.boundary.regions.length,input.requestId,input.jobId,input.jobAttempt,input.scheduledWindow,input.state,input.generationId,input.captureId,input.cur2GenerationId,input.cur2ProjectionSha256,input.requestBodySha256,input.responseBodySha256,input.brokerKeyId,input.failureCode,contentSha256,input.completedAtMs,input.completedAtMs,input.boundary.scope.connectionId,input.boundary.scope.orgId,input.boundary.scope.customerId,input.boundary.partition,input.generationId,input.generationId,input.captureId).run();
    const stored=await this.getAttempt(input.boundary,input.requestId,input.jobAttempt);if(stored===null)fail("SCOPE_NOT_FOUND");if(stored.executionId!==executionId)fail("IMMUTABLE_CONFLICT");return stored;
  }
}
