/** Durable configuration, scheduling and replay state for ADD-12. */
import { getRawDb } from "./index";
import { ensureRuntimeSchema } from "./runtime-migrations";
import type { AwsConfigComplianceRepositoryScope } from "./finops-aws-config-compliance-repository.ts";
import type { AwsConfigComplianceReplayClaim, AwsConfigComplianceReplayStore,
  AwsConfigComplianceRuntimeResult } from "../lib/finops-aws-config-compliance-runtime-binding.ts";
import type { AwsConfigComplianceScope, AwsConfigActivityEvidence, AwsConfigCur2Evidence } from
  "../lib/finops-aws-config-compliance.ts";
import type { AwsConfigComplianceProviderContext } from
  "../lib/finops-aws-config-compliance-signed-broker.ts";

const IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9._:@+-]{0,255}$/u;
const CONNECTION = /^conn_[a-f0-9]{32}$/u; const ACCOUNT = /^\d{12}$/u;
const REGION = /^[a-z]{2}(?:-gov)?-[a-z]+-\d$/u; const JOB = /^job_[a-f0-9]{32}$/u;
const WINDOW = /^\d{4}-\d{2}-\d{2}T00:00:00\.000Z$/u; const SHA256 = /^[a-f0-9]{64}$/u;
const LIVE = `FROM aws_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active'
  JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status IN('active','trial')
  WHERE c.source_kind='aws_trust_role' AND c.status='active'
  AND c.permission_pack_version='standard-2026-08.18'`;
const CONFIGURED = `FROM aws_connections c JOIN organizations o ON o.id=c.org_id AND o.status='active'
  JOIN customers cu ON cu.id=c.customer_id AND cu.org_id=c.org_id AND cu.status IN('active','trial')
  JOIN finops_config_compliance_runtime_configuration r ON r.org_id=c.org_id
    AND r.customer_id=c.customer_id AND r.connection_id=c.id AND r.enabled=1
  WHERE c.source_kind='aws_trust_role' AND c.status='active'
    AND c.permission_pack_version='standard-2026-08.18'`;
interface ScopeRow { org_id:string;customer_id:string;connection_id:string;partition:"aws"|"aws-us-gov"|"aws-cn";
  account_id:string;aggregator_name:string;aggregator_arn:string;aws_organization_id:string;
  accounts_evidence_id:string;accounts_observed_at:string;active_account_ids_json:string;
  expected_regions_json:string;activity_evidence_json:string|null;cur2_evidence_json:string|null }
interface TargetRow { account_id:string;connection_id:string }
interface AttemptRow { replay_key:string;job_id:string;org_id:string;customer_id:string;connection_id:string;
  scheduled_window:string;state:"IN_PROGRESS"|"SUCCEEDED"|"FAILED";failure_code:string|null;
  result_json:string|null;result_sha256:string|null;lease_token:string;lease_expires_at:number|string;
  started_at:number|string;completed_at:number|string|null;updated_at:number|string }
export interface AwsConfigComplianceRuntimeStatus { readonly state:"unavailable"|"collecting"|"failed"|"ready";
  readonly reason:string;readonly lastAttemptAt:string|null }
export class AwsConfigComplianceRuntimeRepositoryError extends Error {
  public readonly code:"INVALID_INPUT"|"SCOPE_NOT_FOUND"|"STORED_STATE_INVALID"|"BOUND_REACHED"|"LEASE_LOST";
  public constructor(code:AwsConfigComplianceRuntimeRepositoryError["code"]){super("AWS Config compliance runtime rejected");this.name="AwsConfigComplianceRuntimeRepositoryError";this.code=code}
}
function reject(code:AwsConfigComplianceRuntimeRepositoryError["code"]):never{throw new AwsConfigComplianceRuntimeRepositoryError(code)}
function integer(value:number|string):number{const parsed=typeof value==="string"?Number(value):value;if(!Number.isSafeInteger(parsed)||parsed<0)reject("STORED_STATE_INVALID");return parsed}
function validScope(value:AwsConfigComplianceRepositoryScope):boolean{return IDENTIFIER.test(value.organizationId)&&IDENTIFIER.test(value.customerId)&&CONNECTION.test(value.connectionId)}
function parseJson(value:string):unknown{try{return JSON.parse(value)}catch{reject("STORED_STATE_INVALID")}}
function strings(value:unknown,expression:RegExp,maximum:number):readonly string[]{if(!Array.isArray(value)||value.length<1||value.length>maximum||value.some((item)=>typeof item!=="string"||!expression.test(item)))reject("STORED_STATE_INVALID");const result=value as string[];if(JSON.stringify(result)!==JSON.stringify([...new Set(result)].sort()))reject("STORED_STATE_INVALID");return result}
async function token():Promise<string>{const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(crypto.randomUUID()));return[...new Uint8Array(digest)].map((part)=>part.toString(16).padStart(2,"0")).join("")}
async function digest(value:string):Promise<string>{const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map((part)=>part.toString(16).padStart(2,"0")).join("")}
function replayScope(key:string):AwsConfigComplianceRepositoryScope&{scheduledWindow:string}{const parts=key.split(":");if(parts.length!==5||parts[0]!=="aws-config-compliance")reject("INVALID_INPUT");let values:string[];try{values=parts.slice(1).map(decodeURIComponent)}catch{reject("INVALID_INPUT")};const result={organizationId:values[0]!,customerId:values[1]!,connectionId:values[2]!,scheduledWindow:values[3]!};if(!validScope(result)||!WINDOW.test(result.scheduledWindow)||!Number.isFinite(Date.parse(result.scheduledWindow))||new Date(Date.parse(result.scheduledWindow)).toISOString()!==result.scheduledWindow)reject("INVALID_INPUT");return result}
function runtimeResult(value:unknown):value is AwsConfigComplianceRuntimeResult{if(typeof value!=="object"||value===null||Array.isArray(value))return false;const item=value as Record<string,unknown>;return typeof item.snapshotId==="string"&&/^acc_[a-f0-9]{64}$/u.test(item.snapshotId)&&typeof item.captureId==="string"&&/^config_[a-f0-9]{64}$/u.test(item.captureId)&&typeof item.state==="string"&&["CONFIGURATION_REQUIRED","PARTIAL","STALE","FAILED","EMPTY","READY"].includes(item.state)}

export class AwsConfigComplianceRuntimeRepository implements AwsConfigComplianceReplayStore {
  private readonly now:()=>number;private readonly skip:boolean;
  public constructor(private readonly database:D1Database=getRawDb(),options:{readonly now?:()=>number;readonly skipRuntimeSchema?:boolean}={}){this.now=options.now??Date.now;this.skip=options.skipRuntimeSchema??false}
  private async ready(){if(!this.skip)await ensureRuntimeSchema(this.database);return this.database}
  private clock(){const value=this.now();if(!Number.isSafeInteger(value)||value<0)reject("INVALID_INPUT");return value}
  public async listEligibleScopes(limit=10_000):Promise<readonly AwsConfigComplianceRepositoryScope[]>{if(!Number.isSafeInteger(limit)||limit<1||limit>10_000)reject("INVALID_INPUT");const rows=await(await this.ready()).prepare(`SELECT c.org_id,c.customer_id,c.id AS connection_id ${CONFIGURED} ORDER BY c.id LIMIT ?`).bind(limit+1).all<{org_id:string;customer_id:string;connection_id:string}>();if((rows.results??[]).length>limit)reject("BOUND_REACHED");return(rows.results??[]).map((row)=>({organizationId:row.org_id,customerId:row.customer_id,connectionId:row.connection_id}))}
  private async row(scope:AwsConfigComplianceRepositoryScope):Promise<ScopeRow>{if(!validScope(scope))reject("INVALID_INPUT");const row=await(await this.ready()).prepare(`SELECT c.org_id,c.customer_id,c.id AS connection_id,c.partition,c.aws_account_id AS account_id,r.aggregator_name,r.aggregator_arn,r.aws_organization_id,r.accounts_evidence_id,r.accounts_observed_at,r.active_account_ids_json,r.expected_regions_json,r.activity_evidence_json,r.cur2_evidence_json ${CONFIGURED} AND c.org_id=? AND c.customer_id=? AND c.id=? LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId).first<ScopeRow>();if(row===null)reject("SCOPE_NOT_FOUND");return row}
  public async loadScope(scope:AwsConfigComplianceRepositoryScope):Promise<AwsConfigComplianceScope>{const row=await this.row(scope);const match=/^arn:(aws|aws-us-gov|aws-cn):config:([^:]+):(\d{12}):config-aggregator\/(config-aggregator-[a-z0-9]+)$/u.exec(row.aggregator_arn);if(!match||match[1]!==row.partition||match[3]!==row.account_id||!REGION.test(match[2]!)||!/^[\w-]{1,256}$/u.test(row.aggregator_name))reject("STORED_STATE_INVALID");return Object.freeze({orgId:row.org_id,customerId:row.customer_id,connectionId:row.connection_id,partition:row.partition,aggregatorAccountId:row.account_id,aggregatorRegion:match[2]!,aggregatorName:row.aggregator_name,aggregatorArn:row.aggregator_arn})}
  public async loadProviderContext(scope:AwsConfigComplianceRepositoryScope):Promise<AwsConfigComplianceProviderContext>{const row=await this.row(scope);const trusted=await this.loadScope(scope);const accounts=strings(parseJson(row.active_account_ids_json),ACCOUNT,10_000);const regions=strings(parseJson(row.expected_regions_json),REGION,64);if(accounts.length*regions.length>100_000||!accounts.includes(trusted.aggregatorAccountId)||!/^o-[a-z0-9]{10,32}$/u.test(row.aws_organization_id)||!Number.isFinite(Date.parse(row.accounts_observed_at)))reject("STORED_STATE_INVALID");const targets=await(await this.ready()).prepare(`SELECT c.aws_account_id AS account_id,c.id AS connection_id ${LIVE} AND c.org_id=? AND c.customer_id=? AND c.partition=? ORDER BY c.aws_account_id,c.id LIMIT 10001`).bind(scope.organizationId,scope.customerId,trusted.partition).all<TargetRow>();const map=new Map<string,string>();for(const target of targets.results??[]){if(!ACCOUNT.test(target.account_id)||!CONNECTION.test(target.connection_id)||map.has(target.account_id))reject("STORED_STATE_INVALID");map.set(target.account_id,target.connection_id)}if(accounts.some((account)=>!map.has(account)))reject("SCOPE_NOT_FOUND");const optionalEvidence=<T>(raw:string|null,keys:readonly string[]):T|null=>{if(raw===null)return null;const value=parseJson(raw);if(typeof value!=="object"||value===null||Array.isArray(value)||JSON.stringify(Object.keys(value).sort())!==JSON.stringify([...keys].sort()))reject("STORED_STATE_INVALID");return value as T};const activity=optionalEvidence<AwsConfigActivityEvidence>(row.activity_evidence_json,["source","configured","exhausted","dataThroughAt","prefixEvidenceId","rows"]);const cur2=optionalEvidence<AwsConfigCur2Evidence>(row.cur2_evidence_json,["source","generationId","sourceEvidenceId","dataThroughAt","reconciliationState","predicate","rows"]);return Object.freeze({expectedCoverage:Object.freeze({awsOrganizationId:row.aws_organization_id,accountsEvidenceId:row.accounts_evidence_id,accountsObservedAt:new Date(Date.parse(row.accounts_observed_at)).toISOString(),activeAccountIds:accounts,expectedRegions:regions}),targets:Object.freeze(accounts.flatMap((accountId)=>regions.map((region)=>Object.freeze({accountId,region,connectionId:map.get(accountId)!})))),activity,cur2})}
  public async claim(input:{readonly key:string;readonly jobId:string;readonly leaseDurationMs:number}):Promise<AwsConfigComplianceReplayClaim>{const scope=replayScope(input.key);if(!JOB.test(input.jobId)||!Number.isSafeInteger(input.leaseDurationMs)||input.leaseDurationMs<60_000||input.leaseDurationMs>30*60*1_000)reject("INVALID_INPUT");await this.row(scope);const db=await this.ready();const now=this.clock();const lease=await token();await db.prepare(`INSERT INTO finops_config_compliance_runtime_attempts(replay_key,job_id,org_id,customer_id,connection_id,scheduled_window,state,failure_code,result_json,result_sha256,lease_token,lease_expires_at,started_at,completed_at,updated_at)VALUES(?,?,?,?,?,?,'IN_PROGRESS',NULL,NULL,NULL,?,?,?,NULL,?) ON CONFLICT(replay_key) DO NOTHING`).bind(input.key,input.jobId,scope.organizationId,scope.customerId,scope.connectionId,scope.scheduledWindow,lease,now+input.leaseDurationMs,now,now).run();let row=await db.prepare(`SELECT * FROM finops_config_compliance_runtime_attempts WHERE replay_key=? LIMIT 1`).bind(input.key).first<AttemptRow>();if(row===null||row.org_id!==scope.organizationId||row.customer_id!==scope.customerId||row.connection_id!==scope.connectionId||row.scheduled_window!==scope.scheduledWindow)reject("STORED_STATE_INVALID");if(row.state==="SUCCEEDED"){if(row.result_json===null||row.result_sha256===null||!SHA256.test(row.result_sha256))reject("STORED_STATE_INVALID");const result=parseJson(row.result_json);if(!runtimeResult(result)||await digest(row.result_json)!==row.result_sha256)reject("STORED_STATE_INVALID");return{state:"COMPLETED",result,resultSha256:row.result_sha256}}if(row.state==="IN_PROGRESS"&&row.lease_token!==lease&&integer(row.lease_expires_at)>now)return{state:"IN_PROGRESS"};if(row.lease_token!==lease){const updated=await db.prepare(`UPDATE finops_config_compliance_runtime_attempts SET job_id=?,state='IN_PROGRESS',failure_code=NULL,result_json=NULL,result_sha256=NULL,lease_token=?,lease_expires_at=?,started_at=?,completed_at=NULL,updated_at=? WHERE replay_key=? AND state<>'SUCCEEDED' AND(state='FAILED' OR lease_expires_at<=?)`).bind(input.jobId,lease,now+input.leaseDurationMs,now,now,input.key,now).run();if((updated.meta?.changes??0)!==1)return{state:"IN_PROGRESS"};row={...row,lease_token:lease}}return{state:"ACQUIRED",leaseToken:lease}}
  public async complete(input:{readonly key:string;readonly jobId:string;readonly leaseToken:string;readonly result:AwsConfigComplianceRuntimeResult;readonly resultSha256:string}):Promise<void>{replayScope(input.key);if(!JOB.test(input.jobId)||!SHA256.test(input.leaseToken)||!SHA256.test(input.resultSha256)||!runtimeResult(input.result))reject("INVALID_INPUT");const payload=JSON.stringify(input.result);if(await digest(payload)!==input.resultSha256)reject("INVALID_INPUT");const now=this.clock();const result=await(await this.ready()).prepare(`UPDATE finops_config_compliance_runtime_attempts SET state='SUCCEEDED',failure_code=NULL,result_json=?,result_sha256=?,completed_at=?,updated_at=? WHERE replay_key=? AND job_id=? AND state='IN_PROGRESS' AND lease_token=? AND lease_expires_at>=?`).bind(payload,input.resultSha256,now,now,input.key,input.jobId,input.leaseToken,now).run();if((result.meta?.changes??0)!==1)reject("LEASE_LOST")}
  public async fail(input:{readonly key:string;readonly jobId:string;readonly leaseToken:string;readonly failureCode:"AWS_CONFIG_COMPLIANCE_COLLECTION_FAILED"}):Promise<void>{replayScope(input.key);if(!JOB.test(input.jobId)||!SHA256.test(input.leaseToken)||input.failureCode!=="AWS_CONFIG_COMPLIANCE_COLLECTION_FAILED")reject("INVALID_INPUT");const now=this.clock();const result=await(await this.ready()).prepare(`UPDATE finops_config_compliance_runtime_attempts SET state='FAILED',failure_code=?,completed_at=?,updated_at=? WHERE replay_key=? AND job_id=? AND state='IN_PROGRESS' AND lease_token=?`).bind(input.failureCode,now,now,input.key,input.jobId,input.leaseToken).run();if((result.meta?.changes??0)!==1)reject("LEASE_LOST")}
  public async getRuntimeStatus(scope:AwsConfigComplianceRepositoryScope):Promise<AwsConfigComplianceRuntimeStatus>{if(!validScope(scope))reject("INVALID_INPUT");const row=await(await this.ready()).prepare(`SELECT * FROM finops_config_compliance_runtime_attempts WHERE org_id=? AND customer_id=? AND connection_id=? ORDER BY updated_at DESC,replay_key DESC LIMIT 1`).bind(scope.organizationId,scope.customerId,scope.connectionId).first<AttemptRow>();if(row===null)return{state:"unavailable",reason:"AWS_CONFIG_COMPLIANCE_COLLECTION_NOT_STARTED",lastAttemptAt:null};const at=new Date(integer(row.updated_at)).toISOString();if(row.state==="IN_PROGRESS")return integer(row.lease_expires_at)>this.clock()?{state:"collecting",reason:"AWS_CONFIG_COMPLIANCE_COLLECTION_IN_PROGRESS",lastAttemptAt:at}:{state:"failed",reason:"AWS_CONFIG_COMPLIANCE_COLLECTION_LEASE_EXPIRED",lastAttemptAt:at};if(row.state==="FAILED")return{state:"failed",reason:row.failure_code??"AWS_CONFIG_COMPLIANCE_COLLECTION_FAILED",lastAttemptAt:at};if(row.result_json===null||row.result_sha256===null||!SHA256.test(row.result_sha256)||await digest(row.result_json)!==row.result_sha256||!runtimeResult(parseJson(row.result_json)))reject("STORED_STATE_INVALID");return{state:"ready",reason:"AWS_CONFIG_COMPLIANCE_COLLECTION_READY",lastAttemptAt:at}}
}
