CREATE TABLE finops_amazon_connect_cost_snapshots (
 generation_id text PRIMARY KEY,org_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,customer_id text NOT NULL REFERENCES customers(id) ON DELETE CASCADE,connection_id text NOT NULL REFERENCES aws_connections(id) ON DELETE CASCADE,
 account_id text NOT NULL,partition text NOT NULL CHECK (partition IN ('aws','aws-cn','aws-us-gov')),region text NOT NULL,source_capture_id text NOT NULL,
 source_state text NOT NULL CHECK (source_state IN ('configuration_required','permission_required','failed','partial','empty','stale','current')),complete bigint NOT NULL CHECK (complete IN (0,1)),
 content_sha256 text NOT NULL,snapshot_json text NOT NULL,completed_at text NOT NULL,data_through_at text NOT NULL,billing_generation_id text NOT NULL,billing_manifest_sha256 text NOT NULL,
 instance_count bigint NOT NULL CHECK (instance_count BETWEEN 0 AND 100),phone_aggregate_count bigint NOT NULL CHECK (phone_aggregate_count BETWEEN 0 AND 10000),cost_row_count bigint NOT NULL CHECK (cost_row_count BETWEEN 0 AND 500000),created_at bigint NOT NULL CHECK (created_at BETWEEN 0 AND 9007199254740991),
 UNIQUE (org_id,customer_id,connection_id,generation_id),UNIQUE (org_id,customer_id,connection_id,source_capture_id),CHECK (generation_id~'^acig_[a-f0-9]{64}$'),CHECK (source_capture_id~'^connect_[a-f0-9]{64}$'),CHECK (content_sha256~'^[a-f0-9]{64}$'),CHECK (billing_manifest_sha256~'^[a-f0-9]{64}$'),CHECK (billing_generation_id~'^fbg_[a-f0-9]{64}$'),CHECK (account_id~'^[0-9]{12}$'),CHECK (octet_length(snapshot_json) BETWEEN 2 AND 83886080),CHECK (char_length(completed_at)=24 AND char_length(data_through_at)=24 AND data_through_at<=completed_at),CHECK (complete=0 OR source_state IN ('empty','stale','current'))
);
CREATE INDEX finops_amazon_connect_cost_history_idx ON finops_amazon_connect_cost_snapshots(org_id,customer_id,connection_id,completed_at DESC,generation_id DESC);
CREATE TABLE finops_amazon_connect_cost_heads(org_id text NOT NULL,customer_id text NOT NULL,connection_id text NOT NULL,active_generation_id text NOT NULL UNIQUE REFERENCES finops_amazon_connect_cost_snapshots(generation_id),advanced_at bigint NOT NULL CHECK (advanced_at BETWEEN 0 AND 9007199254740991),PRIMARY KEY(org_id,customer_id,connection_id));
CREATE OR REPLACE FUNCTION finops_amazon_connect_snapshot_immutable() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'FINOPS_AMAZON_CONNECT_SNAPSHOT_IMMUTABLE'; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER finops_amazon_connect_snapshot_guard BEFORE UPDATE OR DELETE ON finops_amazon_connect_cost_snapshots FOR EACH ROW EXECUTE FUNCTION finops_amazon_connect_snapshot_immutable();
CREATE OR REPLACE FUNCTION finops_amazon_connect_head_guard() RETURNS trigger AS $$ DECLARE candidate finops_amazon_connect_cost_snapshots%ROWTYPE;active finops_amazon_connect_cost_snapshots%ROWTYPE; BEGIN SELECT * INTO candidate FROM finops_amazon_connect_cost_snapshots WHERE generation_id=NEW.active_generation_id;IF candidate.generation_id IS NULL OR candidate.complete<>1 OR candidate.org_id<>NEW.org_id OR candidate.customer_id<>NEW.customer_id OR candidate.connection_id<>NEW.connection_id THEN RAISE EXCEPTION 'FINOPS_AMAZON_CONNECT_HEAD_REJECTED';END IF;IF TG_OP='UPDATE' THEN IF NEW.org_id<>OLD.org_id OR NEW.customer_id<>OLD.customer_id OR NEW.connection_id<>OLD.connection_id THEN RAISE EXCEPTION 'FINOPS_AMAZON_CONNECT_HEAD_REJECTED';END IF;SELECT * INTO active FROM finops_amazon_connect_cost_snapshots WHERE generation_id=OLD.active_generation_id;IF NOT candidate.completed_at>active.completed_at THEN RAISE EXCEPTION 'FINOPS_AMAZON_CONNECT_HEAD_REJECTED';END IF;END IF;RETURN NEW;END; $$ LANGUAGE plpgsql;
CREATE TRIGGER finops_amazon_connect_head_write_guard BEFORE INSERT OR UPDATE ON finops_amazon_connect_cost_heads FOR EACH ROW EXECUTE FUNCTION finops_amazon_connect_head_guard();
CREATE TRIGGER finops_amazon_connect_head_delete_guard BEFORE DELETE ON finops_amazon_connect_cost_heads FOR EACH ROW EXECUTE FUNCTION finops_amazon_connect_snapshot_immutable();
--> statement-breakpoint
REVOKE ALL ON finops_amazon_connect_cost_snapshots FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON finops_amazon_connect_cost_heads FROM PUBLIC;
