CREATE TABLE finops_azure_cid_sources(source_id text PRIMARY KEY,org_id text NOT NULL REFERENCES organizations(id)ON DELETE CASCADE,customer_id text NOT NULL REFERENCES customers(id)ON DELETE CASCADE,azure_tenant_id text NOT NULL,billing_scope_kind text NOT NULL CHECK(billing_scope_kind IN('BILLING_ACCOUNT','BILLING_PROFILE','MANAGEMENT_GROUP','SUBSCRIPTION')),billing_scope_hash text NOT NULL,status text NOT NULL CHECK(status IN('active','configuration_required')),activation_reason text NOT NULL CHECK(activation_reason IN('READY','AZURE_CREDENTIAL_NOT_CONFIGURED','AZURE_EXPORT_NOT_CONFIGURED','AZURE_STORAGE_ACCESS_NOT_CONFIGURED','AZURE_EXPORT_DELIVERY_NOT_OBSERVED','AZURE_DATASET_SCHEMA_UNSUPPORTED')),created_at bigint NOT NULL CHECK(created_at BETWEEN 0 AND 9007199254740991),UNIQUE(org_id,customer_id,source_id),CHECK(source_id~'^azsrc_[a-f0-9]{32}$'),CHECK(azure_tenant_id~'^[a-f0-9-]{36}$'),CHECK(billing_scope_hash~'^[a-f0-9]{64}$'),CHECK((status='active')=(activation_reason='READY')));
CREATE TABLE finops_azure_cid_snapshots(generation_id text PRIMARY KEY,source_generation_id text NOT NULL,source_id text NOT NULL REFERENCES finops_azure_cid_sources(source_id)ON DELETE CASCADE,org_id text NOT NULL REFERENCES organizations(id)ON DELETE CASCADE,customer_id text NOT NULL REFERENCES customers(id)ON DELETE CASCADE,source_state text NOT NULL CHECK(source_state IN('READY','EMPTY','PARTIAL','STALE')),dataset_kind text NOT NULL CHECK(dataset_kind IN('AZURE_STANDARD_ACTUAL_COST','FOCUS_1_0')),content_sha256 text NOT NULL,snapshot_json text NOT NULL,completed_at text NOT NULL,data_through_at text NOT NULL,row_count bigint NOT NULL CHECK(row_count BETWEEN 0 AND 500000),currency_count bigint NOT NULL CHECK(currency_count BETWEEN 0 AND 128),created_at bigint NOT NULL CHECK(created_at BETWEEN 0 AND 9007199254740991),UNIQUE(org_id,customer_id,source_id,generation_id),UNIQUE(org_id,customer_id,source_id,source_generation_id),CHECK(generation_id~'^azcg_[a-f0-9]{64}$'),CHECK(source_generation_id~'^azcid_[a-f0-9]{64}$'),CHECK(content_sha256~'^[a-f0-9]{64}$'),CHECK(octet_length(snapshot_json)BETWEEN 2 AND 83886080),CHECK(char_length(completed_at)=24 AND char_length(data_through_at)=24 AND data_through_at<=completed_at));CREATE INDEX finops_azure_cid_history_idx ON finops_azure_cid_snapshots(org_id,customer_id,source_id,completed_at DESC,generation_id DESC);CREATE TABLE finops_azure_cid_heads(org_id text NOT NULL,customer_id text NOT NULL,source_id text NOT NULL,active_generation_id text NOT NULL UNIQUE REFERENCES finops_azure_cid_snapshots(generation_id),advanced_at bigint NOT NULL CHECK(advanced_at BETWEEN 0 AND 9007199254740991),PRIMARY KEY(org_id,customer_id,source_id));
CREATE OR REPLACE FUNCTION finops_azure_cid_snapshot_immutable()RETURNS trigger AS $$BEGIN RAISE EXCEPTION 'FINOPS_AZURE_CID_SNAPSHOT_IMMUTABLE';END;$$LANGUAGE plpgsql;CREATE TRIGGER finops_azure_cid_snapshot_guard BEFORE UPDATE OR DELETE ON finops_azure_cid_snapshots FOR EACH ROW EXECUTE FUNCTION finops_azure_cid_snapshot_immutable();CREATE OR REPLACE FUNCTION finops_azure_cid_head_guard()RETURNS trigger AS $$DECLARE candidate finops_azure_cid_snapshots%ROWTYPE;active finops_azure_cid_snapshots%ROWTYPE;BEGIN SELECT * INTO candidate FROM finops_azure_cid_snapshots WHERE generation_id=NEW.active_generation_id;IF candidate.generation_id IS NULL OR candidate.source_state NOT IN('READY','EMPTY') OR candidate.org_id<>NEW.org_id OR candidate.customer_id<>NEW.customer_id OR candidate.source_id<>NEW.source_id THEN RAISE EXCEPTION 'FINOPS_AZURE_CID_HEAD_REJECTED';END IF;IF TG_OP='UPDATE'THEN IF NEW.org_id<>OLD.org_id OR NEW.customer_id<>OLD.customer_id OR NEW.source_id<>OLD.source_id THEN RAISE EXCEPTION 'FINOPS_AZURE_CID_HEAD_REJECTED';END IF;SELECT * INTO active FROM finops_azure_cid_snapshots WHERE generation_id=OLD.active_generation_id;IF NOT candidate.completed_at>active.completed_at THEN RAISE EXCEPTION 'FINOPS_AZURE_CID_HEAD_REJECTED';END IF;END IF;RETURN NEW;END;$$LANGUAGE plpgsql;CREATE TRIGGER finops_azure_cid_head_write_guard BEFORE INSERT OR UPDATE ON finops_azure_cid_heads FOR EACH ROW EXECUTE FUNCTION finops_azure_cid_head_guard();CREATE TRIGGER finops_azure_cid_head_delete_guard BEFORE DELETE ON finops_azure_cid_heads FOR EACH ROW EXECUTE FUNCTION finops_azure_cid_snapshot_immutable();
--> statement-breakpoint
REVOKE ALL ON finops_azure_cid_sources FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON finops_azure_cid_snapshots FROM PUBLIC;
--> statement-breakpoint
REVOKE ALL ON finops_azure_cid_heads FROM PUBLIC;
