CREATE TABLE finops_cora_export_object_generations(generation_id text PRIMARY KEY CHECK(generation_id~'^core_[a-f0-9]{64}$'),org_id text NOT NULL REFERENCES organizations(id)ON DELETE CASCADE,customer_id text NOT NULL REFERENCES customers(id)ON DELETE CASCADE,connection_id text NOT NULL REFERENCES aws_connections(id)ON DELETE CASCADE,management_account_id text NOT NULL CHECK(management_account_id~'^[0-9]{12}$'),request_key text NOT NULL CHECK(request_key~'^corarq_[a-f0-9]{64}$'),materialization_id text NOT NULL CHECK(materialization_id~'^coram_[a-f0-9]{64}$'),capture_id text NOT NULL CHECK(capture_id~'^cora_[a-f0-9]{64}$'),export_arn text NOT NULL,execution_id text NOT NULL,source_state text NOT NULL CHECK(source_state IN('WAITING_DELIVERY','FAILED','PARTIAL','EMPTY','COMPLETE')),complete boolean NOT NULL,content_sha256 text NOT NULL CHECK(content_sha256~'^[a-f0-9]{64}$'),materialization_json text NOT NULL CHECK(octet_length(materialization_json)BETWEEN 2 AND 201326592),scheduled_window text NOT NULL CHECK(char_length(scheduled_window)=24),generated_at text CHECK(generated_at IS NULL OR char_length(generated_at)=24),data_through_at text CHECK(data_through_at IS NULL OR char_length(data_through_at)=24),manifest_sha256 text CHECK(manifest_sha256 IS NULL OR manifest_sha256~'^[a-f0-9]{64}$'),object_count bigint NOT NULL CHECK(object_count BETWEEN 0 AND 100000),row_count bigint NOT NULL CHECK(row_count BETWEEN 0 AND 500000),accepted_row_count bigint NOT NULL CHECK(accepted_row_count BETWEEN 0 AND row_count),rejected_row_count bigint NOT NULL CHECK(rejected_row_count BETWEEN 0 AND row_count),created_at bigint NOT NULL CHECK(created_at BETWEEN 0 AND 9007199254740991),UNIQUE(org_id,customer_id,connection_id,request_key),UNIQUE(org_id,customer_id,connection_id,materialization_id),UNIQUE(org_id,customer_id,connection_id,execution_id),CHECK(NOT complete OR(source_state IN('COMPLETE','EMPTY')AND generated_at IS NOT NULL AND data_through_at IS NOT NULL AND manifest_sha256 IS NOT NULL AND accepted_row_count=row_count AND rejected_row_count=0)));
CREATE INDEX finops_cora_export_object_history_idx ON finops_cora_export_object_generations(org_id,customer_id,connection_id,scheduled_window DESC,generation_id DESC);
CREATE TABLE finops_cora_export_object_heads(org_id text NOT NULL,customer_id text NOT NULL,connection_id text NOT NULL,active_generation_id text NOT NULL UNIQUE REFERENCES finops_cora_export_object_generations(generation_id),advanced_at bigint NOT NULL CHECK(advanced_at BETWEEN 0 AND 9007199254740991),PRIMARY KEY(org_id,customer_id,connection_id));
CREATE OR REPLACE FUNCTION finops_cora_export_object_immutable()RETURNS trigger AS $$BEGIN RAISE EXCEPTION 'FINOPS_CORA_EXPORT_OBJECT_IMMUTABLE';END;$$LANGUAGE plpgsql;
CREATE TRIGGER finops_cora_export_objects_immutable_guard BEFORE UPDATE OR DELETE ON finops_cora_export_object_generations FOR EACH ROW EXECUTE FUNCTION finops_cora_export_object_immutable();
CREATE OR REPLACE FUNCTION finops_cora_export_head_guard()RETURNS trigger AS $$DECLARE candidate finops_cora_export_object_generations%ROWTYPE;active finops_cora_export_object_generations%ROWTYPE;BEGIN SELECT * INTO candidate FROM finops_cora_export_object_generations WHERE generation_id=NEW.active_generation_id;IF candidate.generation_id IS NULL OR NOT candidate.complete OR candidate.source_state NOT IN('COMPLETE','EMPTY')OR candidate.org_id<>NEW.org_id OR candidate.customer_id<>NEW.customer_id OR candidate.connection_id<>NEW.connection_id THEN RAISE EXCEPTION 'FINOPS_CORA_EXPORT_HEAD_REJECTED';END IF;IF TG_OP='UPDATE'THEN IF NEW.org_id<>OLD.org_id OR NEW.customer_id<>OLD.customer_id OR NEW.connection_id<>OLD.connection_id THEN RAISE EXCEPTION 'FINOPS_CORA_EXPORT_HEAD_REJECTED';END IF;SELECT * INTO active FROM finops_cora_export_object_generations WHERE generation_id=OLD.active_generation_id;IF NOT(candidate.data_through_at>active.data_through_at OR(candidate.data_through_at=active.data_through_at AND(candidate.generated_at>active.generated_at OR(candidate.generated_at=active.generated_at AND candidate.generation_id>active.generation_id))))THEN RAISE EXCEPTION 'FINOPS_CORA_EXPORT_HEAD_REJECTED';END IF;END IF;RETURN NEW;END;$$LANGUAGE plpgsql;
CREATE TRIGGER finops_cora_export_heads_write_guard BEFORE INSERT OR UPDATE ON finops_cora_export_object_heads FOR EACH ROW EXECUTE FUNCTION finops_cora_export_head_guard();
CREATE TRIGGER finops_cora_export_heads_delete_guard BEFORE DELETE ON finops_cora_export_object_heads FOR EACH ROW EXECUTE FUNCTION finops_cora_export_object_immutable();
REVOKE ALL ON finops_cora_export_object_generations FROM PUBLIC;REVOKE ALL ON finops_cora_export_object_heads FROM PUBLIC;
