/** Sanitizing AWS SDK response projector for ADD-12. Raw provider messages never cross this boundary. */
import { createHash } from "node:crypto";
import type { AwsConfigComplianceProjectionBuilder, AwsConfigComplianceCentralRawEvidence,
  AwsConfigComplianceFanoutRawEvidence } from "./aws-config-compliance-provider-client.js";

type RecordValue=Readonly<Record<string,unknown>>;
function fail():never{throw new Error("AWS_CONFIG_PROVIDER_RESPONSE_INVALID")}
function record(value:unknown):RecordValue{if(typeof value!=="object"||value===null||Array.isArray(value))fail();return value as RecordValue}
function array(value:unknown):readonly unknown[]{if(!Array.isArray(value))fail();return value}
function text(value:unknown):string{if(typeof value!=="string"||value.length<1||value.length>1_024||value.includes("\0"))fail();return value}
function optionalText(value:unknown):string|null{return value===undefined||value===null||value===""?null:text(value)}
function iso(value:unknown):string{const ms=value instanceof Date?value.getTime():typeof value==="number"?value:typeof value==="string"?Date.parse(value):Number.NaN;if(!Number.isFinite(ms))fail();return new Date(ms).toISOString()}
function optionalIso(value:unknown):string|null{return value===undefined||value===null?null:iso(value)}
function integer(value:unknown):number{if(!Number.isSafeInteger(value)||Number(value)<0)fail();return Number(value)}
function digest(value:unknown):string{return createHash("sha256").update(JSON.stringify(value)).digest("hex")}
function rows(evidence:readonly {readonly response:unknown}[],key:string):readonly unknown[]{return evidence.flatMap((page)=>array(record(page.response)[key]))}
function coverage(operation:string,pages:readonly {readonly response:unknown}[],key:string,scope:{accountId:string|null;region:string|null}){return{operation,...scope,state:"SUCCEEDED",pageCount:pages.length,recordCount:rows(pages,key).length,exhausted:true,failureCode:null}}
function compliance(value:unknown):"COMPLIANT"|"NON_COMPLIANT"{const result=text(value);if(result!=="COMPLIANT"&&result!=="NON_COMPLIANT")fail();return result}
function failureCode(value:unknown):"ACCESS_DENIED"|"EXPIRED_TOKEN"|"THROTTLED"|"TIMEOUT"|"BOUND_REACHED"|"AGGREGATOR_NOT_FOUND"|"PROVIDER_UNAVAILABLE"|"UNKNOWN"{const raw=String(value??"");if(/access|authoriz/iu.test(raw))return"ACCESS_DENIED";if(/expired/iu.test(raw))return"EXPIRED_TOKEN";if(/throttl|limit/iu.test(raw))return"THROTTLED";if(/timeout/iu.test(raw))return"TIMEOUT";if(/aggregator.*not.*found/iu.test(raw))return"AGGREGATOR_NOT_FOUND";if(/unavailable|internal/iu.test(raw))return"PROVIDER_UNAVAILABLE";return"UNKNOWN"}
function centralProjection(request:Parameters<AwsConfigComplianceProjectionBuilder["central"]>[0]["request"],evidence:AwsConfigComplianceCentralRawEvidence){
  const organization=record(record(evidence.organization).Organization);const organizationId=text(organization.Id);const allFeatures=organization.FeatureSet==="ALL";
  if(organizationId!==request.expectedCoverage.awsOrganizationId)fail();
  const activeAccounts=rows(evidence.accounts,"Accounts").map(record).filter((item)=>item.Status==="ACTIVE").map((item)=>text(item.Id)).sort();
  if(JSON.stringify(activeAccounts)!==JSON.stringify(request.expectedCoverage.activeAccountIds))fail();
  const definitions=rows(evidence.aggregators,"ConfigurationAggregators");if(definitions.length>1)fail();
  const aggregator=definitions.length===0?null:(()=>{const item=record(definitions[0]);const arn=text(item.ConfigurationAggregatorArn);const source=item.OrganizationAggregationSource===undefined?null:record(item.OrganizationAggregationSource);const accountSources=item.AccountAggregationSources===undefined?[]:array(item.AccountAggregationSources);if((source===null)===(accountSources.length===0))fail();return{name:text(item.ConfigurationAggregatorName),arn,id:text(arn.split("/").at(-1)),sourceType:source===null?"ACCOUNT_SET":"ORGANIZATION",awsOrganizationId:source===null?null:organizationId,allAwsRegions:source?.AllAwsRegions===true,configuredRegions:[...(source===null?accountSources.flatMap((entry)=>array(record(entry).AwsRegions??[])):array(source.AwsRegions??[]))].map(text).sort(),createdAt:iso(item.CreationTime),lastUpdatedAt:iso(item.LastUpdatedTime)}})();
  const sourceStatuses=rows(evidence.sourceStatuses,"AggregatedSourceStatusList").map((raw)=>{const item=record(raw);const status=text(item.LastUpdateStatus);if(!["SUCCEEDED","FAILED","OUTDATED"].includes(status))fail();const sourceType=text(item.SourceType);if(sourceType!=="ACCOUNT"&&sourceType!=="ORGANIZATION")fail();const sourceId=text(item.SourceId);return{sourceType,sourceId,accountId:sourceType==="ACCOUNT"?sourceId:null,region:text(item.AwsRegion),status,lastUpdatedAt:iso(item.LastUpdateTime),failureCode:status==="FAILED"?failureCode(item.LastErrorCode):null}});
  const ruleCompliance=rows(evidence.ruleCompliance,"AggregateComplianceByConfigRules").map((raw)=>{const item=record(raw);const summary=record(item.Compliance);return{accountId:text(item.AccountId),region:text(item.AwsRegion),ruleName:text(item.ConfigRuleName),complianceType:compliance(summary.ComplianceType),contributorCount:integer(summary.ContributorCount??0),contributorCountCapped:summary.CapExceeded===true}});
  const evaluations=rows(evidence.complianceDetails,"AggregateEvaluationResults").map((raw)=>{const item=record(raw);const identifier=record(item.EvaluationResultIdentifier);const qualifier=record(identifier.EvaluationResultQualifier);const mode=qualifier.EvaluationMode??"DETECTIVE";if(mode!=="DETECTIVE"&&mode!=="PROACTIVE")fail();return{accountId:text(item.AccountId),region:text(item.AwsRegion),ruleName:text(qualifier.ConfigRuleName),resourceType:text(qualifier.ResourceType),resourceId:text(qualifier.ResourceId),complianceType:compliance(item.ComplianceType),evaluationMode:mode,invokedAt:iso(item.ConfigRuleInvokedTime),recordedAt:iso(item.ResultRecordedTime),orderingAt:iso(item.OrderingTimestamp),resourceEvaluationId:optionalText(qualifier.ResourceEvaluationId),annotationPresent:typeof item.Annotation==="string"&&item.Annotation.length>0}});
  const conformancePacks=rows(evidence.conformancePacks,"AggregateComplianceByConformancePacks").map((raw)=>{const item=record(raw);const type=text(item.ComplianceType);if(!["COMPLIANT","NON_COMPLIANT","INSUFFICIENT_DATA","NOT_APPLICABLE"].includes(type))fail();return{accountId:text(item.AccountId),region:text(item.AwsRegion),packName:text(item.CompliancePackName??item.ConformancePackName),complianceType:type,compliantRuleCount:integer(item.CompliantRuleCount??0),nonCompliantRuleCount:integer(item.NonCompliantRuleCount??0),totalRuleCount:integer(item.TotalRuleCount??0)}});
  const resourceCounts=rows(evidence.resourceCounts,"ResourceCounts").map((raw)=>{const item=record(raw);const page=evidence.resourceCounts.find((candidate)=>array(record(candidate.response).ResourceCounts).includes(raw));if(page===undefined)fail();const filters=record(page.request.Filters);return{accountId:text(filters.AccountId),region:text(filters.Region),resourceType:text(item.ResourceType),resourceCount:integer(item.Count)}});
  const resourceInventory=rows(evidence.inventory,"Results").map((raw)=>{if(typeof raw!=="string"||raw.length>64*1_024)fail();let item:RecordValue;try{item=record(JSON.parse(raw))}catch{fail()}return{accountId:text(item.accountId),region:text(item.awsRegion),resourceType:text(item.resourceType),resourceId:text(item.resourceId),captureTime:iso(item.configurationItemCaptureTime),creationTime:optionalIso(item.resourceCreationTime),itemStatus:text(item.configurationItemStatus)}});
  const operationCoverage=[coverage("config:DescribeConfigurationAggregators",evidence.aggregators,"ConfigurationAggregators",{accountId:null,region:null}),coverage("config:DescribeConfigurationAggregatorSourcesStatus",evidence.sourceStatuses,"AggregatedSourceStatusList",{accountId:null,region:null}),coverage("config:DescribeAggregateComplianceByConfigRules",evidence.ruleCompliance,"AggregateComplianceByConfigRules",{accountId:null,region:null}),coverage("config:GetAggregateComplianceDetailsByConfigRule",evidence.complianceDetails,"AggregateEvaluationResults",{accountId:null,region:null}),coverage("config:DescribeAggregateComplianceByConformancePacks",evidence.conformancePacks,"AggregateComplianceByConformancePacks",{accountId:null,region:null}),coverage("config:GetAggregateDiscoveredResourceCounts",evidence.resourceCounts,"ResourceCounts",{accountId:null,region:null}),coverage("config:SelectAggregateResourceConfig",evidence.inventory,"Results",{accountId:null,region:null}),{operation:"organizations:DescribeOrganization",accountId:null,region:null,state:"SUCCEEDED",pageCount:1,recordCount:1,exhausted:true,failureCode:null},coverage("organizations:ListAccounts",evidence.accounts,"Accounts",{accountId:null,region:null})];
  return{prerequisites:{serviceConfigured:aggregator!==null,aggregatorValidated:aggregator!==null,readPermissionsValidated:true,organizationsAllFeaturesEnabled:allFeatures},aggregator,operationCoverage,sourceStatuses,ruleCompliance,evaluations,conformancePacks,resourceCounts,resourceInventory};
}
function fanoutProjection(request:Parameters<AwsConfigComplianceProjectionBuilder["fanout"]>[0]["request"],target:Parameters<AwsConfigComplianceProjectionBuilder["fanout"]>[0]["target"],evidence:AwsConfigComplianceFanoutRawEvidence){
  const statuses=new Map(rows(evidence.evaluationStatuses,"ConfigRulesEvaluationStatus").map((raw)=>{const item=record(raw);return[text(item.ConfigRuleName),item]as const}));
  const rules=rows(evidence.rules,"ConfigRules").map((raw)=>{const item=record(raw),source=record(item.Source),scope=record(item.Scope??{}),status=statuses.get(text(item.ConfigRuleName));const owner=text(source.Owner);if(!["AWS","CUSTOM_LAMBDA","CUSTOM_POLICY"].includes(owner))fail();const modes=array(item.EvaluationModes??[{Mode:"DETECTIVE"}]).map((mode)=>text(record(mode).Mode)).sort();const details=array(source.SourceDetails??[]);const triggerTypes=[...new Set(details.map((rawDetail)=>text(record(rawDetail).MessageType)).map((message)=>message==="ScheduledNotification"?"SCHEDULED":message==="ConfigurationSnapshotDeliveryCompleted"?"SNAPSHOT_DELIVERY":"CONFIGURATION_CHANGE"))].sort();return{accountId:target.accountId,region:target.region,ruleName:text(item.ConfigRuleName),ruleId:text(item.ConfigRuleId),ruleArn:text(item.ConfigRuleArn),state:text(item.ConfigRuleState),owner,sourceIdentifierSha256:digest(source.SourceIdentifier),createdBy:optionalText(item.CreatedBy),evaluationModes:modes,triggerTypes,maximumExecutionFrequency:optionalText(item.MaximumExecutionFrequency??details.map((detail)=>record(detail).MaximumExecutionFrequency).find(Boolean)),resourceTypes:array(scope.ComplianceResourceTypes??[]).map(text).sort(),scopeFingerprintSha256:digest(scope),firstActivatedAt:optionalIso(status?.FirstActivatedTime),lastSuccessfulEvaluationAt:optionalIso(status?.LastSuccessfulEvaluationTime),lastFailedEvaluationAt:optionalIso(status?.LastFailedEvaluationTime),lastErrorCode:optionalText(status?.LastErrorCode)}});
  const statusRows=array(record(evidence.recorderStatuses).ConfigurationRecordersStatus);const recorderStatus=new Map(statusRows.map((raw)=>{const item=record(raw);return[text(item.name??item.Name),item]as const}));
  const recorders=array(record(evidence.recorders).ConfigurationRecorders).map((raw)=>{const item=record(raw),group=record(item.recordingGroup??item.RecordingGroup??{}),status=recorderStatus.get(text(item.name??item.Name));const servicePrincipal=optionalText(item.servicePrincipal??item.ServicePrincipal);const lastStatus=status===undefined?null:optionalText(status.lastStatus??status.LastStatus);if(lastStatus!==null&&!["SUCCESS","FAILURE","PENDING"].includes(lastStatus))fail();return{accountId:target.accountId,region:target.region,recorderName:text(item.name??item.Name),recorderType:servicePrincipal===null?"CUSTOMER_MANAGED":"SERVICE_LINKED",servicePrincipalSha256:servicePrincipal===null?null:digest(servicePrincipal),recording:status?.recording===true||status?.Recording===true,lastStatus,lastStatusAt:optionalIso(status?.lastStatusChangeTime??status?.LastStatusChangeTime),recordAllSupported:group.allSupported===true||group.AllSupported===true,includeGlobalResourceTypes:group.includeGlobalResourceTypes===true||group.IncludeGlobalResourceTypes===true,resourceTypes:array(group.resourceTypes??group.ResourceTypes??[]).map(text).sort()}});
  const scope={accountId:target.accountId,region:target.region};return{operationCoverage:[coverage("config:DescribeConfigRules",evidence.rules,"ConfigRules",scope),coverage("config:DescribeConfigRuleEvaluationStatus",evidence.evaluationStatuses,"ConfigRulesEvaluationStatus",scope),{operation:"config:DescribeConfigurationRecorders",...scope,state:"SUCCEEDED",pageCount:1,recordCount:recorders.length,exhausted:true,failureCode:null},{operation:"config:DescribeConfigurationRecorderStatus",...scope,state:"SUCCEEDED",pageCount:1,recordCount:statusRows.length,exhausted:true,failureCode:null}],recorders,rules};
}
const central:AwsConfigComplianceProjectionBuilder["central"]=({request,evidence})=>centralProjection(request,evidence);
const fanout:AwsConfigComplianceProjectionBuilder["fanout"]=({request,target,evidence})=>fanoutProjection(request,target,evidence);
export const AWS_CONFIG_COMPLIANCE_PROJECTION_BUILDER:AwsConfigComplianceProjectionBuilder=Object.freeze({central,fanout});
