import { createCipheriv, createDecipheriv, randomBytes, timingSafeEqual } from "node:crypto";

import type { AwsStaticCredentialMaterial } from "./types.js";

/**
 * KMS envelope encryption for customer-supplied AWS access keys held by the
 * hosted broker.
 *
 * The local collector keeps key material in an encrypted registry file sealed
 * with a single process-held key. That contract does not transfer to the hosted
 * broker, where the same material would sit in shared PostgreSQL under one
 * application key: anyone who could read the database and that key could read
 * every tenant's credentials, and the key never changes.
 *
 * Here each connection gets its own AES-256 data key, generated by KMS and
 * never stored in plaintext. PostgreSQL holds only the KMS-wrapped copy, so a
 * database compromise alone yields nothing without a live `kms:Decrypt` call
 * that CloudTrail records.
 *
 * The tenant and connection are bound at BOTH layers, which is the property
 * that makes a stolen row useless elsewhere:
 *
 *  - as the KMS encryption context, so KMS itself refuses to unwrap a data key
 *    presented under a different tenant or connection, and
 *  - as the AES-GCM additional authenticated data, so a swapped ciphertext
 *    fails authentication even if the unwrap were somehow permitted.
 *
 * Neither layer alone is sufficient: the encryption context protects the key,
 * the AAD protects the payload.
 */

/** Bytes in an AES-256 key. */
const DATA_KEY_BYTES = 32;
/** GCM standard nonce length; 12 bytes is the only size GCM defines natively. */
const IV_BYTES = 12;
/** The only key spec this contract issues. */
const KEY_SPEC = "AES_256";
/** Envelope schema version. Bump only for a reviewed format change. */
const ENVELOPE_VERSION = 1;

const KMS_KEY_ARN = /^arn:aws:kms:[a-z0-9-]{1,32}:[0-9]{12}:key\/[a-f0-9-]{36}$/u;
const BASE64URL = /^[A-Za-z0-9_-]+$/u;

export class CredentialEnvelopeError extends Error {
  public constructor(message: string) {
    // Messages never carry key material, plaintext, or the wrapped key: this
    // error reaches logs.
    super(message);
    this.name = "CredentialEnvelopeError";
  }
}

export interface CredentialEnvelopeScope {
  readonly tenantId: string;
  readonly connectionId: string;
}

export interface SealedCredentialEnvelope {
  readonly version: number;
  /** The CMK that wrapped `wrappedDataKey`, recorded for rotation and audit. */
  readonly keyArn: string;
  readonly wrappedDataKey: string;
  readonly iv: string;
  readonly tag: string;
  readonly ciphertext: string;
}

/**
 * The subset of the KMS client this module uses.
 *
 * Declared structurally so tests can drive the contract without an AWS client,
 * and so the collector's lazy SDK import stays at the call site.
 */
export interface CredentialKmsClient {
  generateDataKey(input: {
    readonly KeyId: string;
    readonly KeySpec: string;
    readonly EncryptionContext: Readonly<Record<string, string>>;
  }): Promise<{
    readonly Plaintext?: Uint8Array;
    readonly CiphertextBlob?: Uint8Array;
    readonly KeyId?: string;
  }>;
  decrypt(input: {
    readonly CiphertextBlob: Uint8Array;
    readonly EncryptionContext: Readonly<Record<string, string>>;
    readonly KeyId: string;
  }): Promise<{ readonly Plaintext?: Uint8Array; readonly KeyId?: string }>;
}

function assertScope(scope: CredentialEnvelopeScope): void {
  if (
    typeof scope.tenantId !== "string" || scope.tenantId.length === 0
    || typeof scope.connectionId !== "string" || scope.connectionId.length === 0
    // A NUL would let two different scopes render to the same AAD byte string.
    || scope.tenantId.includes("\0") || scope.connectionId.includes("\0")
  ) {
    throw new CredentialEnvelopeError("A credential envelope needs an exact tenant and connection");
  }
}

/**
 * The KMS encryption context. KMS stores it with the wrapped key and requires
 * an exact match on decrypt, so this is what stops a data key wrapped for one
 * connection being unwrapped for another.
 */
function encryptionContext(scope: CredentialEnvelopeScope): Record<string, string> {
  return {
    "sutra:tenant-id": scope.tenantId,
    "sutra:connection-id": scope.connectionId,
    "sutra:purpose": "hosted-static-credentials-v1",
  };
}

/** AES-GCM additional authenticated data, binding the payload to the same scope. */
function additionalData(scope: CredentialEnvelopeScope): Buffer {
  return Buffer.from(`${scope.tenantId}\0${scope.connectionId}`, "utf8");
}

/**
 * Overwrite a plaintext data key in place.
 *
 * Node gives no guarantee the buffer was never copied by the allocator or the
 * SDK, so this narrows the window rather than closing it. It is still worth
 * doing: it stops the key lingering in a long-lived buffer for the life of the
 * process.
 */
function zeroize(key: Buffer): void {
  key.fill(0);
}

export function isSealedCredentialEnvelope(
  value: unknown,
): value is SealedCredentialEnvelope {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const candidate = value as Record<string, unknown>;
  return candidate.version === ENVELOPE_VERSION
    && typeof candidate.keyArn === "string" && KMS_KEY_ARN.test(candidate.keyArn)
    && typeof candidate.wrappedDataKey === "string" && BASE64URL.test(candidate.wrappedDataKey)
    && typeof candidate.iv === "string" && BASE64URL.test(candidate.iv)
    && typeof candidate.tag === "string" && BASE64URL.test(candidate.tag)
    && typeof candidate.ciphertext === "string" && BASE64URL.test(candidate.ciphertext);
}

/**
 * Seal customer credentials under a fresh per-connection data key.
 *
 * The plaintext data key exists only inside this call and is zeroized before
 * returning, on the success and the failure path alike.
 */
export async function sealStaticCredentials(
  kms: CredentialKmsClient,
  keyArn: string,
  scope: CredentialEnvelopeScope,
  material: AwsStaticCredentialMaterial,
): Promise<SealedCredentialEnvelope> {
  assertScope(scope);
  if (!KMS_KEY_ARN.test(keyArn)) {
    throw new CredentialEnvelopeError("The hosted credential CMK must be an exact KMS key ARN");
  }

  // Normalized for the same reason as the unwrap: a raw SDK error must not
  // escape this module.
  let generated: {
    readonly Plaintext?: Uint8Array;
    readonly CiphertextBlob?: Uint8Array;
    readonly KeyId?: string;
  };
  try {
    generated = await kms.generateDataKey({
      KeyId: keyArn,
      KeySpec: KEY_SPEC,
      EncryptionContext: encryptionContext(scope),
    });
  } catch {
    throw new CredentialEnvelopeError("KMS did not issue a credential data key");
  }
  if (
    generated.Plaintext === undefined || generated.CiphertextBlob === undefined
    || generated.Plaintext.byteLength !== DATA_KEY_BYTES
  ) {
    throw new CredentialEnvelopeError("KMS did not return a usable AES-256 data key");
  }

  const dataKey = Buffer.from(generated.Plaintext);
  try {
    const iv = randomBytes(IV_BYTES);
    const cipher = createCipheriv("aes-256-gcm", dataKey, iv);
    cipher.setAAD(additionalData(scope));
    // Only the three credential fields are sealed. Nothing else about the
    // connection belongs inside the credential envelope.
    const cleartext = JSON.stringify({
      accessKeyId: material.accessKeyId,
      secretAccessKey: material.secretAccessKey,
      ...(material.sessionToken === undefined ? {} : { sessionToken: material.sessionToken }),
    });
    const ciphertext = Buffer.concat([cipher.update(cleartext, "utf8"), cipher.final()]);
    return {
      version: ENVELOPE_VERSION,
      keyArn,
      wrappedDataKey: Buffer.from(generated.CiphertextBlob).toString("base64url"),
      iv: iv.toString("base64url"),
      tag: cipher.getAuthTag().toString("base64url"),
      ciphertext: ciphertext.toString("base64url"),
    };
  } finally {
    zeroize(dataKey);
  }
}

/**
 * Unwrap and decrypt a sealed envelope.
 *
 * Fails closed on every mismatch: a wrong scope, a swapped ciphertext, a CMK
 * that does not match the one recorded at seal time, or a tampered tag.
 */
export async function openStaticCredentials(
  kms: CredentialKmsClient,
  scope: CredentialEnvelopeScope,
  envelope: SealedCredentialEnvelope,
): Promise<AwsStaticCredentialMaterial> {
  assertScope(scope);
  if (!isSealedCredentialEnvelope(envelope)) {
    throw new CredentialEnvelopeError("The stored credential envelope is not a valid v1 envelope");
  }

  // KMS refuses the unwrap when the encryption context or the named CMK does
  // not match what sealed the key. That refusal is the tenant boundary, so it
  // is normalized here: callers must not have to distinguish an SDK error from
  // a scope violation, and a raw KMS or crypto error must not reach a log with
  // whatever detail it carries.
  let decrypted: { readonly Plaintext?: Uint8Array; readonly KeyId?: string };
  try {
    decrypted = await kms.decrypt({
      CiphertextBlob: Buffer.from(envelope.wrappedDataKey, "base64url"),
      EncryptionContext: encryptionContext(scope),
      // Naming the key makes KMS reject a blob wrapped under a different CMK
      // rather than silently succeeding because the caller can use both.
      KeyId: envelope.keyArn,
    });
  } catch {
    throw new CredentialEnvelopeError(
      "KMS refused to unwrap the credential data key for this tenant and connection",
    );
  }
  if (decrypted.Plaintext === undefined || decrypted.Plaintext.byteLength !== DATA_KEY_BYTES) {
    throw new CredentialEnvelopeError("KMS did not return a usable AES-256 data key");
  }
  if (typeof decrypted.KeyId === "string") {
    const returned = Buffer.from(decrypted.KeyId, "utf8");
    const recorded = Buffer.from(envelope.keyArn, "utf8");
    if (
      returned.byteLength !== recorded.byteLength
      || !timingSafeEqual(returned, recorded)
    ) {
      throw new CredentialEnvelopeError("KMS unwrapped the data key under an unexpected CMK");
    }
  }

  const dataKey = Buffer.from(decrypted.Plaintext);
  try {
    const decipher = createDecipheriv(
      "aes-256-gcm",
      dataKey,
      Buffer.from(envelope.iv, "base64url"),
    );
    decipher.setAAD(additionalData(scope));
    decipher.setAuthTag(Buffer.from(envelope.tag, "base64url"));
    const cleartext = Buffer.concat([
      decipher.update(Buffer.from(envelope.ciphertext, "base64url")),
      decipher.final(),
    ]).toString("utf8");
    const parsed = JSON.parse(cleartext) as unknown;
    if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new CredentialEnvelopeError("The sealed credential payload is not an object");
    }
    const record = parsed as Record<string, unknown>;
    if (
      typeof record.accessKeyId !== "string" || typeof record.secretAccessKey !== "string"
      || (record.sessionToken !== undefined && typeof record.sessionToken !== "string")
    ) {
      throw new CredentialEnvelopeError("The sealed credential payload is incomplete");
    }
    return {
      accessKeyId: record.accessKeyId,
      secretAccessKey: record.secretAccessKey,
      ...(record.sessionToken === undefined ? {} : { sessionToken: record.sessionToken }),
    };
  } catch (error: unknown) {
    if (error instanceof CredentialEnvelopeError) throw error;
    // An authentication failure must not describe which check failed.
    throw new CredentialEnvelopeError("The stored credential envelope failed authentication");
  } finally {
    zeroize(dataKey);
  }
}
